### ISSUE TITLE
Template translate does not work as expected

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#1354] opened 2013-04-02 15:18 UTC
What stated in documentation http://doc.silverstripe.org/framework/en/3.1/topics/i18n#usage-in-template-files doesn't work.
- Template file: http://pastie.org/7280012
- # sake /dev/tasks/i18nTextCollectorTask --- Running Task i18n Textcollector Task ---  (no more output)
- themes/mySimple/lang/en.yml is updated like this: http://pastie.org/7280023
- copied it into it.yml: http://pastie.org/7280032
- # sake /dev/build "flush=all"

not working...

**Comment by g4b0** [comment] 2015-01-14 14:26
It seems that the problem is still around in 3.1.8

**Comment by nonconformatevi** [comment] 2015-01-14 14:40
I confirm that this error persists on 3.1.8 version

**Comment by chillu** [comment] 2015-02-21 07:54
I've just tried this out in the 3.1 branch, works for me. Check `i18n::include_by_locale()`, it does a `scandir($themesBase)` - which has been there for a while (2011). One bug which might be related: `i18n::get_existing_translations()` doesn't run the same checks on `/themes`, so in cases where the locale ONLY exists in `/themes` this might be an issue. Since your example uses `it`, that's not applicable here though.

**Comment by dhensby** [comment] 2016-09-14 15:22
@tractorcow thoughts on this? You recently did work on this stuff

**Comment by tractorcow** [comment] 2016-11-16 02:33
Yep, there's a bug in theme language files. I've updated the string detection code considerably, but it looks like localisation in the themes folder isn't working.

You might be better to move your strings to `mysite/lang` for the time being until it's fixed.

**Comment by chillu** [comment] 2017-02-16 23:20
I'm not sure if that's still an issue in 3.x, but it was definitely a regression in 4.x - which I've fixed with https://github.com/silverstripe/silverstripe-framework/pull/6628

**Closed** 2017-02-17 08:24 UTC
Labels: change/patch
