### ISSUE TITLE
[3.3.1] Drag & drop SiteTree reordering on root 

### ISSUE THREAD

**Issue by t3hn0** [silverstripe/silverstripe-framework#5216] opened 2016-03-21 13:50 UTC
Drag&drop reordering in tree view doesn't work correctly on root. I cannot reorder pages on root if they contain children (it works if page doesn't contain any children).

I tried to pull latest updates but without changes

**Comment by dhensby** [comment] 2016-03-21 14:13
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/744 ?

**Comment by tractorcow** [comment] 2016-03-22 04:49
It sounds like it's the first bullet point issue.... you need to drag-drop not in the spaces between pages, but either the top or bottom of existing root pages.

Just to give the benefit of the doubt, are you getting any ajax errors @t3hn0 ?

**Comment by t3hn0** [comment] 2016-03-22 08:08
@tractorcow: no there're no JS errors.
@dhensby: doesn't seem like it. When I drag page with children it doesn't show me option to drop it between pages.

Summary:
1. It's only affecting pages with children on root level. It offers me only to add page under another page.
2. I can move a page from root to 2nd or lower level.
3. Sorting/moving pages on sublevels works fine.

**Comment by dhensby** [comment] 2016-03-22 11:23
Do you have any custom canEdit/canCreate rules or logic?

There is no "canReorganise" permission which means that this feature relies on checking canCreate which can cause issues (also already reported)

**Comment by t3hn0** [comment] 2016-03-22 12:02
As the matter of fact I do. I added custom canCreate which allows to add only one page for selected ClassName.

**Comment by dhensby** [comment] 2016-03-22 12:20
That's likely the issue, then :( dupe of https://github.com/silverstripe/silverstripe-cms/issues/657

it's also a CMS issue, so closing

**Closed by dhensby** 2016-03-22 12:20 UTC
