### ISSUE TITLE
Remove noisy bottom row from default HTMLEditorField

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8865] opened 2019-03-19 00:21 UTC
It shows the breadcrumbs to the HTML tag, which isn't super useful to the majority of content authors. Given how common TinyMCE is, those 20px in height add a LOT of clutter overall. Particularly now that we're starting to embed TinyMCE in more constrained views such as block inline editing.

![image](https://user-images.githubusercontent.com/111025/54571921-abfc0880-4a49-11e9-996e-cf475e87d832.png)

**Comment by clarkepaul** [comment] 2019-03-20 01:28
Related: upgrade to newer TinyMCE which would remove this feature anyway https://github.com/silverstripe/silverstripe-admin/issues/675

**Comment by lerni** [comment] 2019-05-20 18:54
I agree it shouldn't be there and since I cannot see movement in #675 & #653 I suggest to just set https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/HTMLEditor/TinyMCEConfig.php#L263 to false but probable to late for 4.4 ;(

**Comment by maxime-rainville** [comment] 2019-10-14 00:50
Just had a quick glance to see how easy this would be. You can use you can use the [`statusbar: false` option](https://www.tiny.cloud/docs-4x/configure/editor-appearance/#statusbar) to hide the that bottom bread crumb thingy. The problem is that the resize handle is also part of the status bar ... so if you disable the status bar, you indirectly disable the ability to resize your editor.

To try it out, all you need to do is update `TinyMCEConfig::$settings` with a `'statusbar' => false` entry.

This [S/O question discuss how you can disable the breadcrumb bit without disabling the resize](https://stackoverflow.com/questions/44623026/remove-status-bar-and-keep-resize-icon-in-tinymce-4) handle. But you're still left with empty status bar. One response suggested using CSS to hide the status bar while keeping the resize handle ... it looks a bit hackish but it could work.

@clarkepaul If you think loosing the ability to resize is an acceptable trade-off and I can create a quick PR.

**Comment by clarkepaul** [comment] 2019-10-14 00:59
@maxime-rainville no we really need to keep the resize functionality. It's horrible editing large images and bodies of text in the small area. If we can't remove the breadcrumb then can we reduce the impact of it height-wise? It might just need to wait until TinyMCE gets upgraded as its only about 12 pixels in height there ...
![image](https://user-images.githubusercontent.com/555033/66725147-d2244280-ee8a-11e9-939b-872957d8fbaf.png)

**Comment by michalkleiner** [comment] 2019-10-14 01:13
I'd vote for keeping the resizing as well. However, I don't think this is a high impact issue.

**Comment by maxime-rainville** [comment] 2019-10-14 02:05
We could remove the breadcrumb and reduce the space allocated to the status bar with some CSS.

![image](https://user-images.githubusercontent.com/1168676/66726052-92ae2400-ee93-11e9-93ba-59300a922b66.png)

There's a way you can set the height of the status bar to zero and have the resize handle float over the scroll bar but that may lead to some weird results. Not sure how browsers will handle have some DOM element float over a scroll bar.

![image](https://user-images.githubusercontent.com/1168676/66726096-de60cd80-ee93-11e9-9252-bf4f6305b951.png)

**Comment by clarkepaul** [comment] 2019-10-14 05:48
In my opinion, the best result would be to minimize the height of breadcrumb but have it remain functional. They are actually useful for navigating up and down the HTML, is that possible?

**Comment by maxime-rainville** [comment] 2019-10-15 21:05
# Current (37px)
![image](https://user-images.githubusercontent.com/1168676/66869277-85ac4480-effb-11e9-9338-c72ac9c29c4e.png)

# No vertical padding (20px)
![image](https://user-images.githubusercontent.com/1168676/66869309-9d83c880-effb-11e9-8770-2b39bf1ca5a4.png)

# No vertical padding + reduce font-size/line-height (16px)
![image](https://user-images.githubusercontent.com/1168676/66869549-27cc2c80-effc-11e9-88cd-676f8beb9bca.png)

**Comment by michalkleiner** [comment] 2019-10-15 21:19
Each of the breadcrumbs is a button allowing editors to navigate and select the parent elements. It's not particularly usable on mobile already, but reducing the font-size/line-height makes the touch target even smaller.
I reckon the editing experience on mobile needs to be considered as well (not only in this particular case).

**Comment by clarkepaul** [comment] 2019-10-16 01:16
Lock-in option B @maxime-rainville :)

**Comment by GuySartorelli** [comment] 2022-07-16 03:20
Closing because it's extremely unlikely we will be doing this 8n CMS4, and were intending to upgrade to tinymce6 in CMS5.

**Closed by GuySartorelli** 2022-07-16 03:20 UTC
Labels: type/enhancement, complexity/low, impact/high, affects/v4, type/UX
