### ISSUE TITLE
ModelAdmin has_many searchForm queueing causes hang

### ISSUE THREAD

**Issue by mikeyc7m** [silverstripe/silverstripe-framework#9091] opened 2019-06-25 23:06 UTC
## Affected Version

4.3.1

## Description

The new ModelAdmin searchForm uses a graphql search lookup service. It is being applied to has_many relationships on a dataobject in modeladmin and this can cause queueing and the user experiences delays. Also when the search field is exposed, the "Link Existing" field disappears.

## Steps to Reproduce

We've got a complex data model with 41 has_many relationships on a particular dataobject. When we use ModelAdmin to edit that object, we see an explosion of graphql queries to load the search forms for those 41 relationships. The browser can only handle a handful of queries at a time, so they all get queued up and the user has to wait for them all to complete. Many of the requests return 400 error anyway (response is "No search form could be generated"). Is there a way to disable the search lookup per relationship?

Perhaps it would be more preactical if the searchForm schema was queried on demand (when someone clicks the search icon) rather than all relationships queried on page load?

**Comment by mikeyc7m** [comment] 2019-07-01 07:09
yeah the cms is unusable because of this, any ideas on how to correct?

**Comment by maxime-rainville** [comment] 2019-08-20 20:50
This is probably related to https://github.com/silverstripe/silverstripe-admin/issues/700

If we could update the react search component when you actually click the search button, that would probably solve your problem as well.

**Comment by ScopeyNZ** [comment] 2019-08-20 21:40
Yeah I'm going to close this as a duplicate of silverstripe/silverstripe-admin#700. Hopefully we can get to this with priority...

**Closed by ScopeyNZ** 2019-08-20 21:40 UTC
