### ISSUE TITLE
Remove `remove()` from DataList

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#8973] opened 2019-05-09 10:24 UTC
## Affected Version

All

## Description

Currently, there are `remove()` methods on DataList and the different *ManyList objects. While the ManyList objects remove the _relation_ between the an object and the item in the list, on DataList, the object on the list is completely deleted from the database, like with a `delete()` operation on DataObject.

This causes confusion among developers and unexpected items disappearing from the database.

## Suggestion

Rename the `remove()` methods on DataList to `delete()`, and deprecate the `remove()` functionality in favour of the delete method.

This will reduce accidental `remove()` calls on a DataList, expecting a relation to be deleted, and is more in line with the `delete()` method on DataObject, which also actively deletes the item.

It also improves clarity, remove is the removal of a relation, and delete is the deletion of the actual object.

Relevant starting point of discussion about this on Slack: https://slackarchive.silverstripe.org/slack-archive/message/278042

**Comment by robbieaverill** [comment] 2019-05-09 21:08
Thanks for raising the issue, closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8714

**Closed by robbieaverill** 2019-05-09 21:08 UTC

**Comment by Firesphere** [comment] 2019-05-09 23:08
Gah, why is the search on here so crappy? I spent 30 minutes searching for a relevant duplicate, yet nothing came up.
