### ISSUE TITLE
filterAny is ignoring records with empty field values in many_many relationship

### ISSUE THREAD

**Issue by garethjpeters** [silverstripe/silverstripe-framework#7588] opened 2017-11-13 10:45 UTC
**filterAny** is ignoring records that don't have many_many relationship, for example:

### **Database:**

Joes

ID | FirstName | Surname
-- | -- | --
1 | Joe | Bloggs
2 | Joe | Pesci
3 | Joe | DeMaggio

Cars

ID | Title
-- | --
1 | Porche
2 | Ferrari
3 | VW

Joes_Cars

ID | JoesID | CarsID
-- | -- | --
1 | 1 | 1
2 | 1 | 3
3 | 3 | 2

 

### **Filter:**
`return = Joes::get()
        	->filterAny(array(
	        	'FirstName:PartialMatch'	=>	'Joe',
	        	'Cars.Title'	=>	'Joe'
        	))`

This only returns 2 records (Bloggs and DeMaggio) and ignores Pesci due to him not having a many_many relationship with Cars specified.

I am trying to perform a "search anything" type of search that will search across all tables for a specified term. The above filter should search for "Joe" whether it appears in the **Joes** table or the **Cars** table but is unfortunately only searching the records where a relationship has been set up.

**Comment by kinglozzer** [comment] 2017-11-13 11:30
@garethjpeters Thanks for reporting this, could you confirm which version of SilverStripe are you using?

**Comment by garethjpeters** [comment] 2017-11-13 11:33
@kinglozzer, it's 3.5.3 - thanks!

**Comment by dhensby** [comment] 2017-11-15 17:14
OK - so the problem is that this uses an `INNER JOIN` on the link table, so if you're not in the link table you won't get a result.

Instead it needs to be a `LEFT JOIN` but I'm not sure how that'll possibly affect other queries :/

**Comment by tractorcow** [comment] 2017-11-16 23:52
Fixed in 3, needs merging up to 4.

**Comment by tractorcow** [comment] 2018-01-15 02:27
Merged up. :)

**Closed by tractorcow** 2018-01-15 02:27 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/bug
