### ISSUE TITLE
SS3.5: Different template behaviour of $FunctionName(args) and $getFunctionName(args)

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#6402] opened 2016-12-15 14:05 UTC
```php
class Page_Controller extends Controller {
   public function getNewItemLink($class, $params = null)
   {
        var_dump($class);
        var_dump($params);
        die();
   }
}
```

SS Template:
```
$NewItemLink('ListingItem',$ID)
```
Produce an error: Missing argument 1 for Page_Controller::getNewItemLink()

SS Template:
```
$getNewItemLink('ListingItem',$ID)
```

works ok

**Comment by kinglozzer** [comment] 2016-12-15 14:17
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/2505. Also see https://github.com/silverstripe/silverstripe-framework/pull/4768 for more info

**Closed by kinglozzer** 2016-12-15 14:17 UTC
