### ISSUE TITLE
Hardcoded /admin/ url segment for my profile 

### ISSUE THREAD

**Issue by mattrayner** [silverstripe/silverstripe-framework#5680] opened 2016-06-10 11:43 UTC
I've discovered a bug in `LeftAndMain_MenuStatus.ss` - if you are using a custom admin URL the myprofile link doesn't work.

i.e. with a config like this:

```yaml
Director:
  rules:
    'admin': ''
    'my_custom_admin': 'AdminRootController'
AdminRootController:
  url_base: 'my_custom_admin'
LeftAndMain:
  url_base: 'my_custom_admin'
  url_segment: 'my_custom_admin'
```

The expected my profile url would be `{$AbsoluteBaseURL}my_cusom_admin/myprofile` but is hard coded on line 6:

```
<a href="{$AbsoluteBaseURL}admin/myprofile" class="profile-link">
```

I'm not sure if this helps but on the controller level I'd use something like:
```php
Config::inst()->get('AdminRootController', 'url_base')
```

**Comment by mattrayner** [comment] 2016-06-10 12:35
Should be fixed by #3274 for version 4 - would love to see it for 3.* too

**Comment by tractorcow** [comment] 2016-07-05 06:45
Dupe of https://github.com/silverstripe/silverstripe-framework/pull/3274

**Comment by tractorcow** [comment] 2016-07-05 06:45
Well, I guess it can stay open... since #3274 is a PR not an issue. :P

**Comment by sminnee** [comment] 2016-09-21 01:57
Looks like the relevant PRs have been merged into SS4.

**Closed by sminnee** 2016-09-21 01:57 UTC
