### ISSUE TITLE
TreeDropdownField has page icon when a value is selected

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#7420] opened 2017-10-02 17:04 UTC
In 3.6.2 (maybe 3.5.5) the TreeDropdown field now has the page icon displayed when a value is selected causing the title of the page to wrap outside of the dropdown. The issue goes away when you open the dropdown and allow it to close, you don't even need to change items. This appears to be appearing correctly in 3.6.1. This was observed in Settings, so I wonder if this should be opened in that module instead? Though it maybe happening outside of there as well.

![treedropdown-bug](https://user-images.githubusercontent.com/1391558/31089422-640a49b0-a77a-11e7-90fe-570dda94db24.png)

**Comment by axllent** [comment] 2017-10-03 20:53
I was just coming here to report the same thing. It's not limited to settings, but rather any use of the TreeDropdownField (eg: RedirectorPage) which seems to fall under the framework module in SS3. The bug appears to have been introduced in 3.6.2 (3.6.1 doesn't have it).

From what I can tell a simple `.page-icon{float: left;}` attribute is probably enough (currently displayed as block, ie: the issue here), though I'm not sure where else `.page-icon` is being used, so it may likely need to be more precise than that.

**Comment by kinglozzer** [comment] 2017-10-04 16:01
Seems to be a regression from https://github.com/silverstripe/silverstripe-cms/pull/1936, PR here: https://github.com/silverstripe/silverstripe-cms/pull/1983

**Comment by tractorcow** [comment] 2017-10-05 00:48
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1983

**Closed by tractorcow** 2017-10-05 00:49 UTC
Labels: affects/v3, change/minor, effort/easy, impact/medium, type/bug, type/UX
