### ISSUE TITLE
ChangePasswordForm Validation Message

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-framework#4050] opened 2015-03-31 02:17 UTC
https://github.com/silverstripe/silverstripe-framework/pull/2978

It looks like the solution to this issue was proposed, however never implemented.

**Comment by dhensby** [comment] 2015-03-31 21:06
Change it in what way?

**Comment by NGlasl** [comment] 2015-04-21 06:32
Simon pointed out that Form->sessionMessage() only takes two arguments in 3.1, however this doesn't look to be the case from what I can see (http://api.silverstripe.org/3.1/source-class-Form.html#1061). The problem is that the list of password validator messages end up being escaped.

**Comment by normann** [comment] 2015-06-17 22:09
#2978 is closed, but the bug is still there.

**Comment by nglasl** [comment] 2015-06-18 00:12
That is correct.

**Comment by dhensby** [comment] 2015-06-18 11:02
Ok, I've reopened the PR so it can be merged. Can someone please provide me with steps to replicate the bug that the PR fixes and I'll investigate.

**Comment by nglasl** [comment] 2015-06-18 23:39
You basically just need to set up a password validator, from what I remember. The error messages will come back being escaped, rather than nicely formatted.

```php
$validator = new PasswordValidator();
$validator->minLength(6);
$validator->characterStrength(2 ,array(
	'lowercase',
	'uppercase',
	'digits'
));
Member::set_password_validator($validator);
```

**Comment by tractorcow** [comment] 2015-07-01 22:05
I've added a new fix at https://github.com/silverstripe/silverstripe-framework/pull/4358

**Comment by nglasl** [comment] 2015-07-13 00:55
This is just waiting on a PR merge.

**Comment by willmorgan** [comment] 2015-07-13 09:48
Duplicate of #2978; closing.

**Closed by willmorgan** 2015-07-13 09:48 UTC
