### ISSUE TITLE
$Pos inside $Me template always returns 1

### ISSUE THREAD

**Issue by jacobsjensen** [silverstripe/silverstripe-framework#6411] opened 2016-12-16 15:24 UTC
Hi Guys, might be me just being dump, but I'm using the content-blocks module (nobrainerweb/silverstripe-content-blocks) and I've hit a bump.

On Page.ss I have an ActiveBlocks loop, in which the onlye thing I have is $Me, which then renders whichever template and data picked by the user. In these templates rendered by $Me I try to access $Pos to check if it's the first item in the ActiveBlocks loop... But it always return 1. 

Is there any way to "get out of that scope"?

If I add $Pos directly inside the ActiveBlocks loop it returns the correct value... No way to pass on a value to $Me as you can with an include?

**Comment by dhensby** [comment] 2016-12-16 16:10
`$Up.Pos` might work?

The functionality you describe is expected and not a bug, so I'm closing this.

**Closed by dhensby** 2016-12-16 16:10 UTC
