### ISSUE TITLE
URLSegmentFilter fails to remove certain non ASCII chars

### ISSUE THREAD

**Issue by TheBnl** [silverstripe/silverstripe-framework#7135] opened 2017-07-05 15:49 UTC
I noticed that the URLSegmentFilter fails to remove some non-ASCII chars while working with an page title containing a ":" This resulted in the controller unable to fetch the right page.

![screen shot 2017-07-05 at 17 52 49](https://user-images.githubusercontent.com/1334195/27873000-ed17c248-61aa-11e7-97ce-21d821797470.png)

![screen shot 2017-07-05 at 17 53 05](https://user-images.githubusercontent.com/1334195/27872999-ed153e9c-61aa-11e7-8b88-6939335035bf.png)

**Comment by tractorcow** [comment] 2017-07-05 21:26
Which framework version were you using?

**Comment by TheBnl** [comment] 2017-07-05 21:53
It was on 3.6.0 that i first noticed it. I updated to 3.6.1 but the issue was also in that version. 

I haven't had (or noticed) the issues with versions below 3.6 and haven't tried it in the 4.0 branches yet.

**Comment by robbieaverill** [comment] 2017-07-13 05:42
I can't reproduce this on SS 3.6.0 or 4.0.0 beta1. [This test](https://github.com/silverstripe/silverstripe-framework/blob/3.6/tests/model/URLSegmentFilterTest.php#L41-L47) shows the expected behaviour here, which is that all non ASCII characters should be stripped.

I assume from the locale indicator that you're using the [Fluent module](https://github.com/tractorcow/silverstripe-fluent)? Perhaps it could be an issue with that module?

**Comment by dhensby** [comment] 2017-07-17 13:54
@robbieaverill thanks for investigating - we have a test that specifically checks for the removal of `:` and it's passing so I'll close this.

**Closed by dhensby** 2017-07-17 13:54 UTC
Labels: affects/v3, affects/v4, change/minor, effort/easy, impact/medium, type/bug

**Comment by TheBnl** [comment] 2017-07-17 20:21
Thanks for looking into it @robbieaverill ! I'll try some combinations of the framework/modules to investigate the issue further.
