### ISSUE TITLE
Naming DBField as "Data" confuses core

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#8088] opened 2018-05-22 20:29 UTC
## Affected Version

framework 4.1.0 / PHP7.0

## Description

Creatiing a simple DataObject with a single `Text` field and naming it "Data" will cause problems when Calling `$this->obj('Data')` in any context. In my case, I am using the restfulserver package which attempts to decompose a `DataObject` into JSON via `JSONDataFormatter` which makes use of `ViewableData::obj()` when casting.

This occurs becuase of the core method `DataObject::data()` which is "blindly" called by `ViewableData::obj()` instead of the desired `DBField` by `SilverStripe\Core\CustomMethods::hasMethod()`.

The problem can be demo'd fairly succinclty below:

## Steps to Reproduce

```
class Page extends SiteTree
{
    private static $db = [
         'Data' => 'Text''
    ];

    public function getCMSFields()
    {
        var_dump($this->obj('Data')); // prints `SiteTree` not `DBText`
        die;
    }
```
## Workaround

The workaround is to declare a method on your datamodel named for the field and call `getField('Data')` from it, thus inverting otherwise default control.

## Suggestions

"Data" is used in a DataObject context as `DataObject::data()` and is therefore a reserved word. As such, userland logic could receive an `Exception` on `dev/build` when attempting to declare a field-name that is reserved. The reserved field-names could be declared as an immutible array in `DataObject` to permit further fields to be added by core-devs in a flexible manner going forward.

# Related PRs
* [ ] #8731

**Comment by maxime-rainville** [comment] 2018-05-22 21:47
I like the idea of throwing an Exception dev/build if a DataObject uses a reserve keyword as a field name. If we're going to do this, it probably be worthwhile to identify further reserve keywords that might casue issues.

**Comment by phptek** [comment] 2018-05-22 22:20
Sure, or just add a single one to the list for now given the frameworks' 10+ year history without any similar issue (AFAIK) otherwise we might be waiting a while ;-)

**Comment by elliot-sawyer** [comment] 2019-01-16 21:22
Suggested code-snippet from @phptek to help out the academy students:

```
public function requireDefaultRecords()
{
	...
	...
    // Protect devs from falling into the trap of naming a DB field after a reserved word
    foreach ($this->getSchema()->databaseFields($this->getClassName()) as $name => $field) {
        if (in_array($name, $this->config()->get('reserved_field_names'))) {
            throw new Exception(sprintf('%s is a reserved field name', $name));
        }
    }
```

**Comment by phptek** [comment] 2019-01-16 21:42
@robbieaverill interesting. Is throwing an exception in any area of the dev/build pipeline considered a major change?

What we could do instead is simply echo a warning to the CLI / GUI during dev/build. but not explicitly halt execution. Then again, dev's may quite easily miss that - but is that better than the status quo?

**Comment by robbieaverill** [comment] 2019-01-16 21:48
We’ve “avoided” this issue in the past by issuing a `user_warning` instead. Having said that, you’re defensively coding against changes that won’t work in practice anyway, so we could probably justify an exception here as a minor semver change

**Comment by phptek** [comment] 2019-01-16 21:57
I thought I read somewhere that SilverStripe (devs) are really looking to move away from `user_error()` and `trigger_error()` etc, for precisely the reason you _would_ want to use an `Exception`.

And yeah, you're bang-on wr/t this being a change to something that is already "broken". Nice one. I'll leave it to the academy devs then :-)

**Comment by kinglozzer** [comment] 2019-01-17 09:33
Another one to add to the list: `Author` seems to have issues in some scenarios where versioning is enabled, I just can’t for the life of me figure out why...

**Comment by tractorcow** [comment] 2019-01-17 21:40
Couldn't the exception be whenever the dbfield matches a method on that class? E.g. 

```
public function requireDefaultRecords()
{
	...
	...
    // Protect devs from falling into the trap of naming a DB field after a reserved word
    foreach ($this->getSchema()->databaseFields($this->getClassName()) as $name => $field) {
        if (method_exists($this, $name)) {
            throw new Exception(sprintf('%s cannot be both a db field and a method', $name));
        }
    }
```

This still allows db fields to be overridden with `getTheField` / `setTheField`, but prevents conflicts between `getTheField()` and `thefield()`

**Comment by phptek** [comment] 2019-01-17 22:59
I like it.

**Comment by tractorcow** [comment] 2019-01-18 01:19
Note that there's a PR already at https://github.com/silverstripe/silverstripe-framework/pull/8731

**Comment by robbieaverill** [comment] 2019-06-18 04:48
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6329

**Closed by robbieaverill** 2019-06-18 04:48 UTC
Labels: affects/v4, change/minor, effort/easy, impact/low, type/enhancement
