### ISSUE TITLE
Handle empty strings in translations (either in transifex or in code)

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-framework#9791] opened 2020-12-07 03:10 UTC
## Affected Version

Silverstripe CMS Recipe 4.x, 5.x

## Description

The current behaviour of our i18n layer (powered by `symfony/translation`) is that when it encounters an empty value for a translation, it accepts and returns it. For example, given the following language file:

```yml
en:
  My\Class:
    HELLO: ''
```

This code will output a blank string:

```php
return i18n::_t(__CLASS__ . '.HELLO', 'Hello');
```

This isn't necessarily _incorrect_ behaviour, but recently Transifex has been [populating language files with empty values](https://github.com/silverstripe/silverstripe-versioned-admin/commit/ae029a698e013aa93642478815a8933b6f063028#diff-4ccd4fb8579bf53c4662ed7448674f50df9c095155682a3d69cd90351e3cd072R8) when translations are incomplete, which results in empty elements in the UI. These would be better off using the fallback value, which may not be directly interpretable by the user but can at least be translated by hand.

**NOTE:** I'm not completely confident that this is a safe change - if anyone can point to a term that would accurately translate as an empty string, we'll need to find a way to solve this at the translation update layer.

## Acceptance criteria
- [ ] Empty strings are removed from translation files in transifex
- [ ] All modules have their translations re-pulled from transifex to avoid printing the empty strings
- [ ] The translation tool has a way to detect and resolve this problem automagically

## NOTE
We should consider whether to give the same treatment to "translated" strings that are identical to the English strings, which is also something that seems to happen a lot and ends up showing as 100% translated in transifex even though they're still in English.

**Comment by emteknetnz** [comment] 2023-03-09 01:46
Duplicate of https://github.com/silverstripe/.github/issues/14

**Closed by emteknetnz** 2023-03-09 01:46 UTC
Labels: complexity/low, impact/high, affects/v4, type/bug
