### ISSUE TITLE
Silverstripe 3.1- Styles and Scripts moves into HTML Body in Debug mode

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-framework#3931] opened 2015-02-24 05:04 UTC
When print or show messages in Debug the styles and scripts moves from head to body after render.

**Comment by kinglozzer** [comment] 2016-03-26 18:44
Duplicate of #1894

**Closed by kinglozzer** 2016-03-26 18:44 UTC

**Comment by dhensby** [comment] 2016-03-26 19:31
I don't think it is. But this won't be fixed because debugs are echos
