### ISSUE TITLE
Folder->syncChildren() deletes existing folders if name contains a dot

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#4746] opened 2015-11-05 17:56 UTC
I have been able to reproduce a bug that seems to delete Folders if they contain a `.`

Steps to reproduce:

1. create a new folder `foo.bar`
2. upload files into said folder
3. press "sync files" in the assets admin
4. database record for foo.bar and all children will be deleted, but filesystem remains existing

Either we should filter out dots in names like we do with other special characters or fix `syncChildren()`
(So far I have not debugged the issue though, only tested on 2 `3.2` and 1 `3.2.x-dev` instances)

**Comment by anselmdk** [comment] 2015-11-05 17:58
I can reproduce it. Actually I just went through it together with @Zauberfisch.

**Comment by tractorcow** [comment] 2015-11-09 04:35
Ouch, those files will be an issue, since they aren't valid "urlsegment" names. Framework would possibly try to rename them.

Maybe a better solution is to make syncChildren ignore folders with names it doesn't deem valid?

**Comment by Zauberfisch** [comment] 2015-11-09 08:46
I'd say the most critical issue about this is that the assets admin actually lets you create folders with a `.`. And upload files to it.
So basically everything works until you press the sync button.

But indeed, there is still the possibility of a folder being created directly on the server, in that case I don't really have a good answer.

**Comment by tractorcow** [comment] 2015-11-09 20:09
This behaviour is getting changed in 4.x anyway. filesystem sync will be removed altogether. ;)

**Comment by jonom** [comment] 2016-03-04 18:03
@tractorcow why isn't it valid for URLSegment names to contain dots?

**Comment by jonom** [comment] 2016-03-04 18:22
The [filename filter](https://github.com/silverstripe/silverstripe-framework/blob/3/filesystem/FileNameFilter.php#L42-L48) seems to be okay with dots in file and folder names and this is the way it should be I think - I couldn't find any [resources](http://superuser.com/questions/358855/what-characters-are-safe-in-cross-platform-file-names-for-linux-windows-and-os) saying dots need to be avoided in directory names. I tried creating a 'test.test' folder and placing an image in it and was able to load the image in a browser and resize in templates. Everything seems to work so I think the file sync process just needs a patch.

**Comment by jonom** [comment] 2016-03-04 18:57
Have found cause and fix for this. @tractorcow should I target 3.3 branch or something earlier?

Folder::syncChildren() is validating file extensions on files and folders indiscriminately, so unless your folder is called something like "folder.doc" it's going to flag the folder for removal. Solution is to skip this check for directories.

**Comment by tractorcow** [comment] 2016-03-07 02:30
It sounds like a bugfix, so I guess 3.2 is fine.

**Comment by jonom** [comment] 2016-03-07 21:47
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5152

p.s. I wonder why this didn't auto-close? Does it need to be merged to master before that kicks in?

**Closed by jonom** 2016-03-07 21:47 UTC

**Comment by kinglozzer** [comment] 2016-03-08 10:02
@jonom I believe the title (or first line) of the commit message needs to contain the `fixes #1234` part, not the description: https://github.com/silverstripe/silverstripe-framework/commit/86b1c8fc2849e8f65f473286a3b2d09f4b76eaf7

**Comment by jonom** [comment] 2016-03-08 18:02
Ah, cheers Loz

**Comment by jonom** [comment] 2016-03-08 18:03
Oh actually I was curious so I checked - only works when merging in to the default branch apparently: https://help.github.com/articles/closing-issues-via-commit-messages/
