### ISSUE TITLE
Media tabs retaining browser default visual focus

### ISSUE THREAD

**Issue by feejin** [silverstripe/silverstripe-framework#4875] opened 2015-12-23 14:44 UTC
Not really a problem, just not very pretty. The tabs can't be navigated with TAB (at least not in Safari with TAB navigation enabled) so having a :focus outline seems redundant anyway.

Occurs to Chrome 47.0.2526.106 and Safari 9.0.2, does not occur in Firefox 42.

![safari](https://cloud.githubusercontent.com/assets/1774129/11978314/74a4c7f2-a982-11e5-9fbb-765591ce69e1.png)

**Comment by jonom** [comment] 2015-12-23 18:48
I happened to be looking at this same issue yesterday. It seems to be a jQuery UI 'feature' but I find it bizarre. That styling is caused by a css class which is added by javascript, rather than a `:focus` pseudo-class. It occurs in a few places throughout the CMS.

Ideally we'd remove these styles but I'm not sure it will be trivial. Then we could apply a similar effect with a `:focus` style but nullify it with an `:active` style so you get a blue outline when tabbing around, but not when you click something.

**Comment by tractorcow** [comment] 2016-01-11 22:14
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4900

**Closed by tractorcow** 2016-01-11 22:14 UTC
