### ISSUE TITLE
CMS Regression: Site Tree disappears in CMS on 3.7.0 - it's fine on 3.6.6

### ISSUE THREAD

**Issue by azt3k** [silverstripe/silverstripe-framework#8169] opened 2018-06-12 23:51 UTC
## Affected Version

3.7.0

## Description

Site Tree disappears in CMS on 3.7.0 - it's fine on 3.6.6.

Looking at the code it appears to be related to some changes in `Hierarchy->getChildrenAsUL` and the number of items in the root node being >30.  This behaviour is probably partially intentional, however there is no way to change what the threshold value is and from a client perspective upgrading from <= 3.6 breaks their site.

Setting the following in the `Hierarchy->getChildrenAsUL` method resolves the issue:

`$nodeCountThreshold=null`
`$limitToMarked=false`

These are actually the default values, but you can see how the working defaults are overridden in the call stack below:

````php
Hierarchy->getChildrenAsUL(,Closure,CMSPagesController,1,AllChildrenIncludingDeleted,numChildren,1,30,Closure)
call_user_func_array(Array,Array)
Object.php:746
SS_Object->__call(getChildrenAsUL,Array)
LeftAndMain.php:941
SiteTree->getChildrenAsUL(,Closure,CMSPagesController,1,AllChildrenIncludingDeleted,numChildren,1,30,Closure)
LeftAndMain.php:941
LeftAndMain->getSiteTreeFor(SiteTree)
CMSMain.php:292
CMSMain->SiteTreeAsUL()
ViewableData.php:466
ViewableData->obj(SiteTreeAsUL,,,1)
ViewableData.php:539
ViewableData->XML_val(SiteTreeAsUL,,1)
````

There does appear to be a config var that could be used to resolved half the issue, but it never gets accessed because `$nodeCountThreshold` is always numeric based on the call stack above

````php
	 		if(!is_numeric($nodeCountThreshold)) {
	 			$nodeCountThreshold = Config::inst()->get('Hierarchy', 'node_threshold_total');
	 		}
````

Interestingly copying  the `Hierarchy->getChildrenAsUL` method from 3.7 into 3.6 breaks the site tree as well, but just setting `$nodeCountThreshold=null` is enough to resolve the issue which would imply that there may also an issue with how `$child->isMarked()` is handled in 3.7.

## Steps to Reproduce

Upgrade to 3.7.0 from 3.6.6 with a site tree larger than 30 and the site tree disappears.

**Comment by robbieaverill** [comment] 2018-06-12 23:52
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/2183

**Closed by robbieaverill** 2018-06-12 23:52 UTC
