### ISSUE TITLE
Session::regenerateSessionId may cause warnings

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#9496] opened 2020-04-24 16:08 UTC
## Affected Version

4.5.3 

## Description

Recently found this in my logs in production:

error-log.WARNING: E_WARNING: session_regenerate_id(): Cannot regenerate session id - session is not active {"code":2,"message":"session_regenerate_id(): Cannot regenerate session id - session is not active","file":".../vendor/silverstripe/framework/src/Control/Session.php","line":652} 

This happens when sending password reset links

## Steps to Reproduce

Get a password reset link, open an incognito window, paste the reset link (in my case, it's hidden by a tracking link from the mail api, so it triggers a redirect) : you get the warning

It may well be due to the incognito window freshly opened or the redirection from the mail api. In any case, it shouldn't happen

Possible ways to solve it:
- prepend @ in front of the call (like in vendor\silverstripe\framework\src\Security\MemberAuthenticator\SessionAuthenticationHandler.php)
- check if session is active, something like this seem to work fine for me in my current hotfix

```
if (!headers_sent() && session_status() == PHP_SESSION_ACTIVE) {
  session_regenerate_id(true);
}
```

**Comment by kinglozzer** [comment] 2020-04-27 08:25
Gah, we’ve already fixed this once (https://github.com/silverstripe/silverstripe-framework/issues/9259), obviously not properly :(

Fancy submitting a PR @lekoala?

**Comment by dhensby** [comment] 2020-04-27 09:01
@kinglozzer your changes are in the 4.5.3 tag (https://github.com/silverstripe/silverstripe-framework/blob/4.5.3/src/Control/Session.php) - so I guess it means there's still an edge case to be dealt with?

**Comment by kinglozzer** [comment] 2020-04-27 09:09
Yeah I think I fixed one trigger for this bug, but not the root cause

**Comment by lekoala** [comment] 2020-04-27 11:52
> Fancy submitting a PR @lekoala?

PR done! https://github.com/silverstripe/silverstripe-framework/pull/9499

**Comment by kinglozzer** [comment] 2020-05-18 08:05
PR merged so this can be closed :D

**Closed by kinglozzer** 2020-05-18 08:05 UTC
Labels: affects/v4, change/patch, impact/low, type/bug
