### ISSUE TITLE
HTTPRequest parameter matching: "extension" is stripped off the final value?

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#5385] opened 2016-04-24 17:50 UTC
SS_HTTPRequest's match function apparently strips off so-called "extensions" off the final parameter in the URL, which is quite unexpected in some cases, for example when an email address is in the URL. 

```php
class UnsubscribePage_Controller extends Page_Controller {
    private static $url_handlers = [
        '$Hash/$Email/$Confirm' => 'unsub'
    ];
    private static $allowed_actions = [
        'unsub'
    ];
    public function unsub() {
        var_export($this->request->allParams());
        die();
    }
}
```

Result: 
```
http://test.web/myPage/myHash/email@example.com/

array (
  'URLSegment' => 'uitschrijven',
  'Action' => 'myHash',
  'ID' => 'email@example',
  'OtherID' => NULL,
  'Hash' => 'myHash',
  'Email' => 'email@example',
  'Confirm' => NULL,
)
```

As you can see, the .com is stripped off the email address. This only happens if $Email is the final parameter; if the $Confirm parameter is added, the .com  is kept. 

I went looking in `SS_HTTPRequest::match` which mentions: "The pattern can contain a number of segments, separated by / (and an extension indicated by a .)". That's the only explanation I can find about it, and it's between brackets as if it's an afterthought, but this is making it impossible to distinguish between very different URLS:
* `/unsubscribe/me@example.com` vs `/unsubscribe/me@example.org`
* `/download/file.pdf` and `/download/file.docx`
etc

Can the stripping of extensions be turned off? Should it even be enabled by default?.. It's very unexpected!

I am using SS 3.3.1.

**Comment by sminnee** [comment] 2016-04-25 21:13
The use-case it was designed for was URLs like `/api1/v1/SiteTree/5.json` vs `/api1/v1/SiteTree/5.xml`. It made sense to process extensions explicitly in such URLs, but not for the ones you point out. Note that `SS_HTTPRequest::getExtension()` returns the extension.

It might be a little hard to fix in SS3 without breaking backward compatibility, but maybe with remove or significantly alter this functionality in SS4?

For SS4, I would suggest that we have something in the url_handler system that lets you mark a URL has optionally having an extension, parsed as a separate variable. We can use this in places like restful APIs.

**Comment by sminnee** [comment] 2016-04-25 21:18
If you're looking for a quick-fix for your own project you might want to do something like:

    if ($extension = $this->getExtension()) $params['Email'] .= ".$extension";

A bit ugly but it should do the job.

**Comment by JorisDebonnet** [comment] 2016-04-26 00:23
I worked around it in my own project by making sure the email address is not the final parameter. I don't mind that it keeps working like this in SS3, but would indeed suggest changing it in SS4 because it's just not intuitive if you don't know about it. Perhaps a twin method could be added alongside getExtension to retrieve the part without the extension, so that the 'raw' parameter can be left alone.

**Comment by robbieaverill** [comment] 2016-04-29 06:14
Could you use a GET parameter instead? Also perhaps the method stripping off the extension might do it only if it detects one it recognises e.g. `.json` or `.xml`

**Comment by tractorcow** [comment] 2016-05-12 05:46
I think we should close this, since the API is behaving as designed. @sminnee's work around solves the problem in your case, right @JorisDebonnet ?

**Closed by tractorcow** 2016-05-12 05:46 UTC

**Comment by sminnee** [comment] 2016-05-12 20:05
It would be an enhancement ticket, if we were to keep it open, which would be okay if someone puts up their hand to work on the feature in the next 3-6 months.

Alternatively someone could just raise a PR when they're done.

My suggested fix would be to alter extension processing to be ah optional feature of the URL matcher, disabled by default and enabled on APIs and other places where it is of use.
