### ISSUE TITLE
alc_enc cookie does not include secure cookie flag

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8234] opened 2018-07-02 20:27 UTC
Reported by @madmatt:

SilverStripe does not set the secure flag on the alc_enc cookie, which means that even if user logins all happen over a secure connection (e.g. Director::forceSSL() on any secure content), any user who selects the 'Remember me' checkbox could leak their token unknowningly, and have someone take over their account.

I think we do this because some sites don't use HTTPS at all, so we can't just set it blindly, but we could potentially handle this in the same way that we already handle it for session cookies (we use PHPSESSID for insecure sessions, and SECSESSID - with the secure flag set - when the session is done over https).

Alternatively, we could remove the ability to 'Remember me' when login is done over http, and then we could reliable set the secure flag on the alc_enc cookie all the time, though that's quite a heavy-handed solution.

Most sites should be moving to HTTPS-everywhere-all-the-time, but this is still good practice to separate cookie usage, and ensure that we set the secure flag where-ever possible.

**Comment by dhensby** [comment] 2018-07-05 15:41
OK - so thinking about this, if the `alc_enc` cookie has the secure flag then if you run a site where the only page that's HTTPS is the sign in page and handler, then the autologin cookie won't actually work until you visit the sign-in page, which is a regression here.

I don't think the alc_enc cookie can ever be marked as secure only otherwise it just won't work most of the time on these mixed HTTP/HTTPS sites.

Maybe we change this in 4.3 as an "enhancement" and only allow it to be set over HTTPS and recommend everyone runs sites on HTTPS all the time?

**Comment by chillu** [comment] 2018-07-05 21:06
Very good point. We could make this configurable (opt-in), and document it where we explain `Director::forceSSL()`. We can't really determine if all your routes are redirected to SSL (`forceSSL()` might be called conditionally, or you might have rules in your CDN or htaccess file). So I don't see how we can ever automatically turn on this flag.

**Comment by dhensby** [comment] 2018-07-05 21:43
Yeah, that's the conclusion I'm coming to.

For sites I know are always HTTPS I replace the core `Cookie_Backend` with my own `SecureCookieJar` which forces the secure flag on (for all cookies). We can't take the state of the current request as guarantee of all subsequent requests.

**Comment by madmatt** [comment] 2018-07-11 11:10
Why can't we do the same thing we do for `PHPSESSID` and use a different cookie for insecure vs. secure sites? The only difference I see is that you might return to e.g. `http://example.com/admin` by typing it in your browser - whereupon you'd expect to get the `alc_enc` cookie picked up but it won't work until you're redirected to https where it would then work... maybe I'm missing something though.

**Comment by chillu** [comment] 2018-07-11 22:54
This is getting a bit complicated, so I wrote out the cases ;)

No HTTPS flow:
 * Access http://example.com/admin
 * Redirect to http://example.com/Security/login
 * Session cookie set via `PHPSESSID`
 * Login with "remember me"
 * Remember me cookie set via `alc_enc` (new: no change)
 * Access http://example.com/: Logged-in
 * Access http://example.com/?stage=Stage: Logged-in
 * Access https://example.com/: n/a

All HTTPS flow:
 * Access http://example.com/admin
 * Redirect to https://example.com/Security/login
 * Session cookie set via `SECSESSID`
 * Login with "remember me"
 * Remember me cookie set via `alc_enc` (new: set `sec_alc_enc`)
 * Access http://example.com/: Redirects, then logged-in
 * Access http://example.com/?stage=Stage: Redirects, then logged-in
 * Access https://example.com/: Logged-in

Mixed flow:
 * Access http://example.com/admin
 * Redirect to https://example.com/Security/login
 * Session cookie set via `SECSESSID`
 * Login with "remember me"
 * Remember me cookie set via `alc_enc` (new: set `sec_alc_enc`)
 * Access http://example.com/: Not logged-in (unless redirect is implemented)
 * Access http://example.com/?stage=Stage: Not logged-in (unless redirect is implemented)
 * Access https://example.com/: Logged-in

Due to the CMS, (nearly) every site made in SilverStripe has logged-in views, due to `?stage=Stage` on pages. We can control the generation of these URLs, and could make them take the protocol used in the CMS (explicitly via BASE_URL, or implicitly via protocol relative URLs). But just because your CMS is on HTTPs doesn't mean all domains serving your site and subsites are.

I agree with @madmatt that the safest way is to have separate `alc_enc` cookies. This way, if you have HTTPS enabled on your website, and don't bother configuring something like `Director::forceSSL(['Security/login'])`, you get a working system both for HTTP and HTTPS, as well as sandboxed, secure cookies (same as PHP sessions). If you care about enforcing HTTPS, you can implement redirects, and SilverStripe's cookies will still work.

**Comment by dhensby** [comment] 2018-07-12 01:16
Something important to note is you have to set `Session.secure_cookie` to true to get the session cookie behaviour you describe on HTTPS; is that typical? I'll admit I had no idea about it and never used it before. Do we need a config option for `Member.secure_alc`?

Are those flows how we want it to work or how it currently works? if the `alc_enc` cookie is not HTTPS only, I'd expect someone in the mixed flow who logged in and chose `remember me` to then be redirected to HTTP for all other pages, they would then send their `alc_enc` cookie and be authenticated in both the HTTP and HTTPS sites.

If we change the cookie to be `sec_alc_enc` wouldn't this now mean users wouldn't be logged into the HTTP site. in effect making it completely impossible to authenticate on the HTTP site... (although I'll admit it seems to be difficult to do if you did set `Session.secure_cookie`).

**Comment by dhensby** [comment] 2018-07-12 12:17
>I'm leaning towards not changing anything here, other than being clearer about our recommendations in docs.

I tend to agree :/ which is a shame as I'd like this improved, but I just can't see how in a workable manner, there seem to be a lot of edge cases to consider.

The internet is moving HTTPS everywhere and with browsers now labelling sites not on HTTPS as "insecure" we should start to assume HTTPS a bit more.

Perhaps in 5 we change it so cookies will set the secure flag of the current request is secure and we remove the ability to forcessl on a set of routes?

**Comment by chillu** [comment] 2018-07-12 23:10
https://github.com/silverstripe/silverstripe-framework/pull/8261

**Closed as completed** 2018-07-30 21:19 UTC
Labels: impact/high, complexity/medium, affects/v4, type/bug
