### ISSUE TITLE
"Please enable pop-ups for this site"

### ISSUE THREAD

**Issue by jacobbuck** [silverstripe/silverstripe-framework#4710] opened 2015-10-27 04:15 UTC
![screen-shot-2015-10-27-at-5 06 30-pm](https://cloud.githubusercontent.com/assets/830470/10749354/3852d75c-7cce-11e5-84fc-638893bd6f32.png)

Is this still necessary in 2015?

Also I get this whenever I have the cms open in a tab while the web server goes down.

**Comment by sminnee** [comment] 2015-10-27 09:43
The underlying issue is that we use a pop-up to let the user re-login without losing their data. I guess it could be re-coded it as something ajax-based, if you want to do that.

**Comment by patricknelson** [comment] 2015-10-27 15:57
I will say that the alert box annoys the hell out of me, even though I've enabled pop-ups. It would be best if this were implemented some other way, since the alert steals focus from your current tab/work and forces you to close it first before moving on again. In my case this happens essentially every day when I close the lid on my laptop and open back up again (since it goes to sleep). To avoid this it would make more sense to use some sort of modal, toaster pop-up or something inline within the page instead of an old school 90's style alert box.

**Comment by patricknelson** [comment] 2015-10-27 16:04
Also I just realized we all have sunglasses in our profile photos.

**Comment by jonom** [comment] 2015-10-27 16:05
@patricknelson Haha!

**Comment by jonom** [comment] 2015-10-27 16:07
Aw, I spoiled the effect by joining the party. :sunglasses: @jacobbuck @patricknelson do one of you guys want to have a stab at changing this behaviour? Otherwise this issue will probably need to be closed as it's a feature request rather than a bug.

**Comment by patricknelson** [comment] 2015-10-27 16:09
Not saying I'd do it, but for reference: Would this go in `master` or `3`? My money is on `3` even though I don't think SS will ever release a `3.3`.

**Comment by jonom** [comment] 2015-10-27 16:21
I would put it in 3 too - I'm pretty hopeful we will see a 3.3 release. Releasing 3.2 took so long because so much had to be reverted to make it semver compliant - 3.3 should be far easier. The goals for 4.0 are pretty ambitious so I wouldn't be surprised if it is a ways off still and we have a 3.3 release in the mean time (who knows - maybe even a 3.4!).

**Comment by sminnee** [comment] 2015-10-27 17:41
3 branch is fine for this change. We'll do a 3.3 release but it will be "low fuss"—we want have a bunch of dedicated product dev time going into 3.3, instead it will just be "here's all the small things that have been added". Beginning of next year, I'd expect.

**Comment by patricknelson** [comment] 2015-10-29 07:39
Ok, see here: https://github.com/silverstripe/silverstripe-framework/pull/4722

You'll see I dropped in some extras since it made sense and I think it's about time, personally. Naturally I found a bug in entwine :facepunch::tired_face:

**Comment by jacobbuck** [comment] 2015-10-29 07:45
![iu](https://cloud.githubusercontent.com/assets/830470/10812693/c8f5c0fc-7e7d-11e5-9c83-98f62dfc50b4.jpeg)

Nice one @patricknelson, and thanks for picking this up :+1:

**Comment by patricknelson** [comment] 2015-10-29 07:49
Also, more to the core of the original point by @sminnee, this bug is less to do with the user logging back in and more to do with a failure of the JavaScript client-side in being able to contact the server, at least temporarily. Shortly after rendering the alert, you may actually reestablish connectivity, so it seems as if it is more of a session timeout; but it's not. Currently (prior to my PR, at least) all the server did is just say "Yep, ok you want a ping? Here's a 1!" and that's it. It didn't actually check your session at all. So if that failed -- it was entirely network related, so **not** use a popup to get the user to attempt to debug their connection issues is actually quite risky for the state of the current page and using an `alert()` dialog is a very good idea if you have little/no time to implement a better solution (which I think I may have).

However, this is a perfect opportunity to pose the "Hey you're logged out, buddy" dialog while they're idle. It's also a good opportunity to get rid of the damned alert message if indeed the JS code can re-establish connectivity. If it cannot, then the message remains. See the PR (https://github.com/silverstripe/silverstripe-framework/pull/4722) for a more specific outline of what the goals are, generally.

**Comment by patricknelson** [comment] 2015-10-29 07:54
@jacobbuck here I've made some "Damn Songlasses" for this thread :+1: 

![dam-songlasses](https://cloud.githubusercontent.com/assets/4269377/10812870/bbcd19da-7df0-11e5-810a-b3b4c71a4c8c.jpg)

**Comment by jacobbuck** [comment] 2015-10-29 08:09
Hahaha seems appropriate :sunglasses:

**Comment by dhensby** [comment] 2016-03-26 21:43
#worstfeatureever

**Comment by tractorcow** [comment] 2016-03-30 00:56
> The underlying issue is that we use a pop-up to let the user re-login without losing their data. I guess it could be re-coded it as something ajax-based, if you want to do that.

This should be in a modal not a new window.open, but I can see some parts of the frontend code still try to do that.

See my comment at https://github.com/silverstripe/silverstripe-framework/pull/4722#discussion_r57824622

**Comment by patricknelson** [comment] 2016-03-30 02:42
I've replied to that here: https://github.com/silverstripe/silverstripe-framework/pull/4722/files/0d0b91ce68bd68cb6a73745c802d74df3b9020d5#r57829168

Basically, the in-CMS login dialog is already implemented (per memory). The issue is more relating to preventing obscuring the user's work in case the server is down to help prevent possible data loss if they get interrupted mid-sentence (for example) since it's entirely possible that internet/server could go down whilst working on an article.

**Comment by tractorcow** [comment] 2016-03-31 21:20
If the server is down then they are pretty much out of luck no matter what happens. :P

I think we should avoid using window.open however, since we have another dialog which addresses the issue where a session is lost but recoverable.

**Comment by jacobbuck** [comment] 2016-03-31 21:48
Agreed. But it would be nice if we could show a modal to tell the user the server is inaccessible, giving the user an option to refresh the page or dismiss it.

**Comment by patricknelson** [comment] 2016-03-31 21:58
Right. You definitely need a way to ensure you can get back to your work if indeed your connection is severed or the server dies. Again, data loss is my main concern for the average user who doesn't know how to open dev tools and delete elements obscuring their work so they can copy/paste it into word while they wait for their local happy web dev to come save the day.

**Comment by dhensby** [comment] 2016-04-06 15:21
> Agreed. But it would be nice if we could show a modal to tell the user the server is inaccessible, giving the user an option to refresh the page or dismiss it.

As long as it doesn't come up every time there's a ping!

**Comment by patricknelson** [comment] 2016-04-06 17:58
Good point! Maybe the display of a banner at the top which can still be dismissed, doesn't overlap anything and reports the current status of the ping (unless the page is refreshed successfully or latest ping is successful).

**Comment by patricknelson** [comment] 2016-04-06 18:05
p.s. Clicking the "x" on that small banner could trigger the JavaScript to reissue another ping just to confirm the server is back online, causing it to reappear again shortly thereafter. In fact, maybe it can work similar to how Google Chat does where it has a countdown timer.

**Closed** 2018-07-27 03:12 UTC
Labels: affects/v3, change/minor, type/enhancement
