### ISSUE TITLE
Summary fields from relation throws error when having the same base class

### ISSUE THREAD

**Issue by kreationsbyran** [silverstripe/silverstripe-framework#2263] opened 2013-07-24 13:46 UTC
The ORM is failing with following conditions:

The Modeladmin manages two dataobjects that inherit from same base class (ex BaseDataObject.php). These dataobjects relate to each other. And the summaryfield array points to the other. Ex:

static $summary_fields = array(  
    'DataObject1.Title'  
 );

When searching for the Title of DataObject1 from the DataObject2s summaryfields (in the ModelAdmin) the ORM breaks. Apparently it cant do a related dataobject search if the dataobjects inherit from the same base class. Bug!

This bug i verified in both SS 3.0.5 and in SS 3.1 Beta 3. I've provided a screenshot of the errror and also a link to a mysite folder that has these classes set up so you can test for yourselves.

![image](https://f.cloud.github.com/assets/1451160/848695/b6ea0cea-f466-11e2-80ed-3d00d1fc7291.png)

In the mysite example the name of the classes are:
Base Class: BaseDataObject
DataObject1: SubjectUnitType
DataObject2: Subject

http://cl.ly/2f372J2s3n2i

**Comment by tractorcow** [comment] 2017-05-15 09:59
Yes I think this has been fixed; applyRelation() has also since had considerable improvements and stabilisation. Closing unless confirmed to persist.

**Closed by tractorcow** 2017-05-15 09:59 UTC
Labels: change/patch
