### ISSUE TITLE
[GRIDFIELD] GridField needs a useful readonly view (currently just showing "none")

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3357] opened 2014-08-03 10:05 UTC
## Acceptance Criteria

 * I can click through GridField rows in readonly view (without action buttons)
 * I can perform standard GridField view operations (pagination, search, sorting)
 * I can click into a row of a readonly GridField to see it's edit view (which might also be readonly)
 * Edit views on rows in a readonly GridField are also marked readonly (regardless of `DataObject->canEdit()`) - this is important for history viewer
 * No state-altering actions are shown (create buttons, batch actions)

## Notes

 * Related: [Diff view for related records](https://github.com/silverstripe/silverstripe-versioned/issues/97)
 * If all records in the GridField aren't editable, it still shows an editable GridField
 * Components should be able to self determine if and how they're shown in readonly views
 * Track under ORB-175

## PR
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8535

## Historic Notes

I would like to lodge the following bug just in case it is one ...

Hi,

I have a very strange situation.  I dont know if it is stupidity (80% sure it is!!!) or something else - I am just posting this here, because it may be of interest to some of you and because I am not sure if it is a bug or something else.

This code works fine on one data object and not on another:

``` php
function getCMSFields(){
        ....
        $config = GridFieldConfig_RecordViewer::create();
        $dataList = Member::get();
        $gridField = new GridField('AA','AA'.$dataList->count(), $dataList, $config);
        $fields->addFieldToTab("Root.BB", $gridField);
        ....
}
```

On DataObject 1 it returns a normal gridfield - its title is AA7 (i.e. there are seven members), but on dataobject 2 it returns as field that says: 

AA7 (none)

This is unexpected. 

What I know:

it only is "funny" on one dataobject

it does not matter if I use Member or Page or MyOtherDataObject as datalist source, it always return as "none"

the other cms fields are not causing the error (I removed all the other fields and I ended up with the same results). 

also with an actual relation (this is what I am working with e.g. Players on Team), then it still returns as "none", despite their being record available.

I am using framework 3.1.5 and I have not experienced this problem before.  

It is an extensive application with plenty of code so some magic word or unexpected far-flung bug may cause the error.

in the getCMSFields, I dont use parent::getCMSFields, but even if I do, I get the same error. 
I did a search for the word "none" in /framework/forms/ and framework/templates/ without any meaningful results (only match was for the LookupField, but I cant imagine how a gridfield would become a lookup field) . I also searched for (none) throughout the ENTIRE application and got the same result: the lookup field. 

the html looks as follows:
![image](https://cloud.githubusercontent.com/assets/167154/3790278/b540e6dc-1af5-11e4-866c-154dbed8eedf.png)

67 members!!!

**Comment by irkeepin** [comment] 2015-04-06 15:33
I'm facing many of these same issues. 

It's been a few months since this thread was active - anyone make progress in the interim?

**Comment by tractorcow** [comment] 2015-04-06 20:50
This is the solution I used for the blog module.

https://github.com/silverstripe/silverstripe-blog/blob/master/code/extensions/BlogFilter.php#L84

The underlying assumption for this change is, just because the parent object is not editable, that doesn't mean the child objects are. In the above case, I wanted blog authors to be able to create new posts via a gridfield, without the ability to edit the actual parent.

In the case that a child object is not editable, gridfield will internally call performReadonlyTransformation on the edit form for that object.

**Comment by irkeepin** [comment] 2015-04-08 19:49
That solution worked perfectly for me, thanks. I simply had a read-only data object that included a has-many relationship. I wanted to display the has-many list as a GridField, but couldn't do that in the "view" mode of the CMS. But extending GridField as you suggest solved it.

**Comment by ntd** [comment] 2015-07-03 07:49
It took me a while to discover, but once you have the class with read-only transformation enabled (such as the @sunnysideup `GridFieldForReadonly` above) you can enable it by leveraging the [injector](http://docs.silverstripe.org/en/3.1/developer_guides/extending/injector/), e.g. by putting in your `_config.yml`:

    Injector:
        GridField:
            class: GridFieldForReadonly

After a flush, everything (`ModelAdmin` included) will pick up the new class instead of the old one.

**Comment by pschiffe** [comment] 2015-09-19 09:21
@ntd thanks for the tip, works like a charm.

BTW, any updates on this issue? No general solution yet?

**Comment by tractorcow** [comment] 2015-09-20 20:26
Not yet sorry, but this is still a real limitation of the gridfield API. Maybe worth pointing out to @assertchris who has been looking at ways to improve gridfield. :)

**Comment by dhensby** [comment] 2016-09-21 09:57
bump

**Comment by pitchandtone** [comment] 2017-03-16 07:42
bump

**Comment by sunnysideup** [comment] 2017-03-16 07:50
I am not in a good position to work on this right now, hope it gets fixed....

**Comment by chrispenny** [comment] 2018-01-22 00:40
Thank you for the workaround @sunnysideup. I was able to implement your solution in my SS4 project just as easily.

**Comment by robertclarkson** [comment] 2018-01-23 03:32
Good workaround @sunnysideup thanks for that

**Comment by tractorcow** [comment] 2018-02-06 22:18
Will see if we can implement this as a part of http://github.com/silverstripe/silverstripe-versioned/issues/93

**Comment by clarkepaul** [comment] 2018-03-12 00:52
Hi, we will create some visuals for this issue with the intention to get everyone on the same page with an approach. 

Question first, is there a case when a GridField might contain both readonly and editable items? 

At the moment I'm thinking to do a normal looking GridField with a preview type icon instead of an edit icon if items have a readonly state, and when the item is being viewed the fields are readonly without any actions available (possibly with the addition of a "read-only" notification).

**Comment by chrispenny** [comment] 2018-03-12 01:50
Hi @clarkepaul,

I think that allowing for a mixture of readonly and editable Objects within a single GridField would be absolutely fantastic.

I could see it being very useful if, say, you're using these modules:

- Elemental
- Advanced Workflow

And you were allowing Workflows at a Block level, and/or were allowing authors to set Embargo dates at a Block level.

Any time I'm using these modules, I always push for making the Objects readonly while they're in either of these states - otherwise things tend to get very messy (from the Authors pov).

**Comment by pitchandtone** [comment] 2018-03-12 06:29
Agree. Needs to be able to have both. Like sitetree some objects could be editable by me, but not all, however I still need to see them.

**Comment by newleeland** [comment] 2018-04-05 01:03
**Potential Designs**
![gridfield_read only_holder](https://user-images.githubusercontent.com/8085295/38342260-8139353a-38d1-11e8-8e38-30e2a1a8be0a.png)

![gridfield_read only_listing](https://user-images.githubusercontent.com/8085295/38342182-d66302da-38d0-11e8-99c0-5c5d11d63912.png)

**Comment by clarkepaul** [comment] 2018-04-15 23:31
@newleeland thanks for the mockups. 
We've taken a very lightweight approach to showing readonly items, we did consider icons/badges on each readonly item but decided that showing indicators on all items becomes visually crowded. History or the the Archive will be readonly for the whole section. If you don't have permissions to edit items in a GridField your likely not able to edit any of the items but in most cases people should be able to access the data. 

The one thing I think the design might be lacking is some information (like an notification) as to why the item is in a readonly state, but its perhaps only required for some cases like:
* the GridField is showing a mix of readonly and editable items
* the user doesn't have permissions (meaning others would be able to edit them)
* the item is in a workflow eg. advanced workflow
* this information is not stored on this database (but through an API)
* and probably a few more...

**Comment by clarkepaul** [comment] 2018-05-16 23:13
I'm suggesting that we go with the proposed design like @newleeland has presented, and when in development we can dig a bit deeper as to all of the reasons why items might be readonly and whether giving anymore detail is beneficial in different scenarios (like those specified in my previous comment).

**Comment by mlewis-everley** [comment] 2018-07-11 15:55
One thing I don't understand, doesn't GridField already support edit/view permissions? If I send a list of objects to GridField, it removes any that cannot be viewed.

If any items in the list cannot be edited, clicking them opens them as read only.

Shouldn't a GridField loaded onto a ReadOnly form, still behave in the same fashion?

For example (we have something similar on a current project), a `Page` might have many `notes`, a user can login, cannot edit the page, but can create notes and edit only notes they have created?

Possibly this is what you were meaning @clarkepaul?

PS: This issue is driving me nuts at the moment, so :+1: for doing something about it.

**Comment by clarkepaul** [comment] 2018-07-12 03:22
I was under the impression it still comes up with "none" by default in place of showing a grid field which is misleading for users, specially if there is nothing private about the information. So if the functionality actually exists to show the data in a readonly state then I think we should be doing that by default. Hopefully I haven't mis-understood the issue. cc @mlewis-everley

**Comment by sunnysideup** [comment] 2018-07-12 04:08
from memory, the gridfield looks at canEdit of the "parent" .... e.g. if you are editing Products where products have many Likes then if Products::canEdit returns false then the Likes in the CMS will be shown as (none).  That is wrong of course, but that is how it was last time I checked, a long time ago now.

**Comment by mlewis-everley** [comment] 2018-07-12 10:44
@clarkepaul Sorry, you are right, it still displays "none" when readonly. What I was meaning was shouldn't the gridfield behave the same way irrespective of if the parent object is readonly or not (I think this is what @sunnysideup is meaning)?

**Comment by clarkepaul** [comment] 2018-07-15 23:43
I'm not sure what should be the default, I would think there's an option for gridfields to have to inherit based on whether the parent is readonly, or be just editable unless specified. I think its best that devs make the recommendation on what approach we take based on actual needs.

Wouldn't an inherit model work well here?

**Comment by clarkepaul** [comment] 2018-07-16 00:04
Readonly gridfields should also consider the item previews...
Related https://github.com/silverstripe/silverstripe-versioned/issues/100

**Comment by purplespider** [comment] 2018-07-31 17:25
@caffeineinc Is right, the History tab currently fails to load for any page which includes a`GridField`. Just spent 2 hours trying to work out what was causing it. This needs to be fixed with a workaround ASAP, before implementing a proper read-only state.

**Comment by caffeineinc** [comment] 2018-08-29 02:43
So i've got a potential fix, provide GridField with a whitelist of readonly (overloadable) transformation components. That way GridField can handle it's own transformation, and if you've got custom implementations, you can add those. 

I'll just create a PR.

```GridField doesn't have a valid readonly state if it's value is set to an Object
without `forTemplate()`. The default behaviour is to render a ReadonlyField,
but given GridField is a complex type this isn't suitable.

This bugfix provides a transformation method to render only components that are
whitelisted to provide a readonly state.
```

Hopefully that doesn't affect semver.

**Comment by NightJar** [comment] 2018-08-29 21:48
GridField has a valid readonly state in that fields without a `performReadonlyTransformation` method are converted into empty `ReadonlyField` objects (which then render as an empty string).

I have never run into this issue (which in itself is very interesting), even when adapting [Elemental to have a read only transformation state](https://github.com/dnadesign/silverstripe-elemental/blob/3/src/Forms/ElementalAreaField.php#L73) - before this change pages would simply render read only titles, url segment, and metadata...  with a complete void of content (thus the necessity for the change as most versions appeared the same despite radically different content over time).

It appears that something is calling `setValue` _too late_ in the process of a history view, setting the value of a `ReadonlyField` to what should be the list for the GridField.



Regardless of the bugs above, a GridField should still have a valid read only state (per OP & PR) :>

**Comment by caffeineinc** [comment] 2018-09-03 22:13
So do you want me to add a Noop `setValue()` function to the PR, as something in the history controller is doing that, _or_ find what's setting the value somewhere deep in history controller. 

Every formfield should have a value, but `GridField` is kind of a composite field, and state is stored in `GridFieldState` (in `GridField->components`) rather than value, which alone moves away from the `FormField` interface. 

I think we should try and get an actionable plan, on how to move forward. This has been broken for too long, and right now, every 4.2 release has to be forked to resolve the issue, or risk going out broken.

**Comment by NightJar** [comment] 2018-09-05 22:05
I dunno bruddah, I'm not core team. Personally I'm fine with a noop, but @silverstripe/core-team may have some feelings about it :)

**Comment by robbieaverill** [comment] 2018-09-06 08:01
ping @silverstripe/core-team

**Comment by chillu** [comment] 2018-09-12 22:18
> So do you want me to add a Noop setValue() function to the PR, as something in the history controller is doing that, or find what's setting the value somewhere deep in history controller.

Ideally you can track down the root cause. In general, a `FormField->setValue()` method accepts different types, based on the view representation. `GridField` doesn't have it's own specific `setValue()` implementation (or a noop implementation), but rather uses the constructor or `setList()` to set it's "value". So it'll fall back to `FormField->setValue()`. As far as I can tell, neither `GridField` nor `GridState` are using `FormField->value` anywhere.

So there's two issues here:
1. GridField causes readonly views to fatal (`impact/critical`)
2. GridField doesn't have a good readonly view (`impact/high`?)

@caffeineinc I'm assuming your PR in https://github.com/silverstripe/silverstripe-framework/pull/8348 fixes both?

**Comment by chillu** [comment] 2018-10-28 19:43
@lukereative Could you assess if Simon's PR in https://github.com/silverstripe/silverstripe-framework/pull/8348 fixes what's been discussed here, and close this issue?

**Closed** 2018-10-31 22:13 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/UX, type/bug

**Comment by clarkepaul** [comment] 2019-03-11 01:02
What was the outcome here? e.g. what does the user see?

**Comment by NightJar** [comment] 2019-03-11 02:02
The [commit](https://github.com/caffeineinc/silverstripe-framework/commit/27570c65eb14537324121c6a7c4a9f6cb03f2211) reads that it removes all components from the config that allow editing.
This should mean it displays a normal gridfield, but with no ability to edit any entry.
