### ISSUE TITLE
Form Validation Docs use non-existent method

### ISSUE THREAD

**Issue by davejtoews** [silverstripe/silverstripe-framework#9429] opened 2020-03-12 17:47 UTC
One of your examples on the Form Validation doc page uses a method on `SilverStripe\Forms\Form` called `addErrorMessage`. 

https://docs.silverstripe.org/en/4/developer_guides/forms/validation/

No method called `addErrorMessage` seems to exist anywhere in your API/

https://api.silverstripe.org/4/search.html?search=addErrorMessage

**Comment by christopherdarling** [comment] 2020-06-26 11:23
dupe of https://github.com/silverstripe/silverstripe-framework/issues/8640 & https://github.com/silverstripe/silverstripe-framework/issues/9151

**Comment by christopherdarling** [comment] 2020-06-26 12:57
Looks like this can be closed... docs look to have been updated now https://docs.silverstripe.org/en/4/developer_guides/forms/validation/ / https://github.com/silverstripe/silverstripe-framework/blob/f1c74c357028235c1f4351a849773fa2a1851e89/docs/en/02_Developer_Guides/03_Forms/01_Validation.md

**Closed** 2020-06-26 14:40 UTC
Labels: affects/v4, change/patch, effort/easy, impact/low, type/docs
