### ISSUE TITLE
ModelAdmin Search form MultiSelect field types submit javascript [object Object]

### ISSUE THREAD

**Issue by christohill** [silverstripe/silverstripe-framework#11443] opened 2024-10-23 05:14 UTC
### Module version(s) affected

5.2.22

### Description

When adding a multi-select field type to a ModelAdmin search form through modifying the `SearchContext` in `GridFieldFilterHeader`, the multi-select field submits an string of comma separated javascript type objects ([object Object]).

I've tested this with `ListboxField` and `TagField` (silverstripe/tagfield) with similar results. Interestingly, `CheckboxSetField` which is also marked as ```php $schemaDataType = FormField::SCHEMA_DATA_TYPE_MULTISELECT``` submits a string of comma separated keys when an array is set as the source.

### How to reproduce

Basic example
```php
public function getGridField(): GridField {
    $grid = parent::getGridField();
    $filter = $grid->getConfig()->getComponentByType(GridFieldFilterHeader::class);
    $context = $filter->getSearchContext($grid);
    $fields = $context->getFields();
    $fields->add(ListboxField::create('Test', 'Test', ['one' => 'One', 'two' => 'Two']));

    return $grid;
}
```
Form Data Payload: `filter[members][Test]: [object Object],[object Object]`

Custom SearchContext Example
```php
// ModelAdmin
public function getGridFieldConfig(): GridFieldConfig {
    $config = parent::getGridFieldConfig();
    $filter = $config->getComponentByType(GridFieldFilterHeader::class);
    $filter->setSearchContext(MemberSearchContext::create(Member::class));

    return $config
}
```
```php
// MemberSearchContext
class MemberSearchContext extends SearchContext {

    public function getSearchFields() {
        $fields = parent::getSearchFields();
        $fields->add(ListboxField::create('Test', 'Test',  ['one' => 'One', 'two' => 'Two']));
        return $fields;
    }

    public function getQuery($data, $sort = false, $limit = false, $existingQuery = null) {
        $query = parent::getQuery($data, $sort, $limit, $existingQuery);
        // Dump form data
        echo "<pre>";
        var_dump($data);
        echo "</pre>";
        die();
        return $query;
    }
}
```

### Additional Context

![image](https://github.com/user-attachments/assets/c960a038-c998-44f6-93df-b8e0fb0aeb84)

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment] 2024-10-23 20:44
Closing as a duplicate of https://github.com/silverstripe/silverstripe-admin/issues/1746

**Closed by GuySartorelli** 2024-10-23 20:44 UTC
