### ISSUE TITLE
Insert Media via URL (YouTube): resulting iframe does not honor custom size

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#8251] opened 2018-07-09 01:38 UTC
## Affected Version

silverstripe/recipe-cms                1.1.0
silverstripe/recipe-plugin             1.3.0

## Description

Somewhat related to #8249

Width and height, as manually changed in the dialog, are not honored in the generated `iframe`.

## Steps to Reproduce

1. Add a YouTube video. It might default to 480 wide.
2. Change the width to e.g. 320.
3. Save and notice how the placeholder correctly shows `width: 320px` for the `div.embed` and `width="320"` for the `img.placeholder`. I repeat: it is saved correctly. 
4. View the result. The div still has `width: 320px`, but the img has been replaced with an iframe with the original `width="480"`. So I assume the issue is in the view.

**Comment by JorisDebonnet** [comment] 2018-07-09 02:09
I just retested this with recipe-cms 1.1.2, and this issue is still there. It's harder to reproduce now though because of that serious useability bug, #8249!

**Comment by maxime-rainville** [comment] 2018-07-13 04:40
I'm pretty sure this is a duplicate of #8249, so I'll close it.

**Comment by JorisDebonnet** [comment] 2018-07-13 09:48
I'm not convinced because #8249 is purely about the experience inside the CMS, while this bug is about how it comes out of the template engine. But it's definitely related, so as long as my description in this bug is double-checked when #8249 is solved, I'll be happy :)

**Comment by sparkcom** [comment] 2020-02-14 15:11
Yes I have got the same problem. I have to use some javascript + css to enforce it.

**Comment by Cheddam** [comment] 2020-02-16 22:25
I've replicated this issue in CMS 4.5.0, so I'm going to re-open it.

**Comment by ngaplastyk** [comment] 2020-04-23 06:27
This issue is still happening. I have created a media by the youtube link and tried to set it to 640 x 330. After saving the change, the iframe still has default dimensions width="480" height="270". One thing I noticed is the parent div thumbnail render style="width: 640px;" but there is no height property for this.

**Comment by emteknetnz** [comment] 2020-07-27 06:05
Fixed in https://github.com/silverstripe/silverstripe-framework/pull/9615

**Comment by emteknetnz** [comment] 2020-07-27 23:05
The fix for this has been merged, I'll close this issue now

**Closed by emteknetnz** 2020-07-27 23:05 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/UX, type/bug, type/frontend
