### ISSUE TITLE
SiteTree_Live doesn't exist

### ISSUE THREAD

**Issue by thany** [silverstripe/silverstripe-framework#4451] opened 2015-07-29 15:39 UTC
I copied over ALL files and the ENTIRE database from my development environment to our staging server. I checked and re-checked that the database settings for staging are correct, and they are. They really are. Also checked that the database is populated correctly, i.e. the import went well. And it did. Now I'm getting this error:

```
[User Error] Couldn't run query: SELECT DISTINCT "SiteTree_Live"."ClassName", "SiteTree_Live"."Created", "SiteTree_Live"."LastEdited", "SiteTree_Live"."URLSegment_nl_NL", "SiteTree_Live"."URLSegment_en_US", "SiteTree_Live"."Title_nl_NL", "SiteTree_Live"."Title_en_US", "SiteTree_Live"."MenuTitle_nl_NL", "SiteTree_Live"."MenuTitle_en_US", "SiteTree_Live"."Content_nl_NL", "SiteTree_Live"."Content_en_US", "SiteTree_Live"."MetaDescription_nl_NL", "SiteTree_Live"."MetaDescription_en_US", "SiteTree_Live"."ExtraMeta_nl_NL", "SiteTree_Live"."ExtraMeta_en_US", "SiteTree_Live"."ReportClass_nl_NL", "SiteTree_Live"."ReportClass_en_US", CASE WHEN ("SiteTree_Live"."URLSegment_en_US" IS NOT NULL AND "SiteTree_Live"."URLSegment_en_US" != '') THEN "SiteTree_Live"."URLSegment_en_US" ELSE "SiteTree_Live"."URLSegment" END AS "URLSegment", CASE WHEN ("SiteTree_Live"."Title_en_US" IS NOT NULL AND "SiteTree_Live"."Title_en_US" != '') THEN "SiteTree_Live"."Title_en_US" ELSE "SiteTree_Live"."Title" END AS "Title", CASE WHEN ("SiteTree_Live"."MenuTitle_en_US" IS NOT NULL AND "SiteTree_Live"."MenuTitle_en_US" != '') THEN "SiteTree_Live"."MenuTitle_en_US" ELSE "SiteTree_Live"."MenuTitle" END AS "MenuTitle", CASE WHEN ("SiteTree_Live"."Content_en_US" IS NOT NULL AND "SiteTree_Live"."Content_en_US" != '') THEN "SiteTree_Live"."Content_en_US" ELSE "SiteTree_Live"."Content" END AS "Content", CASE WHEN ("SiteTree_Live"."MetaDescription_en_US" IS NOT NULL AND "SiteTree_Live"."MetaDescription_en_US" != '') THEN "SiteTree_Live"."MetaDescription_en_US" ELSE "SiteTree_Live"."MetaDescription" END AS "MetaDescription", CASE WHEN ("SiteTree_Live"."ExtraMeta_en_US" IS NOT NULL AND "SiteTree_Live"."ExtraMeta_en_US" != '') THEN "SiteTree_Live"."ExtraMeta_en_US" ELSE "SiteTree_Live"."ExtraMeta" END AS "ExtraMeta", "SiteTree_Live"."ShowInMenus", "SiteTree_Live"."ShowInSearch", "SiteTree_Live"."Sort", "SiteTree_Live"."HasBrokenFile", "SiteTree_Live"."HasBrokenLink", CASE WHEN ("SiteTree_Live"."ReportClass_en_US" IS NOT NULL AND "SiteTree_Live"."ReportClass_en_US" != '') THEN "SiteTree_Live"."ReportClass_en_US" ELSE "SiteTree_Live"."ReportClass" END AS "ReportClass", "SiteTree_Live"."CanViewType", "SiteTree_Live"."CanEditType", "SiteTree_Live"."Version", "SiteTree_Live"."ParentID", "SiteTree_Live"."ID", CASE WHEN "SiteTree_Live"."ClassName" IS NOT NULL THEN "SiteTree_Live"."ClassName" ELSE 'SiteTree' END AS "RecordClassName" FROM "SiteTree_Live" WHERE ( ("SiteTree_Live"."URLSegment_en_US" IS NOT NULL AND "SiteTree_Live"."URLSegment_en_US" != '' AND ("SiteTree_Live"."URLSegment_en_US" = 'home' AND "SiteTree_Live"."ParentID" = 0)) OR ( ("SiteTree_Live"."URLSegment_en_US" IS NULL OR "SiteTree_Live"."URLSegment_en_US" = '') AND ("SiteTree_Live"."URLSegment" = 'home' AND "SiteTree_Live"."ParentID" = 0) )) ORDER BY "SiteTree_Live"."Sort" ASC LIMIT 1 Table 'smithsveglia.SiteTree_Live' doesn't exist
```
The important bit:
```
Table 'smithsveglia.SiteTree_Live' doesn't exist
```

Well, sorry, but it does exist. Not much I can make of it. It really honestly genuinely absolutely truly exists.

So what's the real problem here?

(I have to post this here, since the forum is broken)

**Comment by thany** [comment] 2015-07-29 15:53
Yup, there it is:

![capture](https://cloud.githubusercontent.com/assets/152227/8962399/adbfafc4-361a-11e5-8486-8adac4868fd1.PNG)

That's taken from the MySQL workbench tool.

**Comment by kinglozzer** [comment] 2015-07-29 16:05
@thany If I remember correctly, table names are case sensitive on everything except Windows. Have you moved from a local Windows environment to a live Unix one?

**Comment by thany** [comment] 2015-07-29 16:22
Yes I did. But then why were the tables created all-lowercase in the first place (i.e. on first install) ?
That then, is the problem that should probably be fixed.

**Comment by kinglozzer** [comment] 2015-07-29 16:34
I believe we do already try to correct this already on `dev/build`. I’d suggest investigating [this code](https://github.com/silverstripe/silverstripe-framework/blob/912b133ba1ce5f381d2a6cef021a2ad3021db956/model/MySQLDatabase.php#L342) and see what’s going on/not happening.

**Comment by thany** [comment] 2015-07-29 16:41
I get that, but how come on my development box the tables have become lowercase in the first place?
Yes, a `/dev/build` will correct the table names, but on my development box, it will not.

The problem is, on installing silverstripe for the first time, apparently the tables were created all-lowercase. They must've been. I didn't make them that way, something along the way made the tables all-lowercase, which should be corrected. Next, a `/dev/build` should correct it as well on Windows, if only to prevent unneccesary errors like the one above.

**Comment by stevie-mayhew** [comment] 2015-07-29 20:23
@thany the lower case table names is a MySQL setting on Windows, not something which is created from SilverStripe - its a system wide setting which you will need to change on your development environment.

You might find this (StackOverflow answer)[http://stackoverflow.com/questions/8550789/where-to-change-the-value-of-lower-case-table-names-2-on-windows-xampp] useful about how to change this setting.

**Comment by sminnee** [comment] 2015-07-29 21:51
The /dev/build fix is the best we can do to support people who haven't changed those settings; hopefully the StackOverflow link that Stevie posted will be of help to @thany. However, I don't think there's an open defect in SilverStripe itself so I'm closing this issue.

**Closed by sminnee** 2015-07-29 21:51 UTC

**Comment by thany** [comment] 2015-07-29 21:56
This issue could've been prevent had silverstripe not used any capitals in table names anywhere at all. In otherwords, having everything always lowercase. This is a common solution to prevents casing problems.

That's my suggestion. If nothing else, then please at least consider that.

**Comment by sminnee** [comment] 2015-07-29 22:06
Yeah, table name & fieldname flexibility is something that we're considering, and if we have that, we could potentially switch to lowercase table names as either an option, or the default. We'd obviously need to think about the upgrade path for existing databases but that's not insurmountable.

**Comment by tractorcow** [comment] 2015-07-29 22:26
All lowercase table names would solve a large number of problems; Especially with PHP supporting case-insensitive classname resolution, a lot of work is otherwise necessary to map class strings to tables. strtolower() not only solves that problem, but makes the issue of db case sensitivity settings (between OS) a non-issue too.

Should we just do this in 4.0?

**Comment by stevie-mayhew** [comment] 2015-07-29 22:53
:+1: It seems like a sensible thing to do and isn't that much work for quite a bit of gain.

Anyone who has ever gone through and manually renamed all their tables would loved this change (why is 'L' in 'Live' capitalized but 'v' in 'versioned' isn't :stuck_out_tongue:)

**Comment by thany** [comment] 2015-07-30 10:44
> We'd obviously need to think about the upgrade path for existing databases but that's not insurmountable.

Not only insurmountable, but already fixed, albeit in reverse. Lowercased table names are being CamelCased, so it's a simple matter of reversing the check and reversing the build step.

**Comment by cansozeri** [comment] 2017-11-29 21:13
The problem is still exists with ss4. I have copied my database to a linux server and I get same errors because of table names :=) Dev/build fix that except one table, I had to change it manually :=)

**Comment by tractorcow** [comment] 2017-11-29 21:55
In 4.0 we have a new config.

`SilverStripe\ORM\Connect\DBSchemaManager.fix_table_case_on_build`.

This should fix `sitetree_live` to `SiteTree_Live` on case sensitive filesystems. If it is not, there is a real bug.

**Comment by tractorcow** [comment] 2017-11-29 21:58
Raised this issue at https://github.com/silverstripe/silverstripe-framework/issues/7660 @cansozeri with the new information. Thanks for the report.
