### ISSUE TITLE
Error displayed when we use addExtraClass on a DropdownField

### ISSUE THREAD

**Issue by warslett** [silverstripe/silverstripe-framework#8582] opened 2018-11-07 15:55 UTC
## Affected Version

Observed in 4.2.1

## Description

Silverstripe throws out a big ugly warning when we use addExtraClass on a DropdownField
"nl2br() expects parameter 1 to be string, array given Line 113 in /var/www/html/vendor/silverstripe/framework/src/ORM/FieldType/DBString.php"

We have a form in an Elemental element with a custom controller. We use addExtraClass on most of our other form fields and it works fine. When I add it to DropdownField in the same way it gives me the above error. I've worked out that if I dive into DBString and dump the value it's trying to pass to nl2br it is passing an array where the key and value is my extra class. When I remove the addExtraClass method call the error goes away.

## Steps to Reproduce

The code I'm using at the moment which is triggering the error is:

```
DropdownField::create('HowDidYouHearAboutUs', 'How did you hear about us?', [
    'word of mouth' => 'word of mouth'
])->addExtraClass('form-group-half'),
```

**Comment by robbieaverill** [comment] 2018-11-07 16:48
Would you be able to get a backtrace to share with us? Extra classes are stored as an array, but they're imploded to a string via `FormField::extraClass()` which is used in attributes for templates etc

**Comment by chillu** [comment] 2018-12-11 03:06
Closing, since no feedback was provided for a month. I couldn't reproduce this when calling this method on all core field types in the `4` branch with the frameworktest module, see https://github.com/silverstripe/silverstripe-frameworktest/pull/57

**Closed by chillu** 2018-12-11 03:06 UTC
Labels: feedback-required/author
