### ISSUE TITLE
Controller is redirecting to LoginForm

### ISSUE THREAD

**Issue by ARNHOE** [silverstripe/silverstripe-framework#3131] opened 2014-05-13 08:38 UTC
Using the latest branch since a second from now. Error is occuring since the last (two) week(s)?

This is happening only when I am logged as a super admin. Once I am not logged in as a admin, it seems to work fine.

Basically the following function is being called:
**From class ContentController extends Controller**
```
if(!$this->dataRecord->canViewStage(Versioned::current_archived_date() ? 'Stage' : Versioned::current_stage())) {
				$link = $this->Link();
				$message = _t(
					"ContentController.DRAFT_SITE_ACCESS_RESTRICTION", 
					'You must log in with your CMS password in order to view the draft or archived content. ' .
					'<a href="%s">Click here to go back to the published site.</a>'
				);
				Session::clear('currentStage');
				Session::clear('archiveDate');
				
				$permissionMessage = sprintf(
					_t(
						"ContentController.DRAFT_SITE_ACCESS_RESTRICTION",
						'You must log in with your CMS password in order to view the draft or archived content. '.
						'<a href="%s">Click here to go back to the published site.</a>'
					),
					Controller::join_links($this->Link(), "?stage=Live")
				);

				return Security::permissionFailure($this, $permissionMessage);
			}
```

My url_handler in class AutoLeasenPage_Controller extends Page_Controller {

```
public function findCar($request) {
		$urlsegment = $request->param('CarURLSegment');
		$cartypeurlsegment = $request->param('CarTypeURLSegment');

		$car = CarItem::get()->filter(array('URLSegmentCarType' => $cartypeurlsegment, 'URLSegment' => $urlsegment))->First();
		// if($car) {$this->car = $car->ID;}

		if (!$car) {
			$this->httpError(404);
		}

		return new CarController($this, $car);
	}
```

CarController:

```
class CarController extends Page_Controller {

	private static $allowed_actions = array(
		'index'
	);

	protected $parent;
	protected $car;

	public function __construct(Controller $parent, Car $car) {
		$this->parent = $parent;
		$this->car = $car;

		parent::__construct();
	}
```

**Comment by daOutlawz** [comment] 2015-03-13 02:03
Hi Guys,

Any updates on this? Am facing the same issue.

**Comment by tractorcow** [comment] 2015-03-15 19:58
If `SiteTree::canViewStage` is returning false can you debug the method to see what part of it is failing? It could either be the record isn't available in that stage or some logic in canView is causing it to return false.

**Comment by daOutlawz** [comment] 2015-03-16 01:27
I'm finding it difficult replicating the issue now.  It seemed as though the date it was published had an effect to the issue.  Leaving the page published for more then a day seemed to have solved it.  Removing and re-adding the page brought the issue back.  But now, every time I re-add the page, it works fine.
The version the <code>ContentController::init</code> method was checking for was always 'Stage', but now it's always 'Live'.

**Comment by silverstripe-elliot** [comment] 2015-03-18 22:49
I'm trying to use Versioned on a non-SiteTree DataObject and generating preview links for it. I've encountered this issue on two custom controllers extending from Page_Controller or ContentController. The problem goes away if I extend Controller directly.

I've reproduce it on a barebones controller without any calls to Versioned present, yet something in that hierarchy behaves differently if the "stage" variable is present. Here's some code:

```php
class SomeVersioned_Controller extends ContentController {
	static $allowed_actions = array(
		'xxxx'
	);

	public function xxxx() {
		debug::dump($this->request->requestVars());
	}
}
```

Worth mentioning, I can't reproduce this on a barebones CWP site running 3.1.10. The issue remains on 3.1.x-dev

**Comment by daOutlawz** [comment] 2015-03-18 22:53
@silverstripe-elliot - that's exactly the scenario we have as well.  It only happens on a custom controller with POSTed data.

**Comment by silverstripe-elliot** [comment] 2015-03-18 22:56
@daOutlawz in my case, going directly to the URL triggers it: http://path.to.mysite/SomeVersioned_Controller/xxxx

**Comment by nathanbrauer** [comment] 2015-04-08 21:38
We're experiencing this at Marketo as well (while in Stage mode).

http://www.marketo.com/iframe/related_resource_by_ids/?ids=316&align=left&autoresize=resource-frame-116

Is there any solution or workaround for now? This is preventing us from launching our international programs.

cc: @tylerkidd

**Comment by daOutlawz** [comment] 2015-04-08 21:59
@nathanbrauer a workaround would be to overload the <code>ContentController::init</code> method on that particular page's controller so it either doesn't show the message, or some other more complicated workaround.

**Comment by chillu** [comment] 2015-04-27 06:33
I was able to reproduce this by 

You're slightly misusing `ContentController` by not passing through a `$dataRecord`, but I can understand why you need to access the template helpers in the parent implementation. We're doing the same thing in `Security`, and the numerous `if($this->dataRecord)` checks in `ContentController` indicate that this should be a supported (albeit messy) mode of operation.

See pull request: https://github.com/silverstripe/silverstripe-cms/pull/1194

**Comment by davestlyon** [comment] 2015-12-21 18:50
In case it helps, I was able to get around this in a project with custom controllers by using

Versioned::set_reading_mode('Live');

Not saying that's the right thing to do, but worked for us in the particular case we were trying to solve. In this case the controllers in question were serving up code from a completely separate legacy system, so working with the CMS publishing was unnecessary.

**Comment by tractorcow** [comment] 2015-12-21 21:12
ContentController has had this logic removed in 3.3.0, and put elsewhere. :)

https://github.com/silverstripe/silverstripe-cms/commit/5353ac5315703240540c9cde0f5c8eeb5571bc19

Since the problem was in the removed code, I'm going to close this issue. If anyone sees this issue come up again in 3.3.0 then please feel free to re-open, or create a new ticket.

**Closed by tractorcow** 2015-12-21 21:12 UTC
Labels: change/patch, feedback-required/author

**Comment by robpetreski** [comment] 2015-12-21 21:15
Just as a point of reference, you could also extend Controller, not ContentController if you're still on an older release.
