### ISSUE TITLE
Fatal error with example yml-log config from docs

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-framework#9075] opened 2019-06-17 15:00 UTC
## Affected Version
recipe-cms: ^4.4.1

## Description
The yml-config under "Setting a different configuration for dev" in docs causes a fatal error with SS 4.4.1 but not with 4.3.x. If the context `.errorhandler` is removed the error doesn't occure.

https://docs.silverstripe.org/en/4/developer_guides/debugging/error_handling/#setting-a-different-configuration-for-dev

```
Fatal error: Uncaught InvalidArgumentException: 'calls' entries in service definition should be 1 or 2 element arrays. in /vendor/silverstripe/framework/src/Core/Injector/Injector.php on line 665

( ! ) InvalidArgumentException: 'calls' entries in service definition should be 1 or 2 element arrays. in /vendor/silverstripe/framework/src/Core/Injector/Injector.php on line 665
```

## Steps to Reproduce
Set config as linked above & flush

**Comment by robbieaverill** [comment] 2019-06-17 20:51
Can you share the config file you’re using please? I realise you said it’s from the docs, but just to be sure

**Comment by lerni** [comment] 2019-06-17 23:28
I've just tested it with an fresh install and log.yml in /app/_config/` with the same result
```
Fatal error: Uncaught InvalidArgumentException: 'calls' entries in service definition should be 1 or 2 element arrays. in /ss-logtest/vendor/silverstripe/framework/src/Core/Injector/Injector.php:665 Stack trace: #0 /ss-logtest/vendor/silverstripe/framework/src/Core/Injector/Injector.php(620): SilverStripe\Core\Injector\Injector->inject(Object(Monolog\Logger), 'Psr\\Log\\LoggerI...') #1 /ss-logtest/vendor/silverstripe/framework/src/Core/Injector/Injector.php(1002): SilverStripe\Core\Injector\Injector->instantiate(Array, 'Psr\\Log\\LoggerI...', 'singleton') #2 /ss-logtest/vendor/silverstripe/framework/src/Core/Injector/Injector.php(955): SilverStripe\Core\Injector\Injector->getNamedService('Psr\\Log\\LoggerI...', true, Array) #3 /ss-logtest/vendor/silverstripe/framework/src/Core/Injector/Injector.php(523): SilverStripe\Core\Injector\Injector->get('Psr\\Log\\LoggerI...') #4 /ss-logte in /ss-logtest/vendor/silverstripe/framework/src/Core/Injector/Injector.php on line 665
```
[
[log.yml](https://github.com/silverstripe/silverstripe-framework/files/3299182/log.txt)

](url)

**Comment by robbieaverill** [comment] 2019-06-17 23:30
Reproduced, thanks

**Comment by robbieaverill** [comment] 2019-06-17 23:40
Ok the issue is in the way the configuration is merged with arrays, you end up having two copies of `pushDisplayErrorHandler` (this is just an alias for reference) which have a merged list of arguments from both this example configuration and from the logging.yml in core.

You can workaround this by changing `pushDisplayErrorHandler` to `pushMyDisplayErrorHandler` so it doesn't have a naming conflict with core.

Would you like to make a PR to update the docs if this fixes your issue?

**Comment by lerni** [comment] 2019-06-18 07:34
Thank you for testing and suggested workaround! :100: The fatal error felt unexpected in terms of developer experience. If this is a different issue or not I leave up to you.

**Closed** 2019-06-19 08:17 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug, type/docs
