### ISSUE TITLE
Wrong propagation of grid state in nested GridFields

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#9095] opened 2019-06-27 07:55 UTC
## Affected Version

4.4.1

## Description

There is an issue when sorting and then navigating over nested GridFields. It seems as if the inner GridField will load the state of the parent's GridField which may contain invalid state data (e.g. Sort by a field not existing on the child). This will become a problem in GridFieldDetailForm_ItemRequest->getAdjacentRecordID.

## Steps to Reproduce

* Have two classes FooEntity and BarEntity where FooEntity has a many_many relation to BarEntity. FooEntity shall have some field FooField that does not exist on BarEntity.
* Create a ModelAdmin for FooEntity and ensure that there is a GridField for the BarEntities inside the FooEntity EditForm.
* Make FooField a summary field
* Ensure that there are at least one object per class and a relation between them
* Open the ModelAdmin for FooEntity and sort by FooField
* Click on a FooEntity
* Navigate to the GridField for the BarEntities and select one
* See the mentioned error (note the sort field "FooField" in the grid state url)

**Comment by sb-relaxt-at** [comment] 2019-06-27 07:58
And here a minimal test case:

* https://gist.github.com/sb-relaxt-at/8da1f35f790a25ce4a46993867e947ab
* https://gist.github.com/sb-relaxt-at/6e00c0277e86aca7dfcc41df082216cb
* https://gist.github.com/sb-relaxt-at/897659e17962d0885d87b09f0307b9d7

**Comment by maxime-rainville** [comment] 2019-07-11 22:41
I think this is a duplicate of https://github.com/silverstripe/silverstripe-admin/issues/887.

https://github.com/silverstripe/silverstripe-framework/pull/9072 should fix this.

I'll close this for now. If you look at the other issue and think it doesn't accurately describe your problem, I can reopen.

**Closed by maxime-rainville** 2019-07-11 22:41 UTC

**Comment by sb-relaxt-at** [comment] 2019-07-18 10:35
@maxime-rainville Thanks a lot, I must have overseen this issue, as the actual problem is inside framework and not admin. Looking forward for the bug to be fixed :-)

**Comment by lekoala** [comment] 2019-08-26 12:45
Hi,

I was just it by the same issue. I'm running on a project using v 4.4.3 and it does not seem fix. I'll also post on #9072 because I'm not sure why it's doing that.
