### ISSUE TITLE
“Edit Campaign” view sometimes fails to load

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#5517] opened 2016-05-11 08:46 UTC
Steps to recreate this (Chrome, OS X) are:

- Perform a hard-refresh on `admin/pages`
- Create new campaign
- Click back
- Click to edit the campaign you just created

Refreshing the page (or refreshing anywhere in CampaignAdmin) fixes it

![qwhjwcwm4o](https://cloud.githubusercontent.com/assets/1655548/15175214/2badb7ae-175d-11e6-9694-214a1214dfab.gif)

**Comment by sminnee** [comment] 2016-09-09 01:49
This is probably a duplicate of #5727, so closing.

**Closed** 2016-09-09 08:29 UTC
Labels: affects/v4, type/bug
