### ISSUE TITLE
[2012-04-21] GridFieldAddExistingAutocompleter incorrectly handling searchfields with relations

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1461] opened 2013-04-03 20:11 UTC
created by: @NicoHaase (NicoHaase)
created at: 2012-04-21
original ticket: http://open.silverstripe.org/ticket/7194

---

If the GridFieldAddExistingAutocompleter is set to search in relation fields (eg. through has_one), it incorrectly builds its search query as the JOINs are not added. You can find a patch attached to this ticket that will fix this easily.

**Comment by tractorcow** [comment] 2017-05-15 10:17
Can't easily tell if this is fixed from the code. GridFieldAddExistingAutocompleterTest shows relation fields as scaffoldable, but doesn't show they affect search properly.

**Comment by chillu** [comment] 2017-05-16 10:31
Patch is no longer available due to migration, no feedback from Nico in years, and no easy way to reproduce. Closing.

**Closed by chillu** 2017-05-16 10:31 UTC
Labels: affects/v3, affects/v4, change/patch, effort/easy, impact/low, type/bug
