### ISSUE TITLE
Update `many_many` through relations to support polymorphic "to"

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11004] opened 2023-10-18 01:00 UTC
## Description

Currently for `many_many` through relations, the "from" can be polymorphic, but the "to" cannot. We should support polymorphism on both ends, if possible.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/ORM/DataObjectSchema.php#L1156

**Comment by GuySartorelli** [comment] 2024-05-10 03:12
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/9148

**Closed as not planned by GuySartorelli** 2024-05-10 03:12 UTC
Labels: type/enhancement, affects/v5
