### ISSUE TITLE
SS try to locate I18nRailsYamlAdapter.php in a wrong location

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#3927] opened 2015-02-23 16:05 UTC
And in case of open_basedir restriction it results in the following error:

[23-Feb-2015 16:53:46 Europe/Rome] PHP Warning:  is_readable(): open_basedir restriction in effect. File(/usr/share/php//Zend/Translate/Adapter/I18nRailsYamlAdapter.php) is not within the allowed path(s): (/home/xxx/:/usr/share/php/:/usr/share/php5/:/tmp/:/usr/share/postfixadmin/:/etc/postfixadmin/:/usr/share/phpmyadmin/) in /home/xxx/www/xxx/framework/thirdparty/Zend/Loader.php on line 198

**Comment by kinglozzer** [comment] 2016-03-26 18:43
Duplicate of #3483

**Closed by kinglozzer** 2016-03-26 18:43 UTC
