### ISSUE TITLE
Proposal: Add a logging method to BuildTask

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#9382] opened 2020-01-22 22:50 UTC
## Affected Version

All.

## Description

Almost _every_ `BuildTask` I see and every one I write, there is a need to output some information to the screen in a PHP SAPI specific way. This inevitably means that a developer writes a method similar to the following.
```
    /**
     *
     * @param string $message
     * @param int $numLines
     */
    public static function out(string $message, int $numLines = 1)
    {
        $newLine = Director::is_cli() ? PHP_EOL : '<br/>';

        echo $message . str_repeat($newLine, $numLines);
    }
```
There is of course `DB::alteration_message()` but this is pretty crude, uses repeated message "type" definitions for each SAPI and makes no account of platform ("\n" is hard-coded rather than using an O/S independent marker such as is provided by `PHP_EOL`) nor does it provide the ability to use a custom `LoggerInterface` implementation to e.g. colourise the screen o.p. (See `LoggerInterface()` in `silverstripe/assets` `FileMigrationHelper` for yet another way to achieve this).

This proposal therefore seeks the implementation of a flexible method on `BuildTask` for logging to the _screen_ (But makes no objection if something even more flexible such as logging to a remote F/S is do-able, providing it is no more complicated than restricting the work to o/p only to the screen).

## Steps to Reproduce

Write a `BuildTask` and try really hard _not_ to need to write a method as described above.

**Comment by robbieaverill** [comment] 2020-01-23 02:22
Thanks for raising this, closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/9183

**Closed by robbieaverill** 2020-01-23 02:22 UTC
