### ISSUE TITLE
Persist GridField state between requests

### ISSUE THREAD

**Issue by MarcusDalgren** [silverstripe/silverstripe-framework#3229] opened 2014-06-23 10:46 UTC
As far as I can see right now everything for the GridField is handled via POST requests which means that whatever you've done with the GridField (paginated, sorted, searched etc) is lost if the page is reloaded.

A pretty common usecase where this becomes really annoying is when you have to do some kind of repetetive task with a number of records. Right now you search/filter/paginate for them, click one, edit & save. When that's done and you press back the GridField is reset and you have to do the search/filter/paginate thing all over again.

If this is accepted as an issue I'd be willing to tackle it with the caveat that I've no idea how to do this properly in the current context. Can we switch to get variables for search/filter/paginate? Should we store it in session (feels bad)?

**Comment by g4b0** [comment] 2015-07-24 12:44
Any news? It's a quite annoying issue when managing big GridField.

**Comment by purplespider** [comment] 2015-07-31 12:04
I've just posted a $50 bounty for this: https://www.bountysource.com/issues/2778676-persist-gridfield-state-between-requests

I've recently launched a site that has a booking system on it, a ModelAdmin displays 1 record per date for the next 2 years, allowing the admin to change the availability status for each date. With over 700 records, it's very annoying that when clicking Save & Close or Back from an EditForm, that it drops you back at the top of page 1 of the GridField.

Can I just add, that as well as remembering which page you were on, it should also remember the position on that page, or at least scroll down the page to the position of the record that was just edited. For some things I find it's better to scroll down a long page of records than have to paginate through multiple pages.

**Comment by gavro** [comment] 2016-04-04 15:48
Tried getting some useful statelogic in gridviews with a JS only approach. See: 
- https://github.com/silverstripe/silverstripe-framework/pull/3542#issuecomment-205359003
- https://github.com/novatio/silverstripe-statefulgridfield

Perhaps this approach might work for you?

**Comment by tractorcow** [comment] 2016-04-05 21:08
> Alternatively, GridState could be packed into a JSON blob and saved as a single get variable. That would minimise namespace pollution, but might hit URL-length issues. For smaller quantities of GridState, it might be okay.

The problem is that gridstate can be massive, with multiple potential keys per row.
We'd need to segment gridstate into state which can persist via querystring and which via session. It's too large for the querystring to hold.

You would also need to solve the problem of having these querystring args on the top level page, not simply on gridfield postback handlers, as is current.

**Comment by 3Dgoo** [comment] 2016-06-09 02:26
I have a client who noticed this problem. In the end I added the following JavaScript to the CMS to add the query string to the form action:

    (function($) {
        $.entwine('ss', function($) {
            $('.ss-gridfield').entwine({
                onmatch: function() {
                    var queryString = window.location.search;
                    if (queryString) {
                        $('#Form_ItemEditForm').each(function() {
                            var action = $(this).attr('action');
                            if (action) {
                                if (action.indexOf('?') < 0) {
                                    $(this).attr('action', action + queryString);
                                }
                            }
                        });
                    }
                }
            });
        });
    })(jQuery);

 For me this fixes it that when save is pressed the back, previous and next buttons all still contain the previous filter.

Hopefully this is useful.

**Comment by chillu** [comment] 2017-06-15 22:27
Note that the "current page" state of GridFields in `SiteTree->getCMSFields()` has been fixed in 3.6 through https://github.com/silverstripe/silverstripe-cms/commit/487235f9918b762f9eadcaaa655602da884807a6

**Comment by chillu** [comment] 2017-06-15 22:46
@steve-silverstripe has created another fix for this with https://github.com/littlegiant/silverstripe-persistentgridfield as well.

**Comment by sabina-talipova** [comment] 2022-07-29 00:18
Solved by https://github.com/silverstripe/silverstripe-admin/issues/1314

**Closed by sabina-talipova** 2022-07-29 00:18 UTC
Labels: type/enhancement
