### ISSUE TITLE
HtmlEditorConfig TinyMCE content_css option not respected

### ISSUE THREAD

**Issue by jaydenseric** [silverstripe/silverstripe-framework#5965] opened 2016-09-08 04:12 UTC
The documentation for customizing `HTMLEditorField` content styles is either out of date or there is a bug in the framework, because I can not get it to work no matter what I try.

Docs:
- [Rich-text editing (WYSIWYG)](https://docs.silverstripe.org/en/4.0/developer_guides/forms/field_types/htmleditorfield/)
- [WYSIWYG Styles](https://docs.silverstripe.org/en/4.0/developer_guides/customising_the_admin_interface/typography/)

This used to work back in early 3.0 versions.

**Comment by kinglozzer** [comment] 2016-09-08 08:13
It works for me in 3.x, I’ve used it to load webfonts like this:

```php
/* mysite/_config.php */

$theme = $config->get('SSViewer', 'theme');
$cssFiles = [
	FRAMEWORK_ADMIN_DIR . '/css/editor.css',
	THEMES_DIR . "/{$theme}/css/editor.css",
	'https://fonts.googleapis.com/css?family=Titillium+Web:600'
];

HtmlEditorConfig::get('cms')->setOption('content_css', implode(',', $cssFiles));
```

**Comment by dhensby** [comment] 2016-09-08 11:24
I'm closing this as @kinglozzer says it works for him. @jaydenseric please let us know if you don't have any luck?

**Comment by lerni** [comment] 2016-09-08 13:01
@jaydenseric I also can confirm it works but for some reason I experienced odd caching-issues with this in the past - reload harder! :)

**Comment by jaydenseric** [comment] 2016-09-09 07:23
Has anyone else tried in in the current v4 Alpha 1 or dev-master though?

Simplifying `mysite/_config.php`, this results in a changed block formats menu, but the styles are never downloaded or take effect:

```php
use SilverStripe\Forms\HTMLEditor\HTMLEditorConfig;

global $project;
$project = 'mysite';

require_once('conf/ConfigureFromEnv.php');

HtmlEditorConfig::get('cms')
  ->setOption('content_css', project() . '/editor.css')
  ->setOption('body_class', 'semantic-wysiwyg')
  ->setOption('block_formats', 'Heading 1=h1;Heading 2=h2;Heading 3=h3;Paragraph=p;Blockquote=blockquote');
```

**Comment by kinglozzer** [comment] 2016-09-09 08:41
Ah, sorry - I didn’t realise you were using 4.0-alpha1. It does look like support for this has been accidentally removed: anything you pass for this option [will be overridden](https://github.com/silverstripe/silverstripe-framework/blob/8dd644d25d4e01b6853922164440f8ac9c824f22/Forms/HTMLEditor/TinyMCEConfig.php#L407). It appears that `content_css` should really be set as an array too, perhaps we should adjust that code to something like:

```php
// https://www.tinymce.com/docs/configure/content-appearance/#content_css
$editorCSS = $this->getEditorCSS();
if (isset($settings['content_css'])) {
    $settings['content_css'] = (array)$settings['content_css'] + $editorCSS;
} else {
    $settings['content_css'] = $editorCSS;
}
```

**Comment by bummzack** [comment] 2017-02-09 15:41
Something to add to this issue:
`TinyMCEConfig::getEditorCSS` will **not** pick up any `editor.css` files from user themes or the user project directory, since `SSViewer::get_themes()` won't return any "frontend" themes when in the CMS.

I guess the desired behavior would be, that `content_css` does not have to be set manually, but that `getEditorCSS` would pick up the `editor.css` file from the first theme folder that contains said file?

Not sure if this should be reported as a separate issue, or if it belongs to this one.

**Comment by andrewandante** [comment] 2017-04-26 15:39
Think this https://github.com/silverstripe/silverstripe-framework/issues/6767 is a duplicate of this issue - should probably be merged in?

**Comment by kinglozzer** [comment] 2017-07-12 08:56
Closing in favour of https://github.com/silverstripe/silverstripe-framework/issues/7161, as that issue is more up-to-date

**Closed by kinglozzer** 2017-07-12 08:56 UTC
Labels: affects/v4, type/bug
