### ISSUE TITLE
Invalid italian YAML file in framework

### ISSUE THREAD

**Issue by digitall-it** [silverstripe/silverstripe-framework#6185] opened 2016-10-16 04:07 UTC
Installation of Silverstripe 3.4.1 actually fails. The culprit is the italian yaml language at this position

`framework/lang/it.yml`

 that needs to be sanitized from transifex, like in https://github.com/silverstripe/silverstripe-framework/issues/4247 using tool in https://github.com/tractorcow/cow/issues/2

After sanitization, the installation completes successfully.

I think that a non-destructive import sanitization procedure for all languages is in order.

Attached is the clean file `it.yml` which has 705L, 31039C.
The older, unsanitized `it.bak` has 716L, 31028C  so some data has been discarded.

Follows the installation steps on Ubuntu running over OSX follows, for repeatability. 
## 

after installing virtualbox, then vagrant, I issue these commands

```
mkdir ~/vagrant
git clone https://github.com/scotch-io/scotch-box.git ~/vagrant/silverstripe-box
cd ~/vagrant/silverstripe-box/public
mv index.php ../scotchbox.php
vagrant up
vagrant ssh
```

in the ubuntu environment

```
sudo apt-get update
sudo apt-get install language-pack-it
sudo apt-get install php5-tidy
echo 'date.timezone = "Europe/Rome"'|sudo tee -a /etc/php5/apache2/conf.d/user.ini
sudo apachectl restart
cd /var/www/public
sudo /usr/local/bin/composer self-update
composer create-project silverstripe/installer .
```

after downloading Silverstripe 3.4.1
I navigate with Safari to `http://192.168.33.10`
put the database password, which is `root`
put the administrator password, which is `password`
select as default language italian
I then click "Install Silverstripe"
Installer stops at phase Building database schema...
Error at Line 100 in `/var/www/public/framework/thirdparty/zend_translate_railsyaml/library/Translate/Adapter/thirdparty/sfYaml/lib/sfYaml.php`
Source has the line in red
`throw new InvalidArgumentException(sprintf('Unable to parse %s: %s', $file ? sprintf('file "%s"', $file) : 'string', $e->getMessage()));`
the trace shows `sfYaml::load(it: AddToCampaign:` [...omissis]
after issuing a build command via browser, by navigating
`http://192.168.33.10/dev/build`
a similar error displays
`[User Error] Uncaught InvalidArgumentException: Unable to parse string: Malformed inline YAML string (').`
then in another OSX shell I issue these commands

```
cd ~/vagrant/silverstripe-test-01/public/framework/lang
sudo gem install bundler
sudo gem install yamlclean
yamlclean it.yml > it_sanitized.yml
mv it.yml it.bak
mv it_sanitized.yml it.yml
```

after issuing a build command via browser, by navigating
`http://192.168.33.10/dev/build`
database builds completely

**Comment by dhensby** [comment] 2016-10-16 13:03
I think this is a duplicate of #5913

**Closed** 2017-05-10 08:35 UTC
