### ISSUE TITLE
Requirements_Backend does not allow URLs with ports

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#7130] opened 2017-07-04 23:30 UTC
Caused by over-tolerant regex in `Requirements_Backend::parseModuleResourceReference($file)`

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7131

**Comment by colintucker** [comment] 2017-07-05 08:19
Dupe of #7121

**Closed** 2017-07-05 10:31 UTC
Labels: impact/medium, type/bug
