### ISSUE TITLE
SiteTree DependentPages performance issue

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#8407] opened 2018-09-25 20:53 UTC
## Github link:

https://github.com/silverstripe/silverstripe-cms/issues/2276

## Affected Version

Version: 4.2.1 (c611c981e45409c8ab318f709a5d94cdd7e0ce84)

## Description

SiteTree::DependentPages() function creates an ArrayList of all dependant pages.

If you have a root page with 11 000 dependant pages the performance takes a big hit. It doesn't help that having this feature is mandatory and you can't remove this by configuration.

My recommendation is:

do not use ArrayList unless there is no other choice
make this feature be enabled/disabled via config
make this feature show on demand, not during edit for the page load

## Steps to Reproduce

Visit edit form of a page with 11 000 dependent pages and wait for 2.7 minutes

**Comment by chillu** [comment] 2018-09-30 21:49
Closing as duplicate of https://github.com/silverstripe/silverstripe-cms/issues/2276

**Closed by chillu** 2018-09-30 21:49 UTC
Labels: affects/v4, change/minor, effort/medium, impact/high, type/bug
