### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10250] opened 2022-03-07 02:24 UTC
Split off from https://github.com/silverstripe/silverstripe-framework/issues/10219

Upgrade all the support modules to support php 8.1

Agreed way forward to resolve common errors https://github.com/silverstripe/silverstripe-framework/pull/10237#issuecomment-1058557519

Reference to some breaking changes in php 8.1 - https://stitcher.io/blog/new-in-php-81#breaking-changes

### Note

~~Steve created some science experiment to add a `_a` method that can note docblock/parameter type mismatched and a `_c` method that can recast variable to their expected type. He also has a [script to apply it to the entire code base](https://github.com/emteknetnz/type-transitioner).~~

Update: this approach won't work for php 8.1.  Reason being that the _a() method profiling will certainly detect the say all the `string` and `null` arguments being passed in for a param, we cannot determine whether or not `null` is valid in this instance or not, so we don't know if `_c('string', $myvar, 1)` should be included or not

### Acceptance criteria
- [x] PHP8.1 build are green.
- [x] We don't break semver.
- [x] The magical process for auto updating our code base is documented somewhere. (it's in this issue)
- [x] CI fails on php deprecation warnings
- [x] graphql4 is also updated
- [x] Ensure an installable version of php 8.1 compatible tractorcow deps is available - see https://github.com/tractorcow/classproxy/pull/5#issuecomment-1109210797

### Explanation of the conversion process in the PRs below
- Automatic code modification using https://github.com/emteknetnz/php81-fixer
- Static code analysis that ensures any arguments passed to native php functions are not null
~~- If the native param only accepts a single type of `(string|bool|int|float)` then it is cast i.e `(string)`~~
~~- If the native param only accepts an `array` then it uses the ternary operator i.e. ` ?: []`~~
~~- If the native param accepts multiple types then it uses the ternary operator with a bias to using string i.e. ` ?: ''`~~
- Use the null coalescing operator for variables passed to native functions that do not accept null values
- There are some conditions where arguments are not converted such as the argument is a native constant, is an inner native function call with a single return type, is using the `class` static property e.g. `SiteTree::class`

Because this is an automated process this certainly goes on the side of over converting code.  If we move to full-type hinting param and return type in the future, we could run another code sweep to remove a bunch of the code conversions.  Currently we cannot rely on the docblock types as they are very unreliable.

There are also `#[\ReturnTypeWIllChange]` method attributes added to class methods where relevant, as well as some other methods that are updated, such as adding `__serialized()/__unserialized()`

### Current PHP 8.1 unit test status
- https://github.com/emteknetnz/silverstripe-installer/actions
- https://github.com/emteknetnz/recipe-kitchen-sink/actions

### Follow up PRs
- [x] https://github.com/silverstripe/silverstripe-travis-shared/pull/38

### PRs

GraphQL 3 PRs
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/454
- [x] https://github.com/silverstripe/silverstripe-elemental/pull/973
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1266
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/359

"Manual fix" PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10273
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/357
- [x] https://github.com/silverstripe/silverstripe-assets/pull/484
- [x] https://github.com/silverstripe/silverstripe-assets/pull/485
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10275
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2731
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/358
- [x] https://github.com/silverstripe/silverstripe-mfa/pull/449
- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/106
- [x] https://github.com/symbiote/silverstripe-queuedjobs/pull/370
- [x] https://github.com/silverstripe/silverstripe-travis-shared/pull/36
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10281
- [x] https://github.com/silverstripe/silverstripe-html5/pull/36
- [x] https://github.com/silverstripe/silverstripe-blog/pull/676
- [x] https://github.com/silverstripe/silverstripe-elemental/pull/976
- [x] https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/62
- [x] https://github.com/silverstripe/recipe-reporting-tools/pull/26

solr-php-client fork
- [x] https://github.com/silverstripe/solr-php-client/pull/1
- [x] https://github.com/silverstripe/silverstripe-fulltextsearch/pull/321

Installer (all prs use null coalesce)
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1294
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1264
- [x] https://github.com/silverstripe/silverstripe-assets/pull/483
- [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/212
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/230
- [x] https://github.com/silverstripe/silverstripe-config/pull/56
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2730
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10222
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/450 (graphql 3)
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/456 (graphql 4)
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/112
- [x] https://github.com/silverstripe/silverstripe-mimevalidator/pull/53
- [x] https://github.com/silverstripe/silverstripe-reports/pull/148
- [x] https://github.com/silverstripe/silverstripe-serve/pull/29
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/104
- [x] https://github.com/silverstripe/silverstripe-testsession/pull/73
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/356
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/238
- [x] https://github.com/silverstripe/MinkFacebookWebDriver/pull/18
- [x] https://github.com/silverstripe/recipe-plugin/pull/20
- [x] https://github.com/silverstripe/vendor-plugin/pull/52
- [x] https://github.com/symbiote/silverstripe-gridfieldextensions/pull/338

No changes
- silverstripe/silverstripe-errorpage
- silverstripe/silverstripe-siteconfig

Kitchen-sink (all prs use null coalesce)
- [x] https://github.com/silverstripe/silverstripe-akismet/pull/40
- [x] https://github.com/silverstripe/silverstripe-auditor/pull/42
- [x] https://github.com/silverstripe/silverstripe-blog/pull/675
- [x] https://github.com/silverstripe/silverstripe-ckan-registry/pull/266
- [x] https://github.com/silverstripe/comment-notifications/pull/44
- [x] https://github.com/silverstripe/silverstripe-comments/pull/338
- [x] https://github.com/silverstripe/silverstripe-contentreview/pull/163
- [x] https://github.com/silverstripe/silverstripe-documentconverter/pull/29
- [x] https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/85
- [x] https://github.com/silverstripe/silverstripe-environmentcheck/pull/76
- [x] https://github.com/silverstripe/silverstripe-externallinks/pull/77
- [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/102
- [x] https://github.com/silverstripe/silverstripe-fulltextsearch/pull/319
- [x] https://github.com/silverstripe/silverstripe-graphql-devtools/pull/41
- [x] https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/66
- [x] https://github.com/silverstripe/silverstripe-html5/pull/35
- [x] https://github.com/silverstripe/silverstripe-hybridsessions/pull/70
- [x] https://github.com/silverstripe/silverstripe-iframe/pull/58
- [x] https://github.com/silverstripe/silverstripe-ldap/pull/39
- [x] https://github.com/silverstripe/silverstripe-lumberjack/pull/111
- [x] https://github.com/silverstripe/silverstripe-mfa/pull/451
- [x] https://github.com/silverstripe/silverstripe-realme/pull/83
- [x] https://github.com/silverstripe/silverstripe-registry/pull/67
- [x] https://github.com/silverstripe/silverstripe-restfulserver/pull/98
- [x] https://github.com/silverstripe/silverstripe-securityreport/pull/54
- [x] https://github.com/silverstripe/silverstripe-segment-field/pull/64
- [x] https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/164
- [x] https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/51
- [x] https://github.com/silverstripe/silverstripe-spamprotection/pull/82
- [x] https://github.com/silverstripe/silverstripe-spellcheck/pull/50
- [x] https://github.com/silverstripe/silverstripe-subsites/pull/478
- [x] https://github.com/silverstripe/silverstripe-tagfield/pull/209
- [x] https://github.com/silverstripe/silverstripe-textextraction/pull/72
- [x] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/89
- [x] https://github.com/silverstripe/silverstripe-userforms/pull/1141
- [x] https://github.com/silverstripe/silverstripe-versionfeed/pull/70
- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/107
- [x] https://github.com/silverstripe/silverstripe-widgets/pull/189
- [x] https://github.com/symbiote/silverstripe-advancedworkflow/pull/460
- [x] https://github.com/symbiote/silverstripe-multivaluefield/pull/80
- [x] https://github.com/symbiote/silverstripe-queuedjobs/pull/371
- [x] https://github.com/bringyourownideas/silverstripe-maintenance/pull/177
- [x] https://github.com/silverstripe/cwp-agencyextensions/pull/72
- [x] https://github.com/silverstripe/cwp/pull/309
- [x] https://github.com/silverstripe/cwp-core/pull/106
- [x] https://github.com/silverstripe/cwp-pdfexport/pull/23
- [x] https://github.com/silverstripe/cwp-search/pull/42
- [x] https://github.com/silverstripe/silverstripe-elemental/pull/974
- [x] https://github.com/colymba/GridFieldBulkEditingTools/pull/222
- [x] https://github.com/tractorcow/classproxy/pull/5
- [x] https://github.com/tractorcow-farm/silverstripe-fluent/pull/763

No changes
- content-widget
- crontask
- elemental-fileblock
- security-extensions
- taxonomy
- dnadesign/silverstripe-elemental-userforms
- tractorcow/silverstripe-proxy-db

PRs for dependencies
- [ ] ~~https://github.com/PTCInc/solr-php-client/pull/8~~
^ if this isn't merged, then we should look to copy into thirdparty folder << update have moved to thirdparty folder in fulltextsearch module

**Comment by emteknetnz** [comment] 2022-03-07 04:42
Honestly this is starting to look like a nightmare due to the sheer number of call to native php functions like str_replace, where suddently `null` values are no longer allowed

The core issue of this is that Silverstripe was originally written for PHP 5 before param types were a thing, so everything is mixed value

We basically need to do this in a stunningly large number of places:

**framework Convert.php**
```
     * @param string $path
     * @param string $separator
     * @param bool $multiple Collapses multiple slashes or not
     * @return string
     */
    public static function slashes($path, $separator = DIRECTORY_SEPARATOR, $multiple = true)
    {
        $path = (string) $path;
```

Like wise we have the same issue with a lack of return type enforcement:

versioned **Versioned.php**
```
     * @return string
     */
    public static function get_reading_mode()
    {
        return self::$reading_mode;
    }
```

Which, despite what the dockblock says, it can be null.

So any calls to this method can now fail, such as `str_replace('abc', 'def', Versioned::get_reading_mode());`

I think we might actually be better off being more ambitious here and converting ALL the docblock to actual param and return types.  If not, were essentially stuck with the `$path = (string) $path;` casting of params instead

This would be a breaking change.

**Comment by emteknetnz** [comment] 2022-03-07 20:48
Options here are:
a) Use param casting method `$myvar = (string) $myvar;` and release as a minor of 4
b) Use param types which is a big API change, and release as 5 (new major)
c) Use param types which is a big API change, and release as 4 (semver violation) - with a very large note in the changelog saying there's a high chance you'll get regressions, so really do test this upgrade

@silverstripe/contributing-committers

**Comment by kinglozzer** [comment] 2022-03-08 09:36
I think we’d need to carefully consider the implications of jumping into a 5.x release for this. If we want to get away from monolithic major releases then that’s great, but we need to consider the implications for things like modules, support timelines and community expectations about what a major release is. I don’t think any of those challenges are insurmountable of course, but if a 5.x release is suddenly on the table then it should probably be part of a wider discussion around versioning/releases. If we do decide to take that path then we’d need to decide _which_ breaking changes to include - just the PHP compatibility? Or include embed v4 in that release instead of 4.x? Any other major pain points we can address at the same time? I honestly have no idea what the state of our `master` branch currently is, but forking a `5` branch from `4` instead of `master` is an option in the short-term.

Given the description of the issue in the comments above though, I don’t have any problem with option A. For core PHP functions we can cast arguments to their expected types, I can’t foresee any future problems or technical debt from that? For casting issues caused by core code, I think we just have to use our judgement. For the `Versioned::get_reading_mode()` example, I see two approaches:

1) We can cast the value returned anywhere _we_ use it in core code, and users who upgrade to PHP 8.1 will have to do the same in their code (and module authors will have to do the same too)
2) We treat docblocks as the source of truth, and implement casting in core code. Whether this is a BC-break is a bit ambiguous given the docblocks, but we just have to use our judgement to figure out how likely it is to actually cause issues for people. For `Versioned::get_reading_mode()` my instinct is that this approach would be fine, but there may be other methods where it wouldn’t be

Also cc-ing @silverstripe/core-team because the contributing committers group is smaller 😉

**Comment by emteknetnz** [comment] 2022-03-08 20:39
A) is feasible, and short term it's easier. My issues with it is that it's that it's still a significant amount of effort to implement, it's a frankly weird solution and it's kicking the can down the road

At some point we'll modernize the code and put types on everything anyway, so it seems like we should just do this step to begin with i.e. do it properly the first time around

> If we do decide to take that path then we’d need to decide which breaking changes to include - just the PHP compatibility?

If we do a major I think it's important to try and limit the amount of changes we try to put in for a few reasons:
- The more we breaking changes we put in, the more upgrade pain experienced by end users, who will have the major upgrade forced on them rather than by choice
- 3 to 4 was painful experience for many due to the many breaking changes, and many site owners had a very negative perception of the value in major upgrades.  4 to 5 it would be good if we could basically do the opposite
- People are leaning towards doing more frequent, smaller major upgrades, so if something misses the boat now, it's not lost forever.

**Comment by maxime-rainville** [comment] 2022-03-08 22:15
I would like us to get to a point where we can release new majors again. But that would require us to have a wider discussion around what we put in major and what kind of changes we ship in there. My preference would be to take the Symfony approach where new majors are just removing deprecated API and paying down some technical debt ... so basically, transitioning from CMS4 to CMS5 should be a much smaller step than CMS3 to CMS4.

But realistically, there's no way we could be in a position to do this before the end of this year.

So the question is do we want to have official PHP8.1 support in the 4 release line? If the answer is yes, then we have to decide between A and C. Option C seems like a bridge too far ... basically it's like releasing CMS 5, but pretending we are not.

I could live with Option A ... and we have taken this general approach in the past, but maybe we shouldn't have.

I guess there's an Option D here which would be tell people to suppress deprecation warning if they want to use PHP8.1. Maybe, that can be a transitory step to Silverstripe CMS 5.

**Comment by emteknetnz** [comment] 2022-03-08 23:10
I don't really like option D.  It's a similar story to how Silverstripe could actually run php 8.0 in a live environment several months before we officially announced it.  We delayed announcing this because phpunit 5.7 wasn't compatibile and we didn't want to say "PHP 8.0 works" when it wasn't 100% there.  Telling people they can use PHP 8.1 is just inviting confusion

> But realistically, there's no way we could be in a position to do this before the end of this year.

I don't think there's a pressing need to deliver PHP 8.1 at this stage, so delaying this by say 6 months doesn't seem like that big of a deal

It's also worth remembering that a lot community module won't be PHP 8.1 compatible either, so from a practical point of view PHP 8.1 is never going to be a quick win

**Comment by xini** [comment] 2022-03-22 23:23
> I don't think there's a pressing need to deliver PHP 8.1 at this stage, so delaying this by say 6 months doesn't seem like that big of a deal

That's infuriating! In 6 months time PHP 8.2 will almost be out and you should be looking at updating to 8.2 release candidates at that time! 

As already mentioned in https://github.com/silverstripe/silverstripe-framework/issues/10170, if you want to remove support for older PHP versions as soon as they go EOL even though there is no technical reason to do so (a.k.a 7.3), at least get onto supporting new versions as soon as they are out as well!

/rant. sorry. not.

**Comment by emteknetnz** [comment] 2022-03-30 01:52
Just updating on this one, we're almost certainly not going to look at updating function signatures on this one, as the scope of the work is simply too large, and it's too hard to validate which method parameters are legitimately nullable

Instead we're looking to use a combination of a [forked version rector](https://github.com/emteknetnz/rector) to update and something to [update docblock return types](https://github.com/emteknetnz/docblock-return-updater/blob/main/src/UpdateDocblockReturnTypeTask.php) (required for rector to function correctly) in order to get php8.1 compatibility within CMS4

Here's an example PR https://github.com/silverstripe/silverstripe-assets/pull/482/files

**Comment by maxime-rainville** [comment] 2022-04-06 09:19
Had a look at the first 3 draft PRs ... it seems like we are systematically explicitly casting some method parameters everywhere ... even one that logically will never return a `null` parameter: `rtrim((string) realpath((string) $filesPath)`.

I'm not super enthusiastic with this approach. It's going to be a lot of work to remove all those explicit cast if/when we switch to string type in a future major release. My instinct would have been to manually fix instances where `null` values breaks test until all the builds  are green.

Maybe, there's no other way to properly solve this than explicit cast everything. Is there any intermediary solution we could look at? Maybe we go over the automated tool's output and remove the explicit cast where it is obviously clear that the value will never be null.

**Comment by GuySartorelli** [comment] 2022-04-26 22:04
All linked PRs are merged and ACs are met.

**Closed by GuySartorelli** 2022-04-26 22:04 UTC
Labels: change/minor, impact/high, effort/hard, affects/v4
