### ISSUE TITLE
Config issues - merge_array_low_into_high

### ISSUE THREAD

**Issue by StephenHonor** [silverstripe/silverstripe-framework#5016] opened 2016-02-05 16:36 UTC
The issue is that this function is removing values when set to blank, null, false or 0.

Replication:
Create 2 separate yaml files:

```

---
Name: app
After: framework#coreroutes

---
TestClass:
  test_config_item1: true
  test_config_item2: false
```

```

---
Name: app2
After: framework/*

---
TestClass:
  test_config_item3: true
```

Expected outcome:
TestClass has 3 config items
- **test_config_item1** - true
- **test_config_item2** - false
- **test_config_item3** - true

Actual outcome:
TestClass has 2 config items
- **test_config_item1** - true
- **test_config_item3** - true

The line which has issues is the one below asterisked (Config class).

```
    public static function merge_array_low_into_high(&$dest, $src) {
        foreach ($src as $k => $v) {
*           if (!$v) {
                continue;
            }
            else if (is_int($k)) {
                $dest[] = $v;
            }
            else if (isset($dest[$k])) {
                $newType = self::get_value_type($v);
                $currentType = self::get_value_type($dest[$k]);

                // Throw error if types don't match
                if ($currentType !== $newType) self::type_mismatch();

                if ($currentType == self::IS_ARRAY) self::merge_array_low_into_high($dest[$k], $v);
                else continue;
            }
            else {
                $dest[$k] = $v;
            }
        }
    }
```

**Comment by kinglozzer** [comment] 2016-02-05 16:40
Possible related to https://github.com/silverstripe/silverstripe-framework/pull/3272? I believe that was fixed and then reverted because it broke other things. Not sure as I haven’t compared the two issues in any detail

**Comment by StephenHonor** [comment] 2016-02-05 16:45
It looks like its related.

However, nothing seems to have been done about it in 12 months.

It causes issues for the shop functionality because you can't disable
things without overriding.

**Comment by tractorcow** [comment] 2016-02-09 01:50
I agree that it's a problem if it's removing values that you have never overridden, but it's never been possible to overwrite non-falsey values with falsey ones in any case.

Perhaps `if (!$v) {` should be `if (!$v && ! array_key_exists($k, $dest)) {`

**Comment by tractorcow** [comment] 2016-02-09 01:53
I should probably ping @hafriedlander into this, since these are his rules.

**Comment by hafriedlander** [comment] 2016-02-09 01:56
Yeah, this isn't a bug. This is "deliberate, annoying legacy behaviour". The config system mirrors how statics used to be merged in 2.4. There is a patch around that allows you change how the merge occurs for various fragments, but the performance impact was too great to get it merged in 3.x (the config system gets hit a _lot_ during execution).

I'd be happy to have this rule change in 4, but it'll break a lot of code.

**Comment by hafriedlander** [comment] 2016-02-09 01:57
Also note, the existing behaviour is well documented in https://github.com/silverstripe/silverstripe-framework/blob/3/core/Config.php

**Comment by tractorcow** [comment] 2016-02-09 02:14
@StephenHonor I just need to check, what is the impact of the key not being present in the merged config? Config::inst()->get() would just return null, in this case. Does it break if, for instance, null is returned where false is expected?

**Comment by tractorcow** [comment] 2016-02-09 02:16
@hafriedlander that documentation doesn't cover the "keys with only falsey values not appearing at all in the merged config" which is coming up here, only that it won't merge over non-falsey values.

> * The exception to this is "false-ish" values - empty arrays, empty strings,
> * etc. When merging a non-false-ish value with a false-ish value, the result
> * will be the non-false-ish value regardless of priority. When merging two
> * false-ish values the result will be the higher priority false-ish value.

**Comment by hafriedlander** [comment] 2016-02-09 03:12
Oh, right. Missed that. It's come up so often, I just assumed it was the same. Sorry. Um, probably it should show up in that case, although "missing" is sort of the same as "undefined" which is the same as false-ish. Anyway, if it doesn't break existing code to change this specific case, I'm not against doing so.

**Comment by StephenHonor** [comment] 2016-02-09 07:00
The issue is that on the ss-shop module, it has an if statement checking
for 'must_have_price'. This is set to true by default within a static
variable on the class.

It makes sense to not show products if there is no price by default.
However, there's no way of turning it off without overriding the actual
module.

There's potentially another work around, and that's to set the variable on
the class, within the _config.php file. I will possibly test this today
sometime.

It just seems weirdly illogical that boolean variables, can't be set to
false if already true.

**Comment by daykinandstorey** [comment] 2016-02-09 10:43
Sorry for the double post.

However, what @tractorcow is saying is correct. The value appears to be set to a false value originally. The issue is that when you have a separate config adding additional values to the same class it simply removes the false values completely.

**Comment by tractorcow** [comment] 2016-02-09 22:11
> It makes sense to not show products if there is no price by default. However, there's no way of turning it off without overriding the actual module.

Sorry, this can only be overridden via PHP until we release a new config API that supports this, I'm afraid. This is yet a separate problem to the merging issue not including certain keys at all.

**Comment by gregsmirnov** [comment] 2016-10-19 14:44
The initial false-ish value is set depending on the order of configuration fragments.

```
---
Name: config1
---
Circus:
  enable_magic: false
---
Name: config2
---
Circus:
  actors:
    - John Doe
```

`Circus.enable_magic` value will be lost.

However if we change the order of fragments, the value will remain.
```
Name: config2
---
Circus:
  actors:
    - John Doe
---
Name: config1
---
Circus:
  enable_magic: false
---
```

That allows to "fix" this issue from the configuration point of view, by lowering the priority:

```
---
Name: mycms
After: '*'
---
SiteTree:
  nested_urls: false
```

I hope it will help someone using version 3.

**Comment by beerbohmdo** [comment] 2017-01-11 08:30
What is with this? :/
Could this please be fixed in at least ss-4? :(

https://github.com/silverstripe/silverstripe-framework/blob/master/src/Core/Config/Config.php#L386
https://github.com/silverstripe/silverstripe-framework/pull/3275
https://github.com/silverstripe/silverstripe-framework/pull/3272

**Comment by dhensby** [comment] 2017-01-11 15:16
There is some working going on with the `Config` system which will likely solve this problem - however a PR to master could probably do some good in the mean time?

**Comment by chillu** [comment] 2017-05-24 10:45
@micmania1 Do you think this is still an issue?

**Comment by dhensby** [comment] 2017-09-01 16:37
I believe this is fixed in 4, please reopen if not

**Closed by dhensby** 2017-09-01 16:37 UTC
Labels: affects/v3, type/bug
