### ISSUE TITLE
ToggleCompositeField::setStartClosed - always starts open

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-framework#10141] opened 2021-11-05 11:46 UTC
ToggleCompositeField always seems to start opened.
setStartClosed(true) has no effect.

### ACs
- [ ] When setting `setStartClosed(true)`, the ToggleCompositeField starts closed

**Comment by sabina-talipova** [comment] 2022-05-25 23:48
I have done few tests in three different local environments by using different branches ( 1, 1.9, 1.10, 1.11 ) and I couldn't reproduce this issue. I haven't done any changes, but I flush the cache a few times when I switched between branches. Also I flushed cache when I changed setStartClosed(true) to setStartClosed(false) and back.
@GuySartorelli could you add this code to your page and change setStartClosed(...) argument from true to false and back, trying to reproduce this issue. If you cannot reproduce it, I think we could close this issue.

```php
<?php

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
use SilverStripe\Forms\ToggleCompositeField;

class Page extends SiteTree
{
    private static $db = [
        'Summary'     => 'HTMLText',
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $summary = HtmlEditorField::create('Summary', false);
        $summary->setRows(5);
        $summary->setDescription('Test Description.');

        $summaryHolder = ToggleCompositeField::create(
            'CustomSummary',
            'CustomSummary',
            [ $summary ]
        );
        $summaryHolder->setHeadingLevel(4);
        $summaryHolder->addExtraClass('custom-summary');

        $summaryHolder->setStartClosed(false);

        $fields->insertAfter('Content', $summaryHolder);

        return $fields;
    }
}

```

**Comment by GuySartorelli** [comment] 2022-05-26 00:07
Cannot reproduce.

**Closed by GuySartorelli** 2022-05-26 00:07 UTC
Labels: impact/medium, affects/v4, type/bug
