### ISSUE TITLE
Alignment in HTML field doesn't work

### ISSUE THREAD

**Issue by jpbecotte** [silverstripe/silverstripe-framework#9949] opened 2021-05-20 20:46 UTC
## Affected Version
4.7.3

## Description

Clicking the alignment buttons of the WYSIWYG editor of any page doesn't do anything, while other controls (bold, lists, headers, etc) work as expected.

## Steps to Reproduce

1. Install a fresh site with `composer create-project silverstripe/installer new-site`
2. Install the blog extension `composer require silverstripe/blog`
3. Create a DB, setup the .env file
4. Connect to the admin interface /admin
5. Get the first page, select all the text.
6. Click on the « center » button.

**Comment by kinglozzer** [comment] 2021-05-21 08:04
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8785#issuecomment-845554377

**Closed by kinglozzer** 2021-05-21 08:04 UTC

**Comment by jpbecotte** [comment] 2021-05-21 12:33
This is not a duplicate. In 8785, the bug happens if you remove the simple theme. Here, it doesn't work WITH the simple theme!

**Comment by kinglozzer** [comment] 2021-05-21 16:14
Ah, sorry I didn’t realise you had the theme installed too! This is probably related to https://github.com/silverstripe/silverstripe-simple/issues/68 in that case.

Either way, I think #8785 covers this problem. Fixing that issue will fix this one 🙂
