### ISSUE TITLE
Update IntlLocales countries

### ISSUE THREAD

**Issue by Valandur** [silverstripe/silverstripe-framework#9126] opened 2019-07-15 12:57 UTC
## Affected Version

silverstripe/recipe-cms: 4.3.5

## Description

The current countries array does not include some countries that are listed on the [referenced ISO-3166-1 alpha 2 page](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements). Following country codes are missing:
  - CW -> Curaçao
  - SS -> South Sudan
  - SX -> Sint Maarten (Dutch part)

This ties in with https://github.com/silverstripe/silverstripe-framework/issues/8968, but may be fixable without a major version bump, assuming the countries are inserted with lowercase codes.

## Steps to Reproduce

1. Call `IntlLocales::singleton()->getCountries()`
2. Returned array of country codes is missing `'ss' => 'South Sudan'`

**Comment by robbieaverill** [comment] 2019-07-15 13:24
I'm going to close this as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8968, we can track the changes needed for this in that ticket as well. Thanks for reporting.

**Closed by robbieaverill** 2019-07-15 13:24 UTC
