### ISSUE TITLE
Image Documentation uses .Link instead of .URL (ss4)

### ISSUE THREAD

**Issue by ec8or** [silverstripe/silverstripe-framework#7767] opened 2018-01-16 18:56 UTC
The guide on Images is using `.Link` as a chainable example when you have to use `.URL`:

https://docs.silverstripe.org/en/4/developer_guides/files/images/

**Comment by dhensby** [comment] 2018-01-16 20:09
duplicate of #7764

**Closed by dhensby** 2018-01-16 20:09 UTC

**Comment by tractorcow** [comment] 2018-01-16 22:05
Also adding https://github.com/silverstripe/silverstripe-assets/pull/110 so that the symptoms of this issue are less severe.
