### ISSUE TITLE
[2012-11-12] Multiple DataExtension inheritance doesn't work

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1641] opened 2013-04-03 20:19 UTC
created by: @g4b0 (g4b0)
created at: 2012-11-12
original ticket: http://open.silverstripe.org/ticket/8024

---

If class A extends DataExtension, then class B extends A and finally DataObject C is extendend by B, the C::$db is not the A::$db + B::$db, but just B::$db.

example:

```
class A extends DataExtension {
  public static $db = array(
    'a' => 'Varchar';
  };
}

class B extends A{
  public static $db = array(
    'b' => 'Varchar';
  };
}

class C extends DataObject{
  public static $db = array(
    'c' => 'Varchar';
  };
}

Object::add_extension('C', 'B');
```

I expect that 

```
B::$db == array('a', 'b', 'c');
```

but it's just 

```
B::$db == array('b', 'c');

```

The same apply also for has_one relationship

**Comment by sb-relaxt-at** [comment] 2016-02-14 21:39
This is still an issue in 3.2. A proper fix seems to be a difficult. A quick workaround is the following implementation of extraStatics (in the base class): 

````
public function extraStatics($class = null, $extension = null) {
    return array_merge(
        parent::extraStatics($class, $extension),
            array(
              'db' => Config::inst()->get(get_parent_class($this), 'db'),
              'has_one' => Config::inst()->get(get_parent_class($this), 'has_one'),
              'has_many' => Config::inst()->get(get_parent_class($this), 'has_many'),
              'many_many' => Config::inst()->get(get_parent_class($this), 'many_many'),
              'belongs_to' => Config::inst()->get(get_parent_class($this), 'belongs_to')
            )
        );
    }
}

**Comment by kinglozzer** [comment] 2017-05-17 09:07
It may be worth testing this in SS4 to see if `DataObjectSchema` has resolved this

**Comment by tractorcow** [comment] 2017-05-17 10:56
Confirmed fixed in ss 4

```
<?php

use SilverStripe\Dev\SapphireTest;
use SilverStripe\Dev\TestOnly;
use SilverStripe\ORM\DataExtension;
use SilverStripe\ORM\DataObject;

class Test1641 extends SapphireTest {

    protected $usesDatabase = false;

    protected static $extra_dataobjects = array(
        A::class,
        B::class,
        C::class,
    );

    public function testDB()
    {
        $db = DataObject::getSchema()->fieldSpecs(C::class);
        $this->assertArraySubset(array(
            'a' => 'Varchar',
            'b' => 'Varchar',
            'c' => 'Varchar',
        ), $db);
    }

}

class A extends DataExtension implements TestOnly {

    private static $db = array(
        'a' => 'Varchar'
    );

}

class B extends A implements TestOnly {

    private static $db = array(
        'b' => 'Varchar'
    );

}

class C extends DataObject implements TestOnly {

    private static $extensions = array(
        'B'
    );

    private static $db = array(
        'c' => 'Varchar'
    );

}

```

**Closed by tractorcow** 2017-05-17 10:56 UTC
Labels: affects/v3, impact/low, type/bug
