### ISSUE TITLE
Shortcode parsed in HTMLEditorField

### ISSUE THREAD

**Issue by iqmeckert** [silverstripe/silverstripe-framework#6396] opened 2016-12-14 19:41 UTC
Shortcodes are now being rendered in the HTMLEditorField. It's possibly due to the addition of the casting variable on Value. The correct value is stored in the database, but when the field renders in the CMS, it parses the shortcode and renders the parsed shortcode value.
This effects site links, file links, and custom shortcodes

**Comment by iqmeckert** [comment] 2016-12-14 19:53
Issue can be fixed by removing casting value for Value from TextareaField & HTMLEditorField.

**Comment by iqmeckert** [comment] 2016-12-14 20:06
And updating the TextareaField template to $Value.RAW

**Comment by dhensby** [comment] 2016-12-15 18:53
@tractorcow

**Comment by tractorcow** [comment] 2016-12-15 20:14
On which branch sorry?

**Comment by iqmeckert** [comment] 2016-12-15 20:22
version 3. It looks like it was pushed in 3.3.4 & 3.4.2. 3.5 Seems to take care of it with extra config

**Comment by tractorcow** [comment] 2016-12-15 20:59
What raw HTML is coming up when editing a page that has shortcodes? You should see something along the lines of the below (testing with 3.5):

![image](https://cloud.githubusercontent.com/assets/936064/21241597/3065e090-c375-11e6-9c7d-4f044396b975.png)

In 3.2 the behaviour is very similar.

![image](https://cloud.githubusercontent.com/assets/936064/21241755/1444a7ba-c376-11e6-982b-7d592158d65a.png)

And in the editor:

![image](https://cloud.githubusercontent.com/assets/936064/21241782/30b33556-c376-11e6-827a-9494a919245f.png)

Can you please share your view and show how the shortcode is coming through?

**Comment by iqmeckert** [comment] 2016-12-15 21:13
Let's see if I can explain this better. This is happening for me on site tree links, as well as custom shortcode I 'm using. When I enter the shortcode into the WYSIWYG and save, when the form reloads, the shortcode is replaced with the parsed value. In the attached, I have a donate_button shortcode, (image 1), once I save the page, the shortcode is gone and the parsed value is displayed (image 2). The shortcode is correctly stored in the database, it's the rendering of textarea field that is causing the shortcode to be parsed.

![capturebefore](https://cloud.githubusercontent.com/assets/8713560/21242208/3a6494b8-c2e1-11e6-883e-3efaa97adcee.JPG)

![captureafter](https://cloud.githubusercontent.com/assets/8713560/21242219/43d1019e-c2e1-11e6-946e-5c55cd3fcb41.JPG)

**Comment by tractorcow** [comment] 2016-12-15 21:18
Oh I see, so this is the opposite of what I thought was occurring... I see now. :)

I don't suppose you would mind sharing the code for your donate button shortcode I could use as a test base?

**Comment by tractorcow** [comment] 2016-12-15 21:20
I also realise I should have tested in 3.4, not 3.5, sorry, which is probably why I didn't notice the issue.

**Comment by tractorcow** [comment] 2016-12-15 21:21
@dhensby do you have any thoughts on this?

**Comment by iqmeckert** [comment] 2016-12-15 21:32
Sure, I'm extending SiteConfig where the client enters the donate button HTML, my extension is also the class that holds the shortcode parser. My parser renders using a template, but the template just calls the code, thats still in there from troubleshooting. I was able to solve the problem by casting Value as Text in TextareaField.php and HTMLEditorField.php, and updating the template Textarea.ss to call $Value.RAW

[Custom_SiteConfig.txt](https://github.com/silverstripe/silverstripe-framework/files/655871/Custom_SiteConfig.txt)

**Comment by tractorcow** [comment] 2016-12-16 03:52
@iqmeckert fix at https://github.com/silverstripe/silverstripe-framework/pull/6410

@dhensby can you please double check this solution works?

**Comment by nickspiel** [comment] 2016-12-18 23:18
I am having the same issue on 3.4.2: 
![shortcode](https://cloud.githubusercontent.com/assets/5096172/21297436/3d57997c-c5d4-11e6-9ab4-f982829e578e.gif)

Is there an ETA on closing that issue?
Is the bug present in 3.5?

**Comment by tractorcow** [comment] 2016-12-19 02:58
@nickspiel I'd reverted the fix and re-created against HTMLEditorField only, but I'll re-implement for textareafield.

Apparently 3.5 does NOT have the same issue, due to the original regression-causing-fix being implemented slightly differently in that release.

**Comment by tractorcow** [comment] 2016-12-19 03:04
Updated https://github.com/silverstripe/silverstripe-framework/pull/6410

**Comment by nickspiel** [comment] 2016-12-19 04:26
Cool beans. 3.5 is working well. I have upgraded our build to use that so i am no longer desperate for this fix. Thanks for looking into it.

**Comment by tractorcow** [comment] 2016-12-20 02:10
Fixed with #6410

**Comment by tractorcow** [comment] 2016-12-20 02:10
Also a new 3.5.1 rc is out so you can use that. :)

**Closed by tractorcow** 2016-12-20 02:10 UTC
