### ISSUE TITLE
Tool to maintain repo and github metadata across all supported modules

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8343] opened 2018-08-26 22:48 UTC
Create a script which syncs up standard metadata across our supported modules. We've gone past the point where this is feasible to achieve manually. See Robbie's suggestion in https://forum.silverstripe.org/t/improving-the-way-we-maintain-the-silverstripe-open-source-ecosystem/859.

# Acceptance Criteria

 * Uses list of supported modules from the common JSON format
 * Can choose to run specific commands only (e.g. only update labels)
 * Runs in a few minutes (e.g. does sparse Github checkouts?)
 * Has an optional list where you can opt-out of specific modules for specific commands (e.g. those with a different license)
 * Uses local user for Github commits (assumes commit rights)

# Script features

 * Github labels (see [existing script](https://gist.github.com/chillu/45f9e9b777016f6257a64026aa84e0b3))
 * Contributing.md file (see [framework example](https://github.com/silverstripe/silverstripe-framework/blob/4/CONTRIBUTING.md))
 * [Issue and pull request templates](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) (see [framework example](https://github.com/silverstripe/silverstripe-framework/tree/4/.github))
 * LICENSE

# Notes

 * `.travis.yml` files are too complex for now

**Comment by robbieaverill** [comment] 2018-08-29 21:40
I've made a start on this with a Symfony console application for syncing labels to all supported modules: https://github.com/creative-commoners/maintain. The logic is based on https://gist.github.com/chillu/45f9e9b777016f6257a64026aa84e0b3 and it will pull the modules list from https://raw.githubusercontent.com/silverstripe/supported-modules/gh-pages/modules.json. I'll change this to use https://addons.silverstripe.org/api/supported-addons at some point, although that's a composer package name and we really need the GitHub slug

**Comment by robbieaverill** [comment] 2018-09-14 09:12
Cross referencing:

* Sync labels command: https://github.com/silverstripe/cow/issues/112
* Sync other stuff command: https://github.com/silverstripe/cow/issues/113

**Comment by robbieaverill** [comment] 2018-09-26 14:17
I've made a start with the file sync command in https://github.com/silverstripe/cow/pull/114. It'll currently pull the license from GitHub: https://github.com/silverstripe/supported-modules/blob/gh-pages/templates/LICENSE.md, then write, stage, commit and push any changes for each supported module.

We should add some extra metadata to https://github.com/silverstripe/supported-modules/blob/gh-pages/modules.json e.g. `"sync_files": true` for the modules we want this enabled for. Some supported modules we won't want this for, e.g. a LICENSE.md file with SilverStripe in the copyright wouldn't be right to push to a third party supported module, so we can skip it. For now I've just added a check to ensure it's under the SilverStripe GitHub account before pushing to it.

**Comment by dhensby** [comment] 2018-09-26 14:42
Ah, this is a good idea - it's been on my mind for a while. Things like branch protection set up and what not would be good too

**Comment by robbieaverill** [comment] 2018-11-09 13:04
Summarising some of the comments on [the proposed update the PR template](https://github.com/silverstripe/silverstripe-framework/pull/8347), and [the previous thread around introducing a PR template](https://github.com/silverstripe/silverstripe-framework/pull/7481):

###  We don't want to put people off contributing by making the process difficult

@dhensby: "I'm weary of making PRs more daunting and difficult to submit - are we actually addressing a problem that exists by implementing this template?"

### The tone should be first person

@tractorcow: e.g. "I confirm the following" rather than "Please confirm the following"

### Acknowledgement of code license

@dhensby: "If we are talking about giving up rights to the code in the PRs this probably needs to come as a more consistent and concerted effort across silverstripe projects and not just in framework and as a simple checkbox that can be edited after the fact." (@dhensby) - completing this task would achieve this

### Make sure we're actually solving a problem by doing this

@dhensby (again): "I'm weary of making PRs more daunting and difficult to submit - are we actually addressing a problem that exists by implementing this template?"

Me: In general I don't think there are a large number of low quality PRs - the problem is that there are so many of them that aren't being reviewed or merged. I think that by introducing something like the proposed checklist at #8347 we can ease this a bit by giving reviewers more of a guarantee that PRs will conform to our contribution expectations before we even look at them.

Note [@flamerohr said](https://github.com/silverstripe/silverstripe-framework/pull/7481#issuecomment-337426489) "The most important message is probably the "allow maintainers to make changes" permission to be set, so that maintainers could tailor parts accordingly if they have time - as opposed to wait 4 weeks for the creator to have time to get back to this."

^ I think that is enabled by default, but I agree. [@dhensby agrees](https://github.com/silverstripe/silverstripe-framework/pull/7481#issuecomment-337614078).

### KISS

@jonom suggested having a single checkbox: "I've reviewed the [contribution guidelines for issues and bugs](https://docs.silverstripe.org/en/contributing/issues_and_bugs/)."

[@sminnee suggested](https://github.com/silverstripe/silverstripe-framework/pull/7481#issuecomment-337384870) a simple checklist, e.g. "have you run linting" etc

## RFC: Add a CLA assistant

[RFC: Add a CLA assistant](https://github.com/silverstripe/silverstripe-framework/issues/7487) - this hasn't gone through the RFC labelling process, but has five 👍reactions - four total core committers are in favour. Doing this could remove the need for PR templates entirely.

[@chillu said on #7481](https://github.com/silverstripe/silverstripe-framework/pull/7481#issuecomment-339269151): "I think the CLA tooling is a better way to solve this than checkboxes in PR templates"

---

## New proposal

So with all of that combined, I think that implementing the CLA assistant (#7487) would be a good step, and either keep the PR template the way it is at the moment or remove it in favour of the CLA assistant.

Simple GitHub issue and PR templates can then be automatically synced to all commercially supported modules via a `cow` command.

@silverstripe/core-team are we happy with this?

**Comment by robbieaverill** [comment] 2018-11-19 11:19
Another thing that would be good to synchronise across modules is the phpcs ruleset. @unclecheese mentioned on #8569 that we should prefer single quotes over double quotes outside of required interpolation - this isn't part of PSR-2 but is a sensible rule we should enforce. Once all of our modules are relatively close to PSR-2 with a couple of exceptions like `public function MyControllerMethod()` and early returns in `class_exists()` checks we should be able to uniformly sync a ruleset to all modules. Framework is likely to be the most work here - see #7991

**Comment by robbieaverill** [comment] 2019-03-11 22:45
@chillu mentioned this new feature in GitHub this morning: https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

This would be good for CODE_OF_CONDUCT, CONTRIBUTING, and GitHub issue/PR template files. We wouldn't sync readmes and we don't really use SUPPORT files.

We'd need to remove existing files from repositories in order for this feature to work, since existing files take priority over organisation defaults. We could use this for placeholder readme files though.

We'd still need to use cow to sync licenses, phpunit/phpcs files, etc.

>You cannot create a default license file for your organization. License files must be added to individual repositories so the file will be included when a project is cloned, packaged, or downloaded.

**Comment by dhensby** [comment] 2019-03-11 22:58
> we don't really use SUPPORT files

We can start: https://github.com/silverstripe/silverstripe-framework/blob/4/SUPPORT.md

**Comment by robbieaverill** [comment] 2019-03-11 22:59
Touché! Nice =)

**Comment by GuySartorelli** [comment] 2024-08-05 02:42
This work has either been completed or is superceded by newer issues, respectively.

**Closed by GuySartorelli** 2024-08-05 02:42 UTC
Labels: type/enhancement, impact/low
