### ISSUE TITLE
Refactor RequiredField validator

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10467] opened 2022-08-24 10:38 UTC
The current behaviour for [`RequiredFields`](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/RequiredFields.php) is weird. It runs the individual validation for each field which seems like mixed concerns.

It also happily accepts a white space has a non-empty string.

**Comment by GuySartorelli** [comment] 2022-08-29 00:53
~~IMO this should be split into two separate validators - one for the required fields validation and another entirely separate validator for calling `validate()` on each field.~~
~~The latter of these could by default be included in scaffolded composite validators (e.g. on CMS edit forms).~~
We've implemented that.

As for the whitespace we should make it _not_ accept white-space as a "value" (i.e. if the value is only whitespace for a required field, throw a validation error) - but perhaps add a configuration option to allow it, in case someone has some valid use-case for whitespace-only values.

**Comment by GuySartorelli** [comment] 2024-09-17 04:22
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/10908

**Closed as not planned by GuySartorelli** 2024-09-17 04:22 UTC
Labels: type/api-break, impact/medium, complexity/medium, affects/v5
