### ISSUE TITLE
TreeDropdownField sometimes will not show any pages within the "Link to a page" dialog

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#8076] opened 2018-05-18 03:54 UTC
## Affected Version

```
silverstripe/admin           1.1.0  SilverStripe admin interface
silverstripe/asset-admin     1.1.0  Asset management for the SilverStripe CMS
silverstripe/assets          1.1.0  SilverStripe Assets component
silverstripe/campaign-admin  1.1.0  SilverStripe campaign admin interface
silverstripe/cms             4.1.0  The SilverStripe Content Management System
silverstripe/config          1.0.4  SilverStripe configuration based on YAML and class statics
silverstripe/errorpage       1.1.0  ErrorPage component for SilverStripe CMS
silverstripe/framework       4.1.0  The SilverStripe framework
silverstripe/graphql         1.1.0  GraphQL server for SilverStripe models and other data
silverstripe/reports         4.1.0  Reports module for SilverStripe CMS
silverstripe/siteconfig      4.1.0  Site wide settings administration.
silverstripe/userforms       5.1.1  UserForms enables CMS users to create dynamic forms via a drag and drop interfa...
silverstripe/versioned       1.1.0  SilverStripe Versioned component
```

## Description

Occasionally, within the 4.1.0 CMS, the `TreeDropdownField` that appears in the "Link to a page" dialog (accessed via the TinyMCE "Insert Link" dropdown) will not show any pages at all.  You can see a GIF of this bug below:

![peek 2018-05-18 12-42](https://user-images.githubusercontent.com/1853705/40214995-4d3b6540-5aa1-11e8-937b-4b44fafca6c9.gif)

Browser version: Firefox Quantum 60.0
User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Operating system: KDE neon 5.12.5

## Steps to Reproduce

1. Highlight text in editor.
2. Click "Insert link" in editor toolbar.
3. Select "Page on this site".
4. On the resulting dialog, try to select a page from the "Select a page" dropdown.

Sometimes it works, sometimes it doesn't.  I'm unsure of a reliable method as yet to consistently make it break.  If I discover one, I'll update the issue.

## Workaround

The field starts working as expected again after a full reload of the CMS in the browser.

**Comment by dhensby** [comment] 2018-05-18 09:48
sounds like a duplicate of https://github.com/silverstripe/silverstripe-admin/issues/472

**Comment by dhensby** [comment] 2018-05-18 09:48
Also, this is an admin/cms issue, not a framework one. If you feel it's significantly different to https://github.com/silverstripe/silverstripe-admin/issues/472 or https://github.com/silverstripe/silverstripe-admin/issues/496 please open an issue there.

**Closed by dhensby** 2018-05-18 09:48 UTC

**Comment by colintucker** [comment] 2018-05-20 06:14
Looks like the same one, thanks @dhensby :+1:
