### ISSUE TITLE
SapphireTest::$usesDatabase seems to be a noop

### ISSUE THREAD

**Issue by ntd** [silverstripe/silverstripe-framework#5557] opened 2016-05-18 09:50 UTC
The bugfix 43ff00ebd60adde181ef70cbd8d1a218c9a53fd9 changed the `SapphireTest` behavior: AFAIU the database is always created, also when you do not want to.

As an example, the following test:
```
class DummyTest extends SapphireTest
{
    protected $usesDatabase = false;

    public function testDummy() {
        $this->assertTrue(true);
    }
}
```

drops from 9.1 seconds to 0.1 seconds if I revert that commit.

**Comment by dhensby** [comment] 2016-05-18 14:35
Interesting, we should investigate.

I'm trying to find what the original intention is, maybe there's an accidental negating of the last condition or it should only be used in conjunction if one of the first two conditions are true?

**Comment by dhensby** [comment] 2016-05-18 14:55
Right, I've tested by running the test suite locally and there is no difference when including this patch or not.

I think in the instance where you're running *one* test and it doesn't need the DB, then it will probably be faster, but when running a suite of tests where some do and some don't need the DB, this doesn't appear to make a noticeable difference.

I agree with your assertion that `SapphireTest::$usesDatabase` seems to be needless

**Comment by ntd** [comment] 2016-05-18 15:09
> I think in the instance where you're running one test and it doesn't need the DB...

Yes, I often run a single test unit, e.g. for interactively checking regexes or output formatting routines.

I would rather not test than wait 9 secs for every iteration, so I'd personally prefer to fix the triggering condition than to drop `$usesDatabase`.

**Comment by dhensby** [comment] 2016-05-19 22:22
I agree - @chillu any insight on the original commit?

**Comment by chillu** [comment] 2016-05-20 00:05
Yeah we need to support TDD, and a 9 sec single test case run is a big blocker for that. It also makes it less likely that devs will try to decouple systems - what's the point of abstracting away a DB dependency if the tests run slowly (with a DB) anyway?

Sooo, six year old commit, I don't know the exact details on https://github.com/silverstripe/silverstripe-framework/commit/43ff00ebd60adde181ef70cbd8d1a218c9a53fd9, but Dan's suggestion on there (`if(($fixtureFile || $this->usesDatabase) && !self::using_temp_db())`) sounds like a good solution. So I'd rather fix the conditional than remove `$usesDatabase` altogether.

@ntd Wanna give that a shot and send a PR? Since it fixes a regression, and relies on opt-in behaviour (`$usesDatabase = false`), it sounds fairly safe to go into the current `3.4` release branch? Not necessarily in the pending `3.4.0` release of course.

**Comment by dhensby** [comment] 2016-05-20 14:41
Fix at #5573 

`if(($fixtureFile || $this->usesDatabase) && !self::using_temp_db())` isn't quite right because if a temp db is being used then we won't create any of the fixtures.

the `using_temp_db` check looks to only be needed to determine if we need to actually create a DB or not

**Comment by kinglozzer** [comment] 2016-05-20 15:59
Closed in https://github.com/silverstripe/silverstripe-framework/commit/4e6d0b39823cb239ca21e1412b1105db5ca68039

**Closed by kinglozzer** 2016-05-20 15:59 UTC

**Comment by dhensby** [comment] 2016-05-20 16:28
@ntd which version of SS were you using? Is my fix working for you?

**Comment by ntd** [comment] 2016-05-20 17:31
:+1:  Yes, it works. I had to backport it to 3.3.2 though:

[0001-FIX-5557-Tests-with-no-DB-requirements-wont-create-t.patch.txt](https://github.com/silverstripe/silverstripe-framework/files/275135/0001-FIX-5557-Tests-with-no-DB-requirements-wont-create-t.patch.txt)

Is it planned to be released in 3.4.1? Actually I am using it with 3.3.2 in a long term project but I don't mind switching to 3.4.1 when it will be ready.

**Comment by dhensby** [comment] 2016-05-20 17:34
I'll be forward merging. I it'll make 3.3 and 3.4

**Comment by dhensby** [comment] 2016-05-22 23:22
@ntd merged forward - if you wouldn't mind doubly confirming :)

**Comment by ntd** [comment] 2016-05-23 06:40
I tested 2ae2675a471f69271b03ed5f3de9d7ed04dc022a and it works as expected. Many thanks.

**Comment by dhensby** [comment] 2016-05-23 07:05
Fantastic

**Comment by nfauchelle** [comment] 2016-06-17 11:50
Ran into and fixed this locally. Went to submit a patch to find it already done! Nice work guys :-) I have half a dozen tests which don't touch the DB and this makes a huge difference.
