### ISSUE TITLE
Use bootstrap for SS3-JS-driven areas

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5643] opened 2016-06-01 23:47 UTC
(See also: Oly's pull request)

 * Page, reports, siteconfig, etc (the areas not powered by React) use bootstrap for CSS.

**Comment by chillu** [comment] 2016-06-13 22:00
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/5677

**Closed by chillu** 2016-06-13 22:00 UTC
