### ISSUE TITLE
bad video url leads to server error

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#9294] opened 2019-10-18 21:43 UTC
## Affected Version

SS 4.4.4

## Description

Our client had a live video: https://vimeo.com/event/15595 of an event. Once the event is over, the video is no longer available. This leads to a server error!

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/167154/67129986-93143980-f25c-11e9-8240-ec5bba6e7411.png)

add to source code:
```html
<div class="leftAlone ss-htmleditorfield-file embed" data-url="https://vimeo.com/event/15595" data-shortcode="embed"><img class="placeholder" src="pic.ng" width="1280" height="720" /></div>
```
RESULT ... 
![image](https://user-images.githubusercontent.com/167154/67130238-2b122300-f25d-11e9-99a7-70d61640c68a.png)

![image](https://user-images.githubusercontent.com/167154/67130278-49781e80-f25d-11e9-9a85-bce96d0b72d4.png)

**Comment by brynwhyman** [comment] 2019-10-20 22:25
Thanks for raising this issue. I'm going to close it as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/9073 (given that has some comments already)

**Closed by brynwhyman** 2019-10-20 22:25 UTC

**Comment by sunnysideup** [comment] 2019-10-20 22:33
Thank you
