### ISSUE TITLE
SS4-beta3: Gridfield pagination partially broken

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#7376] opened 2017-09-14 21:19 UTC
SilverStripe4-beta3 has broken pagination with the left/right icons displayed as grey blocks, and neither of them working. Currently the only way to paginate is to type the page you want to go to.

In doing so however (typing the page in the pagination input field), when one tries to navigate away from the page it causes a warning about not saving the data (dirty warning?).

![screen shot 2017-09-15 at 09 12 27-fullpage](https://user-images.githubusercontent.com/1463435/30456211-d5cbdeba-99f6-11e7-82c0-5b261619be98.png)

**Comment by tractorcow** [comment] 2017-09-14 21:24
Duplicate of https://github.com/silverstripe/silverstripe-admin/issues/242, and is fixed now.

**Closed by tractorcow** 2017-09-14 21:24 UTC
