### ISSUE TITLE
Casting is not respected when using different case in templates

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10469] opened 2022-08-25 05:42 UTC
## Description
PHP methods and `DataObject` properties are case insensitive.
If you get some method or property case insensitively in a template, it will render the correct _value_ but will fall back to the default casting.

## Steps to Reproduce

In a page class:
```php
class Page extends SiteTree
{
    public function MyHtmlField()
    {
        return '<strong>strongboi</strong>';
    }
}
```
In a template:
```ss
<h2>Correct casting</h2>
$MyHtmlField
<h2>Incorrect casting</h2>
$myHtmlField
```

## Acceptance Criteria
- [ ] The correct casting is applied when you access some property or method with a different case than is defined in PHP code.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10470

**Comment by michalkleiner** [comment] 2022-09-07 19:59
Could this be caused by the mechanism when it's trying to get an existing method, perhaps in a case-sensitive way, and if it doesn't exist it tries to prepend `get` there and then the casting is not applied because the method name doesn't match with the `get` prefix?

**Comment by GuySartorelli** [comment] 2022-09-07 21:59
I think the attached PR illustrates the cause pretty well - basically `ViewableData::castingHelper()` is using `isset()` to see if the field name is in its casting config - but `isset()` is case sensitive so of course the following will return false even though the field we want is in the config:
```php
$config = [
    'MyField' => 'Text',
];
isset('myField', $config);
```

**Comment by michalkleiner** [comment] 2022-09-07 23:08
Of course. I missed the link to the PR which I've just approved.

**Comment by lozcalver** [comment] 2022-09-08 08:12
PR merged

**Closed as completed by lozcalver** 2022-09-08 08:12 UTC
Labels: impact/medium, complexity/medium, type/bug
