### ISSUE TITLE
RFC Move test suite to Codeception

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#7202] opened 2017-07-21 12:57 UTC
## Problem

Currently our test suites are either mangled together (unit tests and functional tests all run off the same core `SapphireTest` dependency) or completely separate (behat).

Whilst our unit and functional tests are built on top of PHPUnit, our use of `SapphireTest` is still somewhat idiosyncratic and confusing for newcomers. Behat tests are generally seen by developers/the community as difficult to get running and a scary/different method to write.

The separation of our behat tests from our other tests also means we have separate ways of setting up fixtures for tests, managing sessions, and  managing test behaviour. Of course, there's also a new syntax (Gherkin) to learn for writing behat tests which requires a good knowledge of SilverStripe's pre-defined features and contexts.

Summary:
 - High barrier to entry for acceptance testing
 - Poor documentation around testing
 - New syntax and approach needs to be learnt for each test type

### Deliver a phased approach to move over to Codeception as preferred test suite throughout 4.x lifetime.

I suggest a phased approach where we aim to move first unit tests (4.1), then functional tests (4.2), then acceptance tests (4.3) over to SilverStripe.

We would keep `SapphireTest` for the life of 4.x so that external projects that depend on it are not forced to migrate and legacy tests continue to run.

As we phase our test suite over new tests (new test classes) will need to be written in Codeception and amendments to existing tests will have to be made to codeception tests if they've been migrated.

Pros:
 - Unified test suite, syntax and approach across all test suites
 - Better external documentation to guide developers
 - More powerful and modular testing tools
 - Lower barrier to entry for all types of tests
 - Can retain gherkin tests

Cons:
 - Migration of tests to new format
 - Migration of behat fixtures/contexts 

### Move to Codeception in SS 5.x

I feel this isn't feasible as the 5.x delivery is so far away someone will have to commit to re-writing every new test into codeception for 5.x which is years of commitment. Otherwise it means putting this off for years.

Pros:
 - We won't run two test suites side-by-side

Cons:
 - Big delay to core support
 - Large amount of effort to migrate new tests over the coming years

### Migrate smaller core modules to Codeception and leave framework to last

We could focus on migrating smaller modules to Codeception over framework which would allow us to build the support for all three test types more quickly.

Pros:
 - All 3 test types supported relatively quickly

Cons:
 - Fragmented testing standards across modules
 - Dual support of fixtures/contexts across modules and core

#### Terminology

**Unit test**: A test that only tests objects and their methods. There is no direct interaction with the Framework's request handling
**Functional test**: A test that mocks requests through the Framework's request handlers directly using PHP
**Acceptance test**: A test that interacts with a browser to make real HTTP requests to the framework -
 Currently behat tests

#### Relevant links

http://codeception.com/docs/01-Introduction

**Comment by dhensby** [comment] 2017-07-21 13:02
**Of course I've chosen yet another mammoth piece of work to investigate.**

I didn't want this RFC to turn into a big blurb about why codeception is awesome, their docs do that pretty well and reading through their guide shows off the features well.

I've already started on a codeception "framework" module (https://github.com/dhensby/codeception-silverstripe) and I've started working on migrating some unit tests (https://github.com/dhensby/silverstripe-framework/compare/pulls/4/codeception)

**Comment by unclecheese** [comment] 2017-07-21 20:19
Thanks for taking the lead on this, Dan. I largely agree with a lot the points you've made. Anything we can do to increase the speed of our tests is worth considering. I'm also quite keen on the API of Codeception versus Behat. I think, like most users, I find it more accessible. Currently, getting set up with Behat is a real bear, and it's not encouraging the outcome we want, which is better test coverage across all modules.

If we're going to do a phased approach across the lifetime of 4.x, how will that affect our Travis set up? Would we essentially have the same number of tests, only more jobs?

**Comment by sminnee** [comment] 2017-07-22 02:26
I think that replacing a blob of code that's heavily coupled to PHPunit/behat with a blob of code that's heavily coupled to codeception wouldn't be much of a step forward.

I also think that the material problems are with behat, not phpunit

I'd advocate:
 * refactor the muck from behat/sapphiretest/functionaltest into a set of services
 * use them in a behat -> codeception refactor
 * migrate PHPunit tests last

**Comment by sminnee** [comment] 2017-07-22 02:40
Reading the codeception docs, a few comments:

 * cept, cest, and test form? Lol jargon! It looks like you've favour the cest form although the test form is closer to what we currently have. The cept form is gross.
 * I can't see us using the db helper; we'd probably want a similar helper object that manages test databases via the ORM.

**Comment by sminnee** [comment] 2017-07-22 03:22
So, expanding on what I mean about extracting SapphireTest into a set of services, the goal is basically to amend our tests so that they inherit from PHPUnit_Framework_TestCase instead of SapphireTest.

From my view this is the best first step towards a Codeception migration:

 * You can do it incrementally without doubling-up test infrastructure and confusing people (the confusion of the mid-way PHPUnit -> Codeception won't be worth the relative benefits of Codeception IMO).
 * The refactors necessary to do this will be necessary for a Codeception migration. (We'll end up with some specific code/classes referenced in setUp / tearDown)
 * The benefit of these refactors can be achieved as they happen, and if we don't get through them all, we still see some value delivered (fewer tests bound to SapphireTest).
 * These are the changes that will actually speed things up — moving to Codeception would only speed things up accidentally by forcing you do to this work along the way.
 * You avoid the risk of introducing a hard-coupling to Codeception.

Once this is done, in principle shifting to Codeception after this should be a reasonably mechanical process: change the base class and a few method names. Specifically, it should be able to be done in a single PR for the whole of framework.

In parallel to this I'd advocate migrating behat to codeception. For unit testing, PHPUnit is basically as good as Codeception, so moving from Behat + PHPUnit to Behat + Codeception makes little sense. However, moving from Codeception + PHPUnit to just Codeception has the benefit of consistency.

What are some of the refactors I would envision? Basically, the following goodies provided by SapphireTest should be separate services that you reference in setUp / tearDown.

 * Creation of, per-test resetting, and connection to a test database, including flushing ORM caches
 * required_extensions support
 * Extra Director routes
 * Mock email system
 * Access to fixture objects

In addition some stuff probably doesn't require an actual service, but just needs refactoring of tests not to rely on this minor convenience.

 * Resetting the i18n locale / timezone
 * Logging in as ADMIN
 * Various pieces of config that have been hardcoded into SapphireTest::setUp() to make things more consistent. (Member password validator, Cookie.report_errors, source_file_comments)
 * DBField support in assertContains / assertNotContains (just cast as string)
 * assertDOSContains (it's only used twice across all core modules)

There are some bits of core that would be good to refactor such that they're not needed

 * FlushableTestState: Flushable and Resettable shouldn't be necessary as long as you've nested a Kernel
 * GlobalsTestState: Refactor code to not rely on globals
 * VersionedTestState: This should be refactored to be unnecessary with a nested kernel

**Comment by robbieaverill** [comment] 2017-07-23 01:16
I agree with both the problem highlighted in this RFC and the comments that Sam has made about coupling to something else instead of fixing the issues.

I'm not familiar at all with Codeception, but my thoughts from using the test harnesses so far are that:

* there are few real "unit tests" in SS
* writing them without SapphireTest is hard
* using SapphireTest is slow, especially with fixtures
* Behat is easy to use, but harder to get started with in a module (much easier to extend SapphireTest and write unit tests immediately)

I can see huge value in separating the functional tests and the harness for them from the ability to write simple unit tests.

SS doesn't always provide easy ways to mock dependencies without fixtures or slight amounts of over abstraction for the sake of partial mocking, but I think SS4 will help with this since there's a more prevalent use of injection.

I'm particularly interested in the "let's make testing easier and faster in SS" part of this but not so much for tying to anything other than what we have already.

**Comment by micmania1** [comment] 2017-07-23 21:31
We used codeception on our previous project so here's a summary of what I found.

In terms of the unit/functional testing features - these were pretty much unusable because all of the SilverStripe functionality (temp db, fixtures, flush, etc.) are all tied up in SapphireTest. Even if these were moved to a set of traits (rather than services), the functionality could be used wherever and it would be an improvement currently. In the end we stuck with SilverStripe/SapphireTest for unit and functional testing.

In regards to Robbie's comment; pure unit testing in SilverStripe is near impossible anyway, with static calls everywhere, dependencies on cache and concepts like data extensions which essentially couples everything closely together. There's probably more value in spending time on functional & integration testing than trying to force things.

I found the acceptance testing functionality to be almost there and it was pretty easy to get up and running, both on my local machine and CI. It could do with a testsession type thing so that database isn't hard-coded, but other than that I don't really have any complaints about it. 

In regards to Sam's comment:
> The cept form (raw PHP without any kind of class/method wrapper) is pretty gross and hopefully we can avoid it entirely.

This was my initial thought but the actions of the test are procedural and it doesn't hold any state itself so actually makes sense. Each test has a page object where the re-usable parts go to reference things on the page (ie. input fields, buttons etc.)

**Comment by dhensby** [comment] 2017-07-24 14:22
> @unclecheese If we're going to do a phased approach across the lifetime of 4.x, how will that affect our Travis set up? Would we essentially have the same number of tests, only more jobs?

The travis set up should be simple - we'd add an extra step to the build process to run the codeception suite alongside the existing PHPUnit suite, much like we do with the code style tests.

**Comment by dhensby** [comment] 2017-07-24 14:40
I agree with @sminnee and @robbieaverill that we shouldn't just move one test dependency to another for no real gain and so we should focus on moving the behat tests first.

If we move behat tests, then there becomes less reason to maintain SapphireTest and we could start moving everything over to Codeception if it's deemed valuable.

Regarding @micmania1's feedback: I feel a lot of the sentiment is true for SS 3 (though I've had functional testing working for an SS 3 project). But it's a stretch to say these things are impossible because of temp DBs, fixtures and flushing, sure they are functionality missing from vanilla codeception but they were missing from vanilla PHPUnit, they just need to be integrated with codeception. Though the creation of a randomly named temp DB isn't actually a requirement of a test suite as we can run against a `.env.testing` that defined separate DB creds for testing or some other fixed credentials for test DBs. The current aim (though perhaps not implemented fully) of our test DBs is to create a DB with a partly random name upon test suite start and then trash it at the end - using a developer dictated DB name isn't really something we should be scared of.

**Comment by tractorcow** [comment] 2017-07-24 22:09
A reasonable goal prior to this refactor would be to get rid of SapphireTest and move to an entirely injection-controlled TestState controller as a component rather than a base class. That would mean we could use any test framework we wanted without coding for a specific base class.

The bulk of what is left in SapphireTest would be "helpers" easily shifted to traits or other services.

**Comment by mateusz** [comment] 2017-09-11 21:11
Fascinating read! I've learned that there is no consensus how a "unit test" looks like in the SilverStripe.

Few loose thoughts to append.

My definition of a unit test is a device for testing public interface of a class (unit=class) with all dependencies factored out (no state necessary, apart from reliance on structs a.k.a. value objects). Trying to do this kind of thing with SS3 Framework echoes micmania1's sentiment, "impossible". Disclosure: I haven't tried SS4 yet. Upon a brief look TestState looks like a good manoeuvre, but the biggest problem is still DataObject - you touch it, you pull in the world.

Unit tests are useful because they can afford to be really nitpicky and specific - if they fail, the issue is sure to be contained in the class being tested. They also entice authors of classes to be hygienic about class's public interface and dependencies.

With the amount of state it holds, SapphireTest seems to simply be a "functional test", just with fancy name.*  But perhaps Framework's concept of Unit Test is simply different?

*) Sapphire? Where did THAT come from :D Can it be renamed to JspartyTest? Just joking.

**Comment by robbieaverill** [comment] 2017-09-11 21:14
I wonder whether we could move towards a stateless unit test framework that is just PHPUnit with composer's autoloader (NB: introduces a PSR-4/autoloader requirement, whereas it's currently just a recommendation). Then we can slowly move off SapphireTest and leave it for (as Mateusz says) functional testing.

**Comment by sminnee** [comment] 2017-09-11 21:25
SilverStripe unit tests are more like component tests: https://martinfowler.com/bliki/ComponentTest.html

**Comment by sminnee** [comment] 2017-09-11 21:32
My recommendation for what to do next would be to elaborate on what "Refactor the muck from behat/sapphiretest/functionaltest into a set of services" might look like specifically.

Hackday project, maybe?

**Comment by chillu** [comment] 2018-09-04 10:09
Since I've stumbled on it again, I figured that I'll link to my previous thoughts on Behat vs. Codeception over at https://github.com/silverstripe/silverstripe-behat-extension/issues/62#issuecomment-159717821

**Comment by robbieaverill** [comment] 2018-09-10 21:33
I feel like we have a fair bit to do in terms of improving the PHPUnit test suite and PHPDocs, perhaps we should close this for now in favour of tidying up what we already have?

**Comment by chillu** [comment] 2018-09-11 06:35
Yeah, I don't see this RFC having a chance of becoming reality soon. I'm closing this not because I'm against the idea, but because we shouldn't keep things open when there's no implementation plan for the next year or so.

**Closed by chillu** 2018-09-11 06:35 UTC
Labels: affects/v4, feedback-required/core-team, impact/high, rfc/draft

**Comment by robbieaverill** [comment] 2018-10-19 11:33
I've just had another look over this and given the following problems:

* Our unit tests are not really unit tests
* Behat is designed for non-devs to write the scenarios, but in practice it actually needs a dev to write them
* We spend a lot of time maintaining Behat tests

... perhaps this might be a good idea after all, for SS5?
