### ISSUE TITLE
summary_fields in GridField escape html incorrectly

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#11200] opened 2024-04-17 00:35 UTC
### Module version(s) affected

5.x-dev

### Description

See: https://github.com/sunnysideup/silverstripe-5-test-with-summary-fields
#### Packages (see composer file)
![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/f8bd9cb7-02ce-4592-98aa-ddcb96b2d43f)

#### Relevant Code
![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/43225248-e1c4-4b94-9603-485045284244)

#### Create company
![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/0b309f09-b47b-46e2-b51a-56cb1340236e)

#### List Company

![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/60aa3f0c-e3b6-437a-82d3-6de1cc3107eb)

### How to reproduce

See: https://github.com/sunnysideup/silverstripe-5-test-with-summary-fields

The repo is a fresh install of SS. You can install this and then add a company with a logo. Then the GridField basically does not show the log, but instead it show the raw html (escaped). 

### Possible Solution

Can provide more details if required, but please review first. 

### More examples

![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/79c8f92b-a8fe-466e-97a8-b2f2701214dc)
![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/fbbe5ed9-6e1c-4570-8633-af6bc1a08d85)

### Additional Context

Changed about a month or two ago. 

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment] 2024-04-17 00:43
Please provide a **text** description of what exactly the problem is, and what the expected behaviour is.
Please include any images that help to demonstrate the problem.
Please provide any code as markdown-formatted code blocks rather than images so they can be copy-pasted for easy reproduction.
Please include clear step-by-step instructions for reproducing the bug.

A link to a repository is not a bug report. I'm sorry but the CMS Squad simply doesn't have enough time to look at your repository and figure out for ourselves what the problem is - please spell it out so we can easily prioritise this as appropriate.

**Comment by GuySartorelli** [comment] 2024-04-17 00:43
> Can provide more details if required

Yes, please do.

**Comment by GuySartorelli** [comment] 2024-04-17 01:02
> Please provide a text description of what exactly the problem is, and what the expected behaviour is.

This request is not optional - while I do appreciate you reporting a bug, it is very hard for me to understand what exactly the problem is without you describing what the problem is and what the expected bahaviour is.

> Please provide any code as markdown-formatted code blocks rather than images so they can be copy-pasted for easy reproduction.

I have added this request to my earlier comment. Images of code are not useful, because I can't copy them into my IDE to validate I get the same results that you get.

Note that the repository you have provided is not useful to me in identifying what the problem is - I need to be able to understand what the problem is, and reproduce it locally myself from a fresh installation of Silverstripe CMS.

**Comment by GuySartorelli** [comment] 2024-04-17 04:49
Having taken a glance at the screenshots, it looks like this is probably a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/11191.

I'm going to close it as a duplicate for now. If it isn't a duplicate, I'm going to need some words that explain to me why not.

**Closed as not planned by GuySartorelli** 2024-04-17 04:49 UTC
