### ISSUE TITLE
Updating tests is a mild goose chase when supplying Director::test with urls relative to base.

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#7689] opened 2017-12-10 22:50 UTC
https://github.com/silverstripe/silverstripe-framework/blob/d57dea03184aec636ab7af5f0d81be2b7cb03693/src/Control/Director.php#L259

This line always prepends e.g. `/home/users/moduleupgrader/public_html/silverstripefour/testsite`, which then doesn't match any director rule, as they're all relative to the base (as is sensible). This results in every single call to `Director::test` fail with `404` (unless the test expects a 404).

This is worked around by defining an `Director.alternative_base_url` in the config during `setUp`, but even then issues seemed to arise between whether or not to include a trailing slash on that base, and requires a test/upgrading developer to prefix all URIs with the alternative base (if there are assertions to check `Location` header for example).

While this is ok, and can be mitigated, I certainly didn't find it very helpful, and ultimately spent far too long trying to figure out why every test failed where I couldn't see a reason for it (it seems in the past that relative URIs worked as expected). To this end I personally don't think that test URIs should be prepended with the base, as in the CLI (where tests now always run since the removal of the `dev/tests` controller) will always be relative to root, which seems a bit unnecessary really.

Or perhaps I'm missing the vision of some compelling reason? If so, please share.
At the least I think some extra docs might be nice, as it's a gotcha that certainly gotme.

# PR:

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7705

**Comment by tractorcow** [comment] 2017-12-10 23:11
> This line always prepends e.g. /home/users/moduleupgrader/public_html/silverstripefour/testsite, 

This to me seems an error with `constants.php` not safely determining BASE_URL constant if you've forgotten to set an `SS_BASE_URL` environment variable. Not the main issue though...

> which then doesn't match any director rule, as they're all relative to the base (as is sensible). This results in every single call to Director::test fail with 404 (unless the test expects a 404).

Also, `Director` uses `baseURL()` method, but `HTTPRequestBuilder::createFromVariable` uses `BASE_URL` constant only; This is probably the main issue here (if one differs from one another, it breaks).

When you test this code and it fails, what is the difference between your `BASE_URL` and `Director::baseURL()`?

**Comment by tractorcow** [comment] 2017-12-10 23:13
> To this end I personally don't think that test URIs should be prepended with the base, as in the CLI (where tests now always run since the removal of the dev/tests controller) will always be relative to root, which seems a bit unnecessary really.

$_SERVER[`REQUEST_URI`] always needs to have the base, otherwise it won't be correctly replicating the functionality of the frontend. CLI-ification of HTTP Requests is always an approximation at best.

**Comment by dhensby** [comment] 2017-12-12 10:58
Is this mainly because we no longer have `$_FILE_TO_URL_MAPPING`? If so, that was the purpose of `SS_BASE_URL`, that needs to be defind for CLI just as `$_FILE_TO_URL_MAPPING` was for v3

**Comment by tractorcow** [comment] 2017-12-12 20:28
@NightJar can you please dump your `$_SERVER` var in constants.php so I can confirm a possible fix?

**Comment by tractorcow** [comment] 2017-12-14 04:45
ok, two bugs fixed with https://github.com/silverstripe/silverstripe-framework/pull/7705:

 - Stop inferring BASE_URL on CLI. If you don't have SS_BASE_URL set it never works properly, so it's just fixed to empty base now.
 - Fixed HTTPRequest mocking in Director::mockRequest(). Now we can pass the relative $url straight into the request builder instead of letting it incorrectly mock it from BASE_URL constant (which may differ from the current Director::baseURL()).

**Comment by tractorcow** [comment] 2017-12-15 03:25
Lol, I just noticed the `mild goose chase`.

For when you're not quite up for a wild goose chase right? :P

**Closed** 2017-12-17 20:22 UTC
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug

**Comment by dhensby** [comment] 2017-12-20 16:41
Can someone catch with mild goose!
