### ISSUE TITLE
Error when create ModelAdmin mange a model having many_many - from/through/to relationship

### ISSUE THREAD

**Issue by grandcreation** [silverstripe/silverstripe-framework#8284] opened 2018-07-24 22:08 UTC
## Affected Version
SilverStripe 4.1.1

## Description

I follow exactly the instruction from the home page to create a very simple many_many relationship object
<pre>
use SilverStripe\ORM\DataObject;

class Team extends DataObject
{
    private static $many_many = [
        "Supporters" => [
            'through' => 'TeamSupporter',
            'from' => 'Team',
            'to' => 'Supporter',
        ]
    ];
}
class Supporter extends DataObject
{
    private static $belongs_many_many = [
        "Supports" => "Team",
    ];
}
class TeamSupporter extends DataObject
{
    private static $db = [
        'Ranking' => 'Int',
    ];

    private static $has_one = [
        'Team' => 'Team',
        'Supporter' => 'Supporter',
    ];
}
</pre>

It is working good until i create the ModelAdmin to manage the Team object. It return an error when i try to access the Team Management page

<pre>
   private static $managed_models = [
        'Team'
    ];

    private static $url_segment = 'team-management';

    private static $menu_title = 'Team Management';
</pre>

**Comment by grandcreation** [comment] 2018-07-24 22:09
It is working well if i just use many_many without "through", "from", "to" section

**Comment by maxime-rainville** [comment] 2018-07-27 05:44
Hi @grandcreation. Thanks for reporting this issue.

What's the error you are seeing on your end? Is the error showing immediately once you access your model admin, or do you have to navigate the relation?

I just tried it on SilverStripe 4.2 and it's working for me.

**Comment by lekoala** [comment] 2018-08-01 17:35
I have similar issues due to hasMany doing a preg_replace on the following array. This causes Notice: Array to string conversion.

```
    [SubTeams] => SilverLeague\IDEAnnotator\Tests\SubTeam
    [Comments] => SilverLeague\IDEAnnotator\Tests\TeamComment
    [Supporters] => Array
        (
            [through] => SilverLeague\IDEAnnotator\Tests\TeamSupporter
            [from] => Team
            [to] => Supporter
        )

```

**Comment by chillu** [comment] 2018-09-09 21:27
No feedback, can't reproduce, closing

**Closed by chillu** 2018-09-09 21:27 UTC
Labels: affects/v4, feedback-required/author
