### ISSUE TITLE
Error "Undefined index: REQUEST_URI" using Director::forceWWW() on cli-script.php in live mode.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4770] opened 2015-11-13 03:35 UTC
If you call Director::forceWWW() from _config.php while in live mode using cli-script.php, it will return a notice-level error.

Easiest fix is probably to do nothing when `Director::is_cli()` is true, as it's not really relevant for CLI execution.

Present in 3 branch

**Comment by dhensby** [comment] 2015-11-13 12:00
Duplicate of #4025

**Closed by dhensby** 2015-11-13 12:00 UTC
