### ISSUE TITLE
[BUG][VIEW] Using source_file_comments causes issues with ReadOnly field

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#6857] opened 2017-04-29 04:45 UTC
It will render a strange outpit, like the following:
```
<p id="Form_ItemEditForm_NoYubikeyCount" tabindex="0" class="form-control-static readonly" <!--="" include="" 'silverstripe="" forms="" ariaattributes'="" --=""><!-- template /data/site/docroot/silverstripe-admin/themes/cms-forms/templates/SilverStripe/Forms/Includes/AriaAttributes.ss -->

	aria-labelledby="title-Form_ItemEditForm_NoYubikeyCount "

<!-- end template /data/site/docroot/silverstripe-admin/themes/cms-forms/templates/SilverStripe/Forms/Includes/AriaAttributes.ss --><!-- end include 'SilverStripe/Forms/AriaAttributes' -->&gt;
	<i>('none')</i>
</p>
```
Where, due to the commenting, a few strange things happen in the displaying of the field

**Comment by dhensby** [comment] 2017-11-24 21:43
still a problem?

**Comment by Firesphere** [comment] 2017-11-25 06:41
Yes, this still happens in the CMS

**Comment by tractorcow** [comment] 2017-11-27 03:35
Might I suggest something like:

```
<%-- disable-comments --%>
<% if $Message || $Description %>
	aria-describedby="<% if $Message %>message-$ID<% end_if %> <% if $Description %>describes-$ID<% end_if %>"
<% end_if %>
<% if $Title || $RightTitle %>
	aria-labelledby="<% if $Title %>title-$ID<% end_if %> <% if $RightTitle %>extra-label-$ID<% end_if %>"
<% end_if %>
```

We could check for the `<%-- disable-comments --%>` string in SSViewer::parseTemplateContent, and disable `source_file_comments` just for that string.

**Comment by tractorcow** [comment] 2017-11-27 03:37
Um, maybe 4.0.2, since 4.0.1 is pretty close.

**Comment by adrian-stein** [comment] 2018-02-21 05:59
Any time frame or version of when this will be fixed?

**Comment by a2nt** [comment] 2018-03-14 06:22
I can confirm issue using SS 4.1.0

**Comment by Juanitou** [comment] 2018-06-26 11:45
Still present in 4.1.2:
![image](https://user-images.githubusercontent.com/807463/41909337-0dd71dda-7947-11e8-85f0-0020ec6ab9b0.png)

**Comment by robbyahn** [comment] 2019-11-14 01:12
Still an issue only in checkbox in framework 4.4.4. 
![image](https://user-images.githubusercontent.com/2970208/68818108-cd041e80-06e8-11ea-97e0-14accb82c87a.png)

**Closed** 2023-09-25 04:20 UTC
Labels: complexity/low, impact/medium, affects/v4, type/bug
