### ISSUE TITLE
Shortcodes don't get rendered in template escaped values

### ISSUE THREAD

**Issue by jacobbuck** [silverstripe/silverstripe-framework#5661] opened 2016-06-07 02:32 UTC
In my model, the value of my `Content` field is:

```html
<p><a href="[sitetree_link,id=1]">Home</a></p>
```

In my template I have:

```html
$Content.XML
```

What gets rendered out is:

```html
&lt;p&gt;&lt;a href=&quot;[sitetree_link,id=1]&quot;&gt;x3eHome&lt;/a&gt;&lt;/p&gt;
```

But I'd expect to see:

```html
&lt;p&gt;&lt;a href=&quot;/home/&quot;&gt;x3eHome&lt;/a&gt;&lt;/p&gt;
```

**Comment by jacobbuck** [comment] 2016-06-07 02:45
Also if I update my template to:

```html
$Content

$Content.HTMLATT

$Content.URLATT

$Content.RAWURLATT

$Content.ATT

$Content.RAW

$Content.JS

$Content.HTML

$Content.XML
```

This renders out:

```html
<p><a href="/">Home</a></p>

&lt;p&gt;&lt;a href=&quot;[sitetree_link,id=1]&quot;&gt;Home&lt;/a&gt;&lt;/p&gt;

%3Cp%3E%3Ca+href%3D%22%5Bsitetree_link%2Cid%3D173%5D%22%3EHome%3C%2Fa%3E%3C%2Fp%3E

%3Cp%3E%3Ca%20href%3D%22%5Bsitetree_link%2Cid%3D173%5D%22%3EHome%3C%2Fa%3E%3C%2Fp%3E

&lt;p&gt;&lt;a href=&quot;[sitetree_link,id=1]&quot;&gt;Home&lt;/a&gt;&lt;/p&gt;

<p><a href="[sitetree_link,id=1]">Home</a></p>

\x3cp\x3e\x3ca href=\"[sitetree_link,id=1]\"\x3eHome\x3c/a\x3e\x3c/p\x3e

&lt;p&gt;&lt;a href=&quot;[sitetree_link,id=1]&quot;&gt;Home&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;&lt;a href=&quot;[sitetree_link,id=1]&quot;&gt;Home&lt;/a&gt;&lt;/p&gt;
```

**Comment by tractorcow** [comment] 2016-06-07 06:15
Dupe of https://github.com/silverstripe/silverstripe-framework/issues/1381

**Closed by tractorcow** 2016-06-07 06:15 UTC
