### ISSUE TITLE
Increased Memory Usage in SilverStripe 5.x Compared to 4.x

### ISSUE THREAD

**Issue by PixNyb** [silverstripe/silverstripe-framework#10952] opened 2023-09-20 15:31 UTC
## Description

In SilverStripe version 5.x, we are experiencing significantly higher memory usage compared to SilverStripe 4.x. This increased memory usage is observed across various operations and appears to be impacting the overall performance of the application.

Expected Behavior:

- SilverStripe 5.x should maintain memory usage levels comparable to or lower than SilverStripe 4.x.

Observed Behavior:

- SilverStripe 5.x is exhibiting memory usage that is approximately double that of SilverStripe 4.x.

## Steps to Reproduce

1. Set up a fresh installation of SilverStripe 4.x.
2. Perform a specific operation that involves memory usage tracking (e.g., loading a large dataset, executing a complex query, etc.).
3. Note the memory usage during this operation.
4. Upgrade the SilverStripe installation to version 5.x.
5. Repeat the same operation that was performed in step 2.
6. Observe the memory usage during the operation in SilverStripe 5.x.

Expected Result:

- The memory usage in SilverStripe 5.x during the operation should be comparable to or lower than the memory usage observed in SilverStripe 4.x.

Actual Result:

- The memory usage in SilverStripe 5.x during the operation is significantly higher, approximately double the memory usage observed in SilverStripe 4.x.

## Additional Information

- Operating System: Cross-platform
- PHP Version: Experienced in 8.x, but likely affects all versions
- Web Server: Apache, Nginx
- Database: MySQL, MariaDB

## Others Interested

- @martinviolet88 - Violet88
- @derkgort - TwistedBytes

**Comment by GuySartorelli** [comment] 2023-09-21 01:13
Hi,

Thank you for reporting this. Did you happen to do any profiling to discover any specifics about what might be causing the increased memory usage?

As well as that, do you have any data that indicates how much of a problem this actually is? Currently this report just say "increased memory usage" but are we talking a 3% increase during normal requests? Or a 500% increase?

**Comment by PixNyb** [comment] 2023-09-26 07:54
I haven’t had the chance to thoroughly benchmark SilverStripe, however we’ll have 2 versions of the same application running hopefully by the end of the day and I’ll be able to benchmark them both.

**Comment by GuySartorelli** [comment] 2023-09-27 22:55
I've just checked this with a fresh installation of silverstripe/installer, with the latest stable 4.13.x and the latest stable 5.0.x,
Both setups used the same versions of MySQL and PHP 8.1.
I used lekoala/silverstripe-debugbar to identify memory usage for full requests to the homepage.

In both setups, a page load with a flush used 20MB.
In the CMS 4 project, a _cached_ page load used 4MB.
In the CMS 5 project, a _cached_ page load used 2MB.

So I'll definitely need more information about what your setup specifically is to reproduce your results.

**Comment by PixNyb** [comment] 2023-09-27 23:19
Hmm that's odd. The two applications are currently being monitored by Derk. From my experience working with ss5 some time ago using dockerized deployment, a basic ss4 install used on average around 100-150mb where the ss5 install used around 300, occasionally jumping up to 400-450 while idling. I'll be testing the two projects tomorrow, using local docker containers and xdebug to profile the entire application.

**Comment by PixNyb** [comment] 2023-09-29 01:31
Alright so i've gotten around to benchmarking the applications and the results appear to be what I expected. This application doesn't seem to jump up to 400mb but still uses significantly more data:

| Silverstripe | CPU % | MEM USAGE / LIMIT | MEM % | NET I/O  |  BLOCK I/O | PIDS |
| --- | --- | --- | --- | --- | --- | --- |
| CMS 5 | 0.01% | 234.1MiB / 15.52GiB | 1.47% | 12.1MB / 4.84MB | 11.3MB / 84.7MB | 10 |
| CMS 4 | 0.01% | 151.1MiB / 15.52GiB | 0.95% | 703kB / 1.43MB | 33MB / 38.7MB | 8 |

This is after loading the homepage of each application once. Looks like Silverstripe 5 might be caching more?
Both of these docker containers run the same php 8.1 + apache installation. I'll profile them more thoroughly tomorrow.
After leaving them idle for a little while the memory usage doesn't seem to go down either

**Comment by GuySartorelli** [comment] 2023-09-29 01:35
Without knowing a lot more about your setup I can't reproduce those results... 
If you can provide a docker image and code and, if relevant, a copy of a database or SQL script to add the data, along with reproduction steps, that would be very helpful.

If we can't reproduce your results, it will be very hard to work towards resolving whatever's going on.

**Comment by GuySartorelli** [comment] 2023-10-19 00:22
@PixNyb 

Have you had a chance to document your environment and produce some reproduction steps? I'd be keen to investigate this, but there's just not enough information here to go off at the moment.

**Comment by GuySartorelli** [comment] 2024-03-14 20:41
I'm going to close this issue since there isn't enough information here to begin investigating a cause - let alone confirm there's even a product-level problem here.

If you can provide more information I'll be happy to reopen this issue.

**Closed as not planned by GuySartorelli** 2024-03-14 20:41 UTC
Labels: type/bug, affects/v5
