### ISSUE TITLE
Image in summary_fields breaks searching/linking DOs

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-framework#10761] opened 2023-04-26 06:23 UTC
If a DO has thumbnails in `$summary_fields`,  probable just not text, an error like `ERROR [Emergency]: Uncaught InvalidArgumentException: "CMSThumbnail" is not a field on class "SilverStripe\Assets\Image"` is thrown by linking existing records in Gridfield.
```php
    private static $summary_fields = [
        'Image.CMSThumbnail' => 'Thumbnail',
        'OtherImage.StripThumbnail'    => _t(self::class . '.IMAGE', 'Image')
    ];
```
The error can be circumvented by explicitly leaving out such fields in `searchable_fields` or using a helper method like `getStripThumbnail()` in the DO. This probable started with 4.11.x or 4.12.x. See https://silverstripe-users.slack.com/archives/C0QSDASKT/p1680281217612129 for context.

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/10885
- https://github.com/silverstripe/developer-docs/pull/311

**Comment by NightJar** [comment] 2023-04-26 09:26
> See https://silverstripe-users.slack.com/archives/C0QSDASKT/p1680281217612129 for context.

History doesn't last forever, so here goes at reformatting:

---

**Issue identifier** [26 days ago](https://silverstripe-users.slack.com/archives/C0QSDASKT/p1680281217612129)
Alright, so I asked this previously, but I'm blocked right now by this issue. I feel like I'm misunderstanding something fundamental here: I keep getting errors when I try to link an existing record in a Gridfield; the related record in question has an Image field, a thumbnail when rendered in your typical Gridfield; however, when I try to link that related record, I get "StripThumbnail" is not a field on class "SilverStripe\Assets\Image" . The Image class extends File  which has the ImageManipulation trait. That should be providing the needed StripThumbnail method (amongst others). My $summary_field is pretty vanilla...

    public function summaryFields()
    {
        // ...
        return [
            'Image.StripThumbnail'    => _t(self::class . '.IMAGE', 'Image')
            // ...
        ];
        // ...
    }



**Bystander A**  [25 days ago](https://silverstripe-users.slack.com/archives/C0QSDASKT/p1680311263398509?thread_ts=1680281217.612129&cid=C0QSDASKT)
Just tried to replicate your issue in one of my projects and your code works fine. I was able to attach existing records and create new ones. I tried it with both an image assigned to the record and without. I was using silverstripe/recipe-cms 4.12.0@stable. Best of luck

**Affected participant** [12 days ago](https://silverstripe-users.slack.com/archives/C0QSDASKT/p1681451843413009?thread_ts=1680281217.612129&cid=C0QSDASKT)
did you sort this? ATM I'm running into it with latest 4.12. Looks like defining searchable_fields circumvents it. This smells much like a bug.

App\Models\MyCustomDataObject:
  searchable_fields:
    - 'Title'

**Issue identifier** [12 days ago](https://silverstripe-users.slack.com/archives/C0QSDASKT/p1681482529422499?thread_ts=1680281217.612129&cid=C0QSDASKT)
It's definitely a bug, I can reproduce it consistently. I got around it by adding a helper method to my dataobject, so instead of doing `$summary_fields = [ 'Image.StripThumbnail' => 'Image' ]` I did `$summary_fields = [ 'getStripThumbnail' => 'Image' ]`

Never had to do that pre 4.12x

**Affected participant** [11 days ago](https://silverstripe-users.slack.com/archives/C0QSDASKT/p1681588818979759?thread_ts=1680281217.612129&cid=C0QSDASKT)
Before I've tried defining searchable_fields, I've downgraded silverstripe/admin to 4.11.x with no luck. Is there already a bug on github? The change in 4.11 to search for individual fields in $searchable_fields across multiple fields could be a possible cause.
https://docs.silverstripe.org/en/4/changelogs/4.11.0/#other-features

**Comment by sabina-talipova** [comment] 2023-07-12 02:46
Hi @lerni and @NightJar,
I am trying to reproduce your issue locally. Could you please confirm that the following steps are correct.
1. I have a DataObject that contains the following code:
```php
<?php
use SilverStripe\ORM\DataObject;
use SilverStripe\Assets\Image;

class MyDataObject extends DataObject
{
  private static $db = [
    'Name' => 'Text',
  ];

  private static $has_one = [
      'MyImage' => Image::class,
      'MyPage' => Page::class,
  ];

  private static $summary_fields = [
      'Name',
      'MyImage.StripThumbnail' => 'Image'
  ];
}
```
2. I can upload image and see image thumbnail in GridField after I created new MyDataObject.
3. When I search for particular image in the list of MyDataObjects  I get 500 Server Error `InvalidArgumentException: "StripThumbnail" is not a field on class "SilverStripe\Assets\Image"`.
4. If I add `  private static $searchable_fields = [ 'MyImage.Name',]; ` to `MyDataObject` everything works as expected.

Could you also confirm PHP version and if PHP version is `>= 8`, that the code below doesn't have any errors.
```php   
private static $summary_fields = [
        'OtherImage.StripThumbnail'  => _t(self::class . '.IMAGE', 'Image'),
];
```

Thank you.

**UPDATE:** Could you, please, also confirm that your logic assumes search for image thumbnail.

**Comment by lerni** [comment] 2023-07-17 08:22
Thx @sabina-talipova looking into this!
1. yes DO like so - to be sure, I also past code.
```php
<?php

namespace App\Models;

use \Page;
use SilverStripe\ORM\DataObject;
use SilverStripe\Assets\Image;

class MyDataObject extends DataObject
{
    private static $db = [
        'Name' => 'Text',
    ];

    private static $has_one = [
        'MyImage' => Image::class,
        'MyPage' => Page::class,
    ];

    private static $summary_fields = [
        'Name',
        'MyImage.StripThumbnail' => 'Image'
    ];

    // AFAIK $searchable_fields inherits from $summary_fields
    // if MyImage is omitted here, all is fine
    private static $searchable_fields = [
        'Name'
    ];

    private static $owns = [
        'MyImage'
    ];

    private static $table_name = 'MyDataObject';

}
```
2. yes
3. Search with `%` in GridFieldAddExistingAutocompleter thorws the error on a associated Page for example.
```php
<?php
...
    private static $has_many = [
        'MyImages' => MyDataObject::class.'.MyPage'
    ];
...
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();


        $MyImageGridFieldConfig = GridFieldConfig_Base::create(20);
        $MyImageGridFieldConfig->addComponents(
            new GridFieldEditButton(),
            new GridFieldDeleteAction(false),
            new GridFieldDeleteAction(true),
            new GridFieldDetailForm(),
            new GridFieldAddNewButton('toolbar-header-right'),
            new GridFieldAddExistingAutocompleter('toolbar-header-right')
        );
        $gridField = new GridField('MyImages', 'MyImages', $this->MyImages(), $MyImageGridFieldConfig);
        $fields->addFieldToTab('Root.Main', $gridField);

        return $fields;
    }
    ...
```
![searchDOwithThumb](https://github.com/silverstripe/silverstripe-framework/assets/472115/9c82ec75-e273-468d-bed6-c02784f195d7)

4. Don't think so! See `$searchable_fields` & comment above - this fixes the issue for me.

I use PHP8.1 and can test on 7.4 & 8, but don't think this makes a difference. There is no custom logic involved, just as outline above.

**Comment by NightJar** [comment] 2023-07-17 09:51
I've taken a quick look at this now; I was just helping with commentary on the issue before.

Think about what is happening and what has changed, I've come to a hypothetical conclusion (**untested**):
**I think this is normal, and was always an issue... BUT is much more easily triggered now that ALL fields are searched by default.**

The docs were updated to highlight this.

![image](https://github.com/silverstripe/silverstripe-framework/assets/778003/079377a2-ce39-47e5-8ebb-dade4f6c156c)

Please note this little warning info box about searchable fields not working on non-database backed fields did not exist in the documentation prior to 4.12.0 (and moving the docs to a new repository).

https://github.com/silverstripe/silverstripe-framework/blob/4.11.0/docs/en/02_Developer_Guides/00_Model/11_Scaffolding.md#searchable-fields


# Lets consider the use case before and after 4.11.

## Before
I have a model. It has summary fields that include an image thumbnail. This works great!
There is a search - I have **not** defined searchable fields.
Summary fields are used by default, which includes the image.
The default search context only searches the first summary field (e.g. Title) without expanding advanced search terms, etc.
Title is searched. A result is found. We are happy.
**Searching for an image _probably_ triggers an error,** but no one ever searches for an image with text because that would be silly.

Consider an example:
CMS 4.11 - I search for a `Member` that exists, but by `Surname`. Only the `FirstName` is searched.
![image](https://github.com/silverstripe/silverstripe-framework/assets/778003/1a955a81-353e-4544-9512-1451071c8475)
But using the advanced search dropdown and putting the same detail into `Surname` yeilds more results than expected.
![image](https://github.com/silverstripe/silverstripe-framework/assets/778003/f2b65aec-60ff-47de-b1c5-4f032e806970)

If there was an extension to Member that added a profile picture, this issue would **not** be triggered.



## After
I have a model. It has summary fields that include an image thumbnail. This works great!
There is a search - I have **not** defined searchable fields.
Summary fields are used by default, which includes the image.
The default search context seraches ALL the fields, INCLUDING the image.
This fails spectacularly. No results, we are not happy.
**Searching for anything _always_ triggers the error.**

# So where does that leave us?

The change was good, but perhaps not far enough.
**Before**: we didn't hit a server error but had a poor experience. E.g. I would expect searching for a Member that I _know_ exists to return a result. But it didn't.
**After**: we hit a server error, but the experience is much nicer if we don't. E.g. I would have found the Member I knew existed, and been happy... _unless_ I had summary images on for my Members.

## There is a work around

@lerni has already found the interim solution in that defining searchable fields to _not include images_ resolves the issue. As above, no one searches for images anyway because that would be silly without some kind of AI powered search tool that has access to all our files 😬

## So the work around resolves the issue?

No. Not really. It works around it, and resolves it in the one use case.
But this is a bug - even though a probably pretty good arguement could be made that it isn't.
Actual behaviour is very different from expected behaviour... and expected behaviour that already exists in other areas. See `GridFieldFilterHeader`.
https://github.com/silverstripe/silverstripe-framework/blob/193a12ac018631b9baa7570f7e354cdbcb1a3ace/src/Forms/GridField/GridFieldFilterHeader.php#L275-L278
The behaviour was always wrong, even though the fix could be argued to be new behaviour. I see this as a lack of behaviour that should have always existed. There is a `DataObjectSchema` that exists to easily look up if a field has DB backing or not. All the tools are there to have this work as expected without a poor developer experience. They just need connecting 🙂 

# All of this has been a fantastic diversion from the real issue

Any site that makes use of `GridFieldAddExistingAutocompleter` on a model that has an image and does not define `searchable_fields` that has been working fine for 5+ years [suddenly stopped working after a minor upgrade](https://github.com/silverstripe/silverstripe-framework/issues/10761#issuecomment-1523087451).

> [I keep getting errors](https://silverstripe-users.slack.com/archives/C0QSDASKT/p1680281217612129) **when I try to link an existing record in a Gridfield**

https://github.com/silverstripe/silverstripe-framework/blob/193a12ac018631b9baa7570f7e354cdbcb1a3ace/src/Forms/GridField/GridFieldAddExistingAutocompleter.php#L342

**Comment by raspberryswwwirl** [comment] 2023-07-17 14:40
Can confirm that the reduced cases supplied by @lerni and @NightJar illustrate the issue accurately. Defining a custom helper method in `$summary_fields` to work around the issue is exactly that: a workaround; however, it does not resolve the issue with using *. StripThumbnail. The current state of this issue, does not fall into the category of configuration or convention when, this error never surfaced itself prior to v4.12.

Retrofitting previously working code w/ this work around just to suppress the exception is a significant time-sink. It's not a set-it-and-forget it task, but something we now have to do across multiple projects. So, considering it's not uncommon to define thumbnails w/ content-oriented DOs (including searching or linking these DOs), my sense is that this error should be properly handled as a feature or adequately suppressed.

**Comment by sabina-talipova** [comment] 2023-07-17 20:47
@lerni, @NightJar, @raspberryswwwirl, Thanks a lot for your comments and clarifications. Now the problem has become more obvious and I think I know what caused it. We will discuss the issue and try to resolve it as soon as possible.

**Comment by GuySartorelli** [comment] 2023-08-03 03:26
Fix merged. It'll be auto-tagged when CI has run.

**Closed as completed by GuySartorelli** 2023-08-03 03:26 UTC
Labels: impact/medium, affects/v4, type/bug, affects/v5

**Comment by NightJar** [comment] 2023-08-07 08:19
Thanks @sabina-talipova, @GuySartorelli!
