### ISSUE TITLE
[CMS] Site tree sort values are not saved to _versions table

### ISSUE THREAD

**Issue by frankmullenger** [silverstripe/silverstripe-framework#5800] opened 2016-07-13 04:55 UTC
Currently when a tree node is moved in the site tree the Sort fields for all siblings are updated in the base table for that class only:
https://github.com/silverstripe/silverstripe-framework/blob/master/admin/code/LeftAndMain.php#L1384

Which leads to the matching records for the current version in the _versions table having incorrect Sort values.

We have used a patch in onAfterWrite() which isn't ideal but might be useful to help describe the issue:

```
public function onAfterWrite()
    {
        parent::onAfterWrite();

        // Update the latest version for each record with the correct Sort value because LeftAndMain::savetreenode()
        // only updates the SiteTree table. We rely on SiteTree_versions in augmentSQL() for futurestate.
        DB::prepared_query("
            UPDATE \"SiteTree_versions\", \"SiteTree\"
            SET \"SiteTree_versions\".\"Sort\" = \"SiteTree\".\"Sort\"
            WHERE \"SiteTree_versions\".\"RecordID\" = \"SiteTree\".\"ID\"
            AND \"SiteTree_versions\".\"Version\" = \"SiteTree\".\"Version\"
            AND \"SiteTree_versions\".\"ParentID\" = ?",
            array($this->owner->ParentID)
        );
    }
```

**Comment by tractorcow** [comment] 2016-07-21 06:22
Yes, this is quite a hard issue, unfortunately modifying past records can also have unintended side effects. It's not 100% clear what is the safest behaviour.

**Comment by tractorcow** [comment] 2016-07-21 06:23
Related to https://github.com/silverstripe/silverstripe-cms/issues/1544

**Comment by dhensby** [comment] 2016-07-21 12:26
Hmm, yes - if a CMS user wants to roll back to a version of a page, do they want to roll back just the content or do they want to roll back it's position in the site tree too?

I'd probably suggest a roll back in the history tab moving the page around would be unexpected behaviour on the CMS user's part. Having said this, what happens to the `ParentID`?

**Comment by tractorcow** [comment] 2016-08-09 02:34
Yeah that will get rolled back too.

**Comment by dhensby** [comment] 2016-08-11 14:54
So maybe we need a list of fields that are excluded from rollbacks and `ParentID` and `Sort` would be prime candidates

**Comment by chillu** [comment] 2019-02-01 02:09
Closing in favour of https://github.com/silverstripe/silverstripe-versioned/issues/180

**Closed by chillu** 2019-02-01 02:09 UTC
Labels: affects/v3, type/bug
