### ISSUE TITLE
Site settings not being written to DB

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/silverstripe-framework#8203] opened 2018-06-20 13:48 UTC
## Affected Version
4.2 beta

silverstripe/admin                 1.2.0-beta1 SilverStripe admin interface
silverstripe/asset-admin           1.2.0-beta1 Asset management for the SilverStripe CMS
silverstripe/assets                1.2.0-beta1 SilverStripe Assets component
silverstripe/campaign-admin        1.2.0-beta1 SilverStripe campaign admin interface
silverstripe/cms                   4.2.0-beta1 The SilverStripe Content Management System
silverstripe/config                1.0.5-beta1 SilverStripe configuration based on YAML and class statics
silverstripe/errorpage             1.2.0-beta1 ErrorPage component for SilverStripe CMS
silverstripe/framework             4.2.0-beta1 The SilverStripe framework
silverstripe/graphql               2.0.0-beta1 GraphQL server for SilverStripe models and other data
silverstripe/recipe-cms            4.2.0-beta1 SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-core           4.2.0-beta1 SilverStripe framework-only core recipe
silverstripe/recipe-plugin         1.3.0       Helper plugin to install SilverStripe recipes
silverstripe/reports               4.2.0-beta1 Reports module for SilverStripe CMS
silverstripe/siteconfig            4.2.0-beta1 Site wide settings administration.
silverstripe/vendor-plugin         1.3.3       Allows vendor modules to expose directories to the webroot
silverstripe/versioned             1.2.0-beta1 SilverStripe Versioned component

## Description
The site settings don't appear to be saving in the database.  No errors are thrown in the http response or the server logs.  The POST data seems to contain the correct information from the form.
The settings can be updated by changing values in the database directly - these are then read back into the settings page.

## Steps to Reproduce

Clean install of beta 1 with `composer create-project`
Go to settings, change the site name - click save.
Success message is shown
Refresh the settings page - content reverts to default

**Comment by kinglozzer** [comment] 2018-06-20 14:15
Closing as a duplicate of https://github.com/silverstripe/silverstripe-siteconfig/issues/98

**Closed by kinglozzer** 2018-06-20 14:15 UTC
