### ISSUE TITLE
EmailField RFC6531 regex validation to support international email standards

### ISSUE THREAD

**Issue by joshkosmala** [silverstripe/silverstripe-framework#4291] opened 2015-06-16 22:07 UTC
Hi Team,

RFC6531 allows unicode characters such as macrons to be legitimate characters in email addresses.

Currently EmailField supports RFC2822. There is a need in New Zealand, according to the Māori Language Act, to accept IDN email addresses. This will be a compliance issue in New Zealand for all government websites using the SilverStripe/CWP framework.

Initial research shows that "that will be a big task. The RFC 6531 is so complex. I think a RegExp which will validate to the RFC 6531 is impossible to write." however passing the "u" modifier to the current pcre expression https://github.com/silverstripe/silverstripe-framework/blob/3.1/forms/EmailField.php#L42 may be a solution.

PHP's filter_var does not support the rfc spec required.

I'm not strong at regex/pcre but if someone is willing to help with the expression I am happy to submit a pull requests and write some tests.

Nova

**Comment by tractorcow** [comment] 2015-06-17 03:13
Related to https://github.com/silverstripe/silverstripe-framework/issues/3057

My understanding is that this is simply not a solution that can be solved with _any_regex; The rules need to be encoded in PHP logic in order to comply with the necessary specification (be that 6531). 2822 is simply obsolete, in any case. :)

**Comment by tractorcow** [comment] 2015-06-17 03:15
I'm going to mark this as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/4291; Please don't take my closing of this issue as dismissal, simply ensuring all related issues are consolidated.

**Closed by tractorcow** 2015-06-17 03:15 UTC
