### ISSUE TITLE
Running Command Line in Live mode

### ISSUE THREAD

**Issue by iqmeckert** [silverstripe/silverstripe-framework#5745] opened 2016-06-29 21:00 UTC
I found when trying to run a cron job on a class that extends CliController, if Director::forceWWW() is set in _config.php and the environment is set to 'live', the cron job fails because the system tries to redirect to www. Director::forceWWW() should check for Director::is_cli() before redirecting. I was able to patch the system by adding
`if (Director::is_Cli()) Director::set_environment_type('dev');` just before Direcotr::forceWWW() in _config.php

**Comment by dhensby** [comment] 2016-06-29 21:29
Duplicate of / fixed by: https://github.com/silverstripe/silverstripe-framework/pull/4025

**Closed by dhensby** 2016-06-29 21:29 UTC
