### ISSUE TITLE
Docs still reference addErrorMessage, which was removed in SS4

### ISSUE THREAD

**Issue by Leapfrognz** [silverstripe/silverstripe-framework#9151] opened 2019-07-29 05:23 UTC
SilverStripe\Forms\Form->addErrorMessage() has been removed, but still referenced in the developer docs https://docs.silverstripe.org/en/4/developer_guides/forms/validation/

**Comment by robbieaverill** [comment] 2019-07-29 08:14
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8640

Pull requests welcome!

**Closed by robbieaverill** 2019-07-29 08:14 UTC
