### ISSUE TITLE
Chosen dropdown styles to align with new CMS form styles

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5669] opened 2016-06-08 23:13 UTC
Chosen dropdown styles to align with new CMS form styles, this only needs to happen if Chosen isn't replaced with a bootstrap React component first, see https://github.com/silverstripe/silverstripe-framework/issues/5670

**Comment by sminnee** [comment] 2016-09-28 21:39
Duplicate of #5670

**Closed** 2016-09-29 03:21 UTC
Labels: affects/v4, effort/hard, type/bug
