### ISSUE TITLE
Don't call deprecated code from non-deprecated code

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10503] opened 2022-09-11 22:52 UTC
Some of our deprecated methods and classes might still be called from code we do not intent to remove in CMS5. To facilitate upgrades, we should aim to not use deprecated code within CMS4. 

### Acceptance criteria
- [ ] Update code so that deprecation methods and classes are no longer being used where possible
- [ ] Scope is core modules

### Recommended approach
- Using the `4` branch and using CI, turn on deprecation warnings for silverstripe/installer and silverstripe/recipe-kitchen-sink and see what deprecation warnings bubble up
- Ensure that we have a reliable way to surface deprecation warnings from up-stream dependencies such as symfony and guzzle e.g. investigate using this https://symfony.com/doc/current/components/phpunit_bridge.html#usage

### Notes
- In some instances there will be no immediate migration path for code in `4` because the new API only exists in `5`

**Comment by maxime-rainville** [comment] 2022-09-11 22:54
Let's get #10500 done first before we scope this one.

**Comment by emteknetnz** [comment] 2022-10-12 23:33
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/10542

**Closed as completed by emteknetnz** 2022-10-12 23:33 UTC
Labels: type/enhancement, impact/medium, complexity/medium
