### ISSUE TITLE
Save button state with form validation

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#9701] opened 2020-09-20 19:49 UTC
# Save button state with form validation

I found an issue which comes from interaction of page edit form validation and save button state.

## Affected Version

`silverstripe/framework - 4.6.0`

## Description

Save button state is incorrect after form submission when a validation error occurs.

## Steps to Reproduce

1. Navigate to page edit form

![Screen Shot 2020-09-21 at 7 41 08 AM](https://user-images.githubusercontent.com/26395487/93720651-8faccf00-fbde-11ea-85d6-a2f3540b2707.png)

2. Make edits in the form - make sure that a form validation is in place (for example a required field).

![Screen Shot 2020-09-21 at 7 41 25 AM](https://user-images.githubusercontent.com/26395487/93720669-aa7f4380-fbde-11ea-8d17-323eef236e34.png)

3. Save the form.

![Screen Shot 2020-09-21 at 7 42 14 AM](https://user-images.githubusercontent.com/26395487/93720678-b2d77e80-fbde-11ea-8bdd-a9cb1c42f2c9.png)

### Expected result

Save button is green, it indicates unsaved changes. It should be the same as before the form submission as the change were not saved due to the validation error.

### Actual result

Save button is transparent with green border, it indicates save changes.

**Comment by bergice** [comment] 2020-09-21 04:36
Duplicate of https://github.com/silverstripe/silverstripe-admin/issues/1110

**Closed by bergice** 2020-09-21 04:36 UTC
