### ISSUE TITLE
BUG DataList:canFilterBy() returns false for relations in dot notation

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#5576] opened 2016-05-21 18:13 UTC
`DataList:canFilterBy()` only checks immediate database fields, not fields on relations which the ORM is quite capable of filtering on.

I noticed this when attempting to use a filter on a gridfield that included the Title from a has_one relation in the summary fields. No filter field is displayed for that column. If I amend `DataList:canFilterBy()` to simply return true, the filter field shows up and works perfectly.

@tractorcow you're probably the authority on this subject is this something you could take a look at?

I suspect `DataList:canSortBy()` has a similar limitation.

![silverstripe_-_edit_page](https://cloud.githubusercontent.com/assets/1079425/15450056/4b4ee322-1f45-11e6-93ca-dc627a782f88.png)

**Comment by tractorcow** [comment] 2016-06-07 06:01
Yep, it could be extended to properly do a check for a composite filter.

What you would want is a variant of DataQuery::applyRelation(), but rather than joining on the entire relation, it simply iterates over the relation with a return true / false at the end. It's a lot of duplicate code though, but it's probably possible.

I suggest a `mirror` method `checkRelation that follows the same logic.

You probably want to restrict filtering to linear relations though, since datalist doesn't do a good job of joining on one-to-many tables (risks duplication of rows). You'll understand once you look at the code. :P

**Comment by jonom** [comment] 2016-08-03 01:21
@tractorcow thanks for your suggestions, I think I may have come up with something at https://github.com/jonom/silverstripe-framework/commit/1d4a053e84e0caf22d2b5321ebf8af293a6cf75c. For now I've just updated the `canFilterBy()` method but I can break it out so it can be re-used, e.g. for `canSortBy()`.

Questions:

1. Where would be the best place (class) to put a function that checks that a field/relation dot notation string is valid for a class? `DataObject`?
2. I'm thinking that the same check should work for both filtering and sorting... but to your knowledge are there cases where you could filter by a relation but not sort by it, or vice versa?
3. Any glaring issues in the solution I came up with?

**Comment by tractorcow** [comment] 2016-08-10 06:22
Oh, by the way, @dhensby has been working on something like this. See https://github.com/silverstripe/silverstripe-framework/pull/5659

Also things are not going well and it's been hard getting tests and things to pass...

**Comment by tractorcow** [comment] 2016-08-10 06:25
1. DataQuery
2. I think it's probably the same rule, so canSortBy can be re-used.
3. Probably won't work out of the box. See 2. as a substitute.

**Comment by tractorcow** [comment] 2016-08-10 06:26
1. DataQuery
2. Actually I had a look at canSortBy, and it's wrong. We should update canSortBy and canFilterBy to piggy back off `applyRelation`.
3. It's getting there, but see @dhensby 's progress.

**Comment by jonom** [comment] 2016-08-11 04:41
Hmmm yes can see there is crossover in terms of walking the relations and we don't want to double up on that. As it stands so far #5659 wouldn't fix this issue but agree it wouldn't take much extra work to do so with that in place. The scope of this issue is a lot narrower though, I wouldn't be changing anything in the ORM, I'd only be changing some helper functions to more accurately report on what the ORM is capable of, by including related fields in the checks.

Anyway, I've dug in to this a bit more today and it seems like `canFilterBy` and `canSortBy` aren't essentially broken, as they don't claim to check related fields through dot notation. But by convention in SilverStripe it's probably fair to expect that they would. `GridFieldFilterHeader` seems to make this assumption which leads to grid field not allowing us to filter on relations, when it should. `GridFieldSortableHeader` doesn't make the same mistake, it includes a workaround to support relations. But think we may as well apply DRY principles here and remove that workaround.

Looking at Framework and CMS it looks like `canFilterBy` and `canSortBy` functions are only called in one place each --> `GridFieldFilterHeader` and `GridFieldSortableHeader`. So fixing these methods should be low risk but have a big impact for filtering in gridfields, which is a pretty important part of the CRUD functionality in SilverStripe.

My concern about building on @dhensby's work is time... if it will make it in to the 3 line soon then great, happy to wait for that and patch in a fix for this issue on top. But if it's a long way from being merge-able it would be a shame for that to block this issue from getting fixed.

Since filtering is pretty busted right now I would be inclined to patch this on 3.4.x. If you agree I'll open a PR for https://github.com/jonom/silverstripe-framework/commit/e1a49df15aab409678e30e29cb78a4c485b0e6b8 (updated)

**Comment by dhensby** [comment] 2016-08-11 13:09
@jonom I wouldn't wait for my fix - I'm almost at the point of saying we simply can't fix my problem in the 3 branch because it's looking like `ManyManyList` has been abstracted away from the actual relation too much

**Comment by jonom** [comment] 2016-08-11 18:49
Fixed with https://github.com/silverstripe/silverstripe-framework/commit/d4114b3dce73ffaf786af7ce76f2e1c6f1483d47

**Comment by lekoala** [comment] 2016-09-30 12:45
Hi!

Sorry to revive this, but I think the fix is not quite there yet, as the dot notation takes only into account relations and not potential formatting (for example, MyMoney.Nice). Here is what I had to to do:

        $model = singleton($this->dataClass);
        $parts = explode(".", $fieldName);

        // First validate the relationships
        $fieldName = array_shift($parts);

        // First, check field (and ignore the rest, which may be formatting)
        if ($model->hasDatabaseField($fieldName)) {
            return true;
        }

        // Nothing else to check
        if (empty($parts)) {
            return false;
        }

        // Then, check relations
        $relatedField = array_shift($parts);

        $relationClass = $model->getRelationClass($fieldName);
        if ($relationClass) {
            $relatedModel = singleton($relationClass);
            if(!$relatedModel->hasDatabaseField($relatedField)) {
                return false;
            }
            return true;
        }

        return false;

Although it's not perfect (hitting a field is ambiguous error due to joins). But at least formatted fields do work :-)

**Comment by dhensby** [comment] 2016-09-30 12:48
I've experienced this yesterday where the formatting notation causes errors.

**Comment by lekoala** [comment] 2016-09-30 13:14
Also, this seems related to this issue #4633 . The comment from @tractorcow helped me to lift the "ambiguous table" error by simply making sure I specify the table, instead of using the HasManyList for my relation (which does not specify the table.. I guess that could be fixed easily as well).

So for now, I'm back to ugly MyClass::get()->filter('MyClass.RelationID',$this->ID) instead of $this->MyRelationName();
but that's not too bad ^^ 

I also realized that allowing formatting notation in canFilterBy might not be the best idea, because it causes the query to fail anyway. So I also had to modify GridFielFilterHeader::getManipulatedData in this way

                $modelClass = $gridField->getModelClass();
                $model = singleton($modelClass);
		foreach($filterArguments as $columnName => $value ) {
                        $parts = explode(".", $columnName);
                        $fieldName = $parts[0];
                        if(count($parts) > 1 && $model->hasDatabaseField($fieldName)) {
                            $columnName = $fieldName;
                        }
			if($dataList->canFilterBy($columnName) && $value) {
				$dataListClone = $dataListClone->filter($columnName.':PartialMatch', $value);
			}
		}
		return $dataListClone;

I didn't test in depth though, but it seems to do the job for now on my project

I hope this helps, too busy right now to investigate properly and submit a PR

**Comment by dhensby** [comment] 2016-09-30 16:00
Yes, so devs probably shouldn't expected `Page::get()->canFilterBy('Title.XML');` to work but the problem is that `GridField` will take the `$summary_fields` definition and just literally check it. So if you have this:

```php
private static $summary_fields = array(
    'Title.XML' => 'Title',
);
```

Then we'll have this error.

@lekoala I like your solution, would you mind a PR to 3.4 branch and we can see what the test suite comes back with?

**Comment by lekoala** [comment] 2016-10-03 08:26
Hi there,

This is what I did. I kept the canFilterBy as is, because it may not be good to make it "lie" by returning true when passing Title.XML.

So instead, I realized that everything could be solved by some simple changes in the GridFieldFilterHeader class.

Here is the pull request
https://github.com/silverstripe/silverstripe-framework/pull/6130

It will not solve the potentiel "ambiguous table" problem, but at least it should improve the current situation.

**Comment by lekoala** [comment] 2016-10-12 10:39
I've been thinking a bit more about this, and I think my fix may not be needed in the first place. Actually, I believe it would make more sense to make the GridField apply some sort of configurable default formatting instead of relying on dot notation in summary_fields.
In one of my project, I end up cluttering all my summary_fields with formatting because I need the data to be formatted. It would make much more sense to have the GridField check the underlying DBField for proper formatting. It could also work very well for custom list (ArrayList or SQLSelect).
It could be something like "for each column, check if there is a field of this name. If so, create an instance of DBField for this column and use the default formatting".
Formatting should not be a afterthought, but considered right from the start.

**Comment by dhensby** [comment] 2016-10-16 13:34
I don't agree, I think fixing the header is the right place to start. it sounds more like an edge case where every field needs some default formatting that isn't the default from their data-types. That's something that a custom gridfieldconfig or extension could deal with.

**Comment by lekoala** [comment] 2016-10-17 14:03
A custom gridfield config is not so friendly, because you would need to redefine it everywhere (maybe if GridFieldDataColumns was injectable I could define a system wide setting). Or redefining a new FormScaffolder (but again, it's not injectable, so you have to overwrite it in every single model).
As for the default formatting, it's mainly due to numbers not being formatted by default by the GridField since it simply reads the value on the object. But for large amount, it's much nicer to have them with separators according to the user's locale.

But as you said, it's always nice to fix something :-)

**Comment by jonom** [comment] 2016-10-17 18:14
Sounds like we can all agree canFilterBy() and canSortBy() should fail for e.g. $SomeDate.Nice because you're working with the result of a method at that point, and the ORM isn't capable of sorting on values that can't be fetched directly from the database AFAIK.

So to have sorting available on a formatted value you'd either have to (a) sort on the unformatted value through the ORM and display the formatted variant, or (b) sort on the result of the method.

(a) would work well for things like $Date.Nice but might be unpredictable if using custom methods. (b) could be garbage for dates if it's only doing an alphabetical sort, but be more reliable for custom formatting methods. Might be a big performance problem as you'd have to fetch and loop through the whole set to do a sort.

(a) is achievable by using `GridFieldDataColumns::setFieldFormatting()` (I think) but it would be nice if we could separately specify what value should be used for sorting, and what should be used for formatting, just through the config layer, so form scaffolding can do the work for us.

Maybe could be incorporated in to the current static something like:
```php
private static $summary_fields = array(
    'Title' => array(
	    'Label' => 'Title',
	    'Formatting' => 'XML', # Method to call on field
    )
);
```

**Comment by lekoala** [comment] 2016-10-18 08:07
When I was working on the fix, I also had another idea I'd like to throw in. The main problem is that there is no good way to know if we are facing a dot notation that represent and relation or a formatting, therefore you need a lot of checks and such.

A really simple solution that would make the string notation more expressive is to make it clear by using some other kind of separator, for instance:

```php
private static $casting = array(
    'TotalSpent' => 'Currency',
);
private static $summary_fields = array(
    'Title' => 'Title',
    'Member.Title' => 'Member Name',
    'Amount:Nice' => 'Amount' // We use : instead of . for formatting notation
    'Member.TotalSpent:Nice' => 'Total Amount Spent' // TotalSpent() is a method, not a field. We need to check if it's something we can sort/filter on. Since there is not underlying DBField, we could use the "casting" array to allow formatting even on computed fields?
);
```

As an added bonus, I think it would be great to handle formatting on computed fields like TotalSpent in my example, otherwise you need to define formatting at two places (partly in summary_fields, partly in setFieldFormatting) or having a method that return formatted data (TotalSpentFormatted... I did that a lot :-) )

Having an array is nice because it's very flexible, but it's also very verbose. Would there by any use case where we have more than two parts? Otherwise we could have ['TheLabel', 'TheFormatting'].

**Comment by jonom** [comment] 2016-10-18 16:17
> A really simple solution that would make the string notation more expressive is to make it clear by using some other kind of separator

I like your idea @lekoala, that example isn't too different to the current structure but much easier to distinguish between relations and methods

**Comment by sminnee** [comment] 2017-05-10 08:43
Marked this as enhancement as it wasn't so much a bug as a feature we never built.

**Comment by dhensby** [comment] 2017-05-18 11:41
I think this will be fixed by #6130

**Comment by kinglozzer** [comment] 2018-06-06 15:48
Looks like the reason for re-opening this was resolved in #6130. I think any enhancements beyond that can be re-opened if someone wants to take ownership of them :)

**Closed by kinglozzer** 2018-06-06 15:48 UTC
Labels: affects/v3, affects/v4, change/minor, type/enhancement

**Comment by jonom** [comment] 2018-06-06 16:01
@lekoala I'd love to see an RFC for your `Field.RelationName:MethodName` idea so discussion can continue on it. I seem to often get tripped up when I want scaffolded interfaces to have formatted values, like the search form wants to search on the method instead of the field, and you may lose sorting ability if you use a method for formatting. Having a clear way to express what is a relation and what is a method could allow the scaffolding to be a lot smarter.

**Comment by lekoala** [comment] 2018-06-07 14:22
I fully agree on that. Having a clear way to declare things on DataObject could make scaffolding much easier and avoid a lot of coding.

What would you need for a RFC? do you have some kind of template?
