### ISSUE TITLE
`GridField` escapes HTML content inappropriately

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#11191] opened 2024-04-08 01:21 UTC
### Module version(s) affected

~~5.2 and~~ 5.x-dev , but not 5.1

### Description

CMS links are malformed. This looks like a regression related to CMS 5 upgrade (suspecting change of default behaviour).

* `"silverstripe/recipe-cms": "5.1.x-dev"` works as expected
* `"silverstripe/recipe-cms": "~5.x-dev"` **does not work as expected**

Looks like something was introduced after `5.1` that changes the behaviour.

### Expected behaviour

Links are clickable (regular HTML links).

![319796065-1014a9a8-f0ab-4b15-853e-0a4435cd7520](https://github.com/silverstripe/silverstripe-framework/assets/26395487/595ed529-08f5-41d8-915a-665726e6f4c6)

### Actual behaviour

Malformed HTML (encoded).

![319795341-a60cf515-8393-4dcb-96d4-680293961322](https://github.com/silverstripe/silverstripe-framework/assets/26395487/e3327fd5-07a4-417e-b0ac-f750b30723d3)

### How to reproduce

Add this `GridField` to a data object's edit form

```php
$config = GridFieldConfig_RecordViewer::create();
$columns = $config->getComponentByType(GridFieldDataColumns::class);
$gridField = GridField::create('Members', 'Members', Member::get(), $config);
$summaryColumns = $columns->getDisplayFields($gridField);
$summaryColumns['Email'] = [
    'title' => 'Email',
    'callback' => function (Member $member): ?DBField {
        $render = sprintf('<a href="mailto:%s">%s</a>', $member->Email, $member->Email);
        return DBField::create_field('HTMLVarchar', $render);
    }
];
$columns->setDisplayFields($summaryColumns);
```

### Possible Solution

I had a quick look at `GridFieldDataColumns` and `DBHTMLVarchar` but I couldn't find any obvious changes that would cause this.

I found a workaround for this (explicit cast):

```php
$config = GridFieldConfig_RecordViewer::create();
$columns = $config->getComponentByType(GridFieldDataColumns::class);
$gridField = GridField::create('Members', 'Members', Member::get(), $config);
$columns->setFieldCasting([
    'Email' => 'HTMLVarchar->RAW',
]);
$summaryColumns = $columns->getDisplayFields($gridField);
$summaryColumns['Email'] = [
    'title' => 'Email',
    'callback' => function (Member $member): ?DBField {
        $render = sprintf('<a href="mailto:%s">%s</a>', $member->Email, $member->Email);
        return $render;
    }
];
$columns->setDisplayFields($summaryColumns);
```

### Additional Context

Originally raised via https://github.com/tractorcow-farm/silverstripe-fluent/issues/839 but confirmed that this is not related to the Fluent module.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## OPTIONS

See https://github.com/silverstripe/silverstripe-framework/issues/11191#issuecomment-2060385424

## Acceptance criteria
- The offending PR is reverted.
- Open a follow up card - or repopen the original card - to discuss how to handle `Nice` method in CMS 6.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11222
- https://github.com/silverstripe/silverstripe-admin/pull/1737

**Comment by sunnysideup** [comment] 2024-04-17 04:58
This looks similar to https://github.com/silverstripe/silverstripe-framework/issues/11200. 

https://github.com/silverstripe/silverstripe-framework/blob/3d64eac1293a7522646be0fbae54d185a9ea3a72/src/Forms/GridField/GridFieldDataColumns.php#L268

Here is some relevant code (sorry images for speed):
![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/430c877d-26e2-4aa4-a434-87814c0da8ef)

**Comment by GuySartorelli** [comment] 2024-04-17 05:01
@sunnysideup Please do not include images of code. It not going to significantly slow you down to type:
````
```php
// ctrl+c the code, ctrl+v the code
```
````

**Comment by sunnysideup** [comment] 2024-04-17 05:12
Thank you for adding the link. I would recommend that you change the title of this ticket so it more accurately reflects the issue.  I searched for GridField, summary_fields, escape (and similar words).

**Comment by GuySartorelli** [comment] 2024-04-17 05:31
A git bisect shows that [this PR](https://github.com/silverstripe/silverstripe-framework/pull/11184) introduced the bug.

Thankfully that wasn't included in the 5.2.0 release (and I have confirmed locally that a fresh installation of Silverstripe CMS 5.2.0 is not affected).

The root cause is GridField trying to be a little too helpful in sanitising values if there's a `Nice()` method in `GridFieldDataColumns::castValue()`: https://github.com/silverstripe/silverstripe-framework/blob/3d64eac1293a7522646be0fbae54d185a9ea3a72/src/Forms/GridField/GridFieldDataColumns.php#L263-L265

Not sure what the best course of action is yet, but I'm leaning towards just reverting that PR. We have 6 months to make the decision before this finds its way to a stable release, so no rush.

Some options are:
1. Revert the PR, and don't introduce that method until CMS 6 (we could do that PR right away for CMS 6, and make sure we update `GridFieldDataColumns::castValue()` while we're at it)
2. Add an additional condition to `GridFieldDataColumns::castValue()` so that `DBHTMLText` and `DBHTMLVarchar` aren't sanitised - though if someone has some custom DB field that should not be sanitised, they will still experience a regression
3. Remove the call to `Nice()` in `GridFieldDataColumns::castValue()` - though that may result in a new unexpected regression in some cases

@lekoala since you implemented the linked PR I'd like to know if you have any thoughts about the best course of action here?

**Comment by sunnysideup** [comment] 2024-04-17 05:50
Great work @GuySartorelli  - thank you for all your patience with me and your expertise in getting it sorted.

**Comment by lekoala** [comment] 2024-04-17 07:12
@GuySartorelli oh i see, that is unexpected, and I was aware of that, but I had hoped the base Nice() method would actually make things simpler... not the opposite.
I think the "nice" method is supposed to be safe already, but at the same time, it seems from this line  $value = nl2br(Convert::raw2xml($value->Nice()) ?? '');  that the framework isn't always think it's the case...

Personally, I don't like the "method_exists" check, so I would be in favor of removing it, but the easy course of action is simply reverting my PR. Maybe it would be simpler to introduce a new base method for "NiceAndSafe" value, and take that as the new default

**Comment by maxime-rainville** [comment] 2024-04-28 22:38
We chatted about this in refinement. We concluded that it has too many moving parts to address specifically in CMS 5.

We'll revert the PR for now and start a discussion about what the ideal end state should be in CMS 6.

**Comment by sunnysideup** [comment] 2024-04-29 07:47
I am still seeing issues.  Is this correct? 
![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/17d2a407-7d64-4925-9f1a-1ab20819f870)

**Comment by GuySartorelli** [comment] 2024-04-29 08:17
The issue is still open because while we do have a plan, we haven't taken the time to enact the plan yet. If you are using the `5` branch (which is unstable, so I recommend not using it) you will still experience the bug this issue describes.

**Comment by GuySartorelli** [comment] 2024-05-06 05:07
Reopened https://github.com/silverstripe/silverstripe-framework/issues/11169 with new ACs for CMS 6 implementation of `Nice()`

**Comment by emteknetnz** [comment] 2024-05-07 02:55
Linked PRs have been merged

**Closed as completed by emteknetnz** 2024-05-07 02:55 UTC
Labels: impact/high, type/bug, affects/v5
