### ISSUE TITLE
Clear "remember me" cookies after trust level alterations

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-framework#8593] opened 2018-11-12 03:43 UTC
## Description

Currently when using the "Remember me" functionality while logging in we do not clear these known cookies when certain trust updates occur. Eg:
- Password change/reset
- MFA added (future scope)

In these cases it's a security precaution to ensure existing remembered devices are logged out.

/cc @clarkepaul

**Comment by chillu** [comment] 2019-02-25 01:11
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8694

**Closed by chillu** 2019-02-25 01:11 UTC
Labels: affects/v4, change/minor, effort/medium, impact/medium, type/enhancement
