### ISSUE TITLE
BUG UploadField hijacking return key

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-framework#3181] opened 2014-06-02 09:36 UTC
The bug was originally reported on stackoverflow and I can confirm it exists in the latest stable release of 3.1.

*"I have page/form in the SS 3 CMS that has an uploadfield on it - when I hit enter on other fields the popup to attach a file automatically shows, how can I stop this behaviour?"
http://stackoverflow.com/questions/23988952/silverstripe-3-uploadfield-stop-upload-popup-appearing-when-enter-is-pressed*

**To reproduce**
Create a Page/DataObject.
Add a TextField and UploadField
Focus on the TextField then press the return key.

If you haven't uploaded an image, it will trigger the modal to select a file.
If you have uploaded an image it will trigger the edit form of the upload field.

**Comment by pedro2555** [comment] 2015-03-05 21:54
@micmania1 Can you confirm this against 3.1?

I could not reproduce it. Maybe a CMS issue?

**Comment by patricknelson** [comment] 2015-10-05 06:55
My bug report at #1288 may be a duplicate.

**Comment by patricknelson** [comment] 2015-10-05 15:20
My bug report at https://github.com/silverstripe/silverstripe-cms/issues/1288 (corrected for CMS repository) may be a duplicate of this. However, work is needed on both repositories, it appears. Ping @kinglozzer

**Comment by patricknelson** [comment] 2015-10-05 15:37
@micmania1 @pedro2555 @kinglozzer 

Ok, this was a combined fix applied to `3.1` on the CMS and framework, since the general underlying issue affected both repositories. See below for legend.

* **CMS:**
  * Issue: https://github.com/silverstripe/silverstripe-cms/issues/1288 
  * PR: https://github.com/silverstripe/silverstripe-cms/pull/1290
* **Framework:**
  * Issue: https://github.com/silverstripe/silverstripe-framework/issues/3181 (you are here)
  * PR: https://github.com/silverstripe/silverstripe-framework/pull/4651

**Comment by patricknelson** [comment] 2015-10-07 00:06
@kinglozzer  This issue should be since it has now been resolved by https://github.com/silverstripe/silverstripe-framework/pull/4662 :+1: (duplicate of my CMS issue https://github.com/silverstripe/silverstripe-cms/issues/1288)

**Closed** 2015-10-07 03:47 UTC
Labels: change/patch, effort/easy, type/frontend
