### ISSUE TITLE
RFC: DataList::create() is case sensitive

### ISSUE THREAD

**Issue by pedro2555** [silverstripe/silverstripe-framework#3938] opened 2015-02-25 09:30 UTC
Creating a file `/mysite/code/MyObject.php` with:

    class MyObject extends DataObject { }

`/dev/build?flush` doesn't cry. And you can get a list of MyObjects using:

    DataList::create('MyObject');

But you can't with:

    DataList::create('myObject');

On Linux this is okish, on Windows it isn't. Overall it makes no sense, since URLs are not case sensitive no website framework should be.

Further more, I can create `/mysite/code/myObject.php` (along side with `MyObject`) with:

    class myObject extends DataObject { }

`/dev/build?flush` complains about having two files containing 'myObject' class and refuses to continue, which makes sense.

I haven't done any deep investigation but I would assume this is a fault on the database configuration, I'm using MySQL 5.5.40, and running `select * from SiteTree;` isn't the same as `select * from siteTree;`.

**Comment by pedro2555** [comment] 2015-02-25 14:18
Further more this appears to happen only with `DataObject`, extending `Page` and I can query for `Page`, `page` or `pAgE`.

**Comment by dhensby** [comment] 2015-02-25 17:09
In PHP classes and function names are case insensitive.

The framework *should* be mimicking this. Do you have any test cases that prove the issue? The class manifest usually lower strings everything for it's comparisons.

**Comment by pedro2555** [comment] 2015-02-25 17:33
Yes I do. As stated, create a `MyObject` class `/mysite/code/MyObject.php`

    class MyObject extends DataObject { }

Then try and create a `DataList` via `DataList::create()` with any case variant of `MyObject` that it is not `MyObject` and it will result in a server error.

For example, in `Page_Controller`:

    static $allowed_actions = array('Test');

    public function Test() {
        echo DataList::create('MyObject`)->count(); // Executes OK
        echo DataList::create('myobject'')->count(); // Results in server error
    }

Accessing `localhost/home/test` should have resulted in `00`, but instead it prints out `0` and then the 500 server error page.

And it is not a `count()` issue, running a foreach also throws a server error.

**Comment by pedro2555** [comment] 2015-02-25 17:37
If you can point out possible fail points in the source code, I might look into it and send a patch. So far I could not figure out where the problem may reside.

**Comment by dhensby** [comment] 2015-02-25 17:39
By test cases I meant actual unit tests that show the unexpected behaviour

**Comment by pedro2555** [comment] 2015-02-25 17:39
Sorry no. Not very familiar with testing in PHP.

**Comment by tractorcow** [comment] 2015-02-25 20:40
Case insensitivity is a large issue in the framework; It's implemented sparsely across several places, but not in any real consistent way.

It would likely be a lot of work to enforce case insensitivity across every element of the framework (config, injector, db schema, type casting, etc). It would probably be easier to force case sensitivity. :)

**Comment by tractorcow** [comment] 2015-02-25 20:42
Maybe liberal use of http://php.net/manual/en/function.array-change-key-case.php in key locations (pun intended) could resolve this issue?

**Comment by dhensby** [comment] 2015-02-26 09:50
@pedro2555 I assume the reason you've discovered this issue is because you're allowing the model type to be defined via the URL?

This is pretty bad practice as you'd allow anyone to query against any type in the system by manipulating the URL. At the very least you should be whitelisting the classes they can use and if you do that, there's no reason not to have that whitelisting perform mapping to the correct case of the class name (as a work around for now).

**Comment by pedro2555** [comment] 2015-02-26 10:27
Indeed, I am considering using the [restfulapi](https://github.com/colymba/silverstripe-restfulapi) module to provide a REST API for the website.

I would not call it a bad practice at all, that's the essence of REST. I would in turn be calling REST a bad practice. I'm happy to discuss that anywhere else, but in here is off topic.

The way that tests for "whitelisted" model types is with `singleton($className)` which works regardless of the capitalization used. The problem comes in the last bit, when we are sure the client is allowed access to the requested model type we pass it to `DataList::create($className)`.

I better workaround would be:

    -   $model = $request->param('ClassName');
    +   $model = singleton($request->param('ClassName'))->className;

But it is just it, a workaround for my specific use case.

**Comment by dhensby** [comment] 2015-02-26 17:52
> I would not call it a bad practice at all, that's the essence of REST. I would in turn be calling REST a bad practice. I'm happy to discuss that anywhere else, but in here is off topic.

What I'm saying is blindly accepting URL parameters as class names without sanitisation is bad practice. I'm not making any comment on REST.

> since URLs are not case sensitive no website framework should be

The [according to w3](http://www.w3.org/TR/WD-html40-970708/htmlweb.html) actually says URLs should be considered case sensitive... They're meant to relate to a directory structure the site sits in and on most OSs the directory structure is case sensitive so the URL would be too.

That's not to say this isn't a bug, but your premise is incorrect.

**Comment by pedro2555** [comment] 2015-02-26 18:55
> What I'm saying is blindly accepting URL parameters as class names without sanitisation is bad practice. I'm not making any comment on REST.

Sure, a bit off topic though.

> The according to w3 actually says URLs should be considered case sensitive... They're meant to relate to a directory structure the site sits in and on most OSs the directory structure is case sensitive so the URL would be too.

I wasn't aware of that, given by myth or otherwise I always thought the other way around. Funny enough even the [IETF website](https://www.ietf.org/) treats URLs as case insensitive.

But if I may, they are not meant to relate to directory structures and are OS independent. They dependent on their specification and on scheme specifications, for this case the HTTP specification. Still they are case sensitive, at least the major portion (HEX characters aren't, %2e = %2E).

For more in-depth [RFC3986 Uniform Resource Identifier (URI): Generic Syntax](http://tools.ietf.org/html/rfc3986) and [RFC7230 Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing](http://tools.ietf.org/html/rfc7230)

Oddly, this invalidates my bug but makes the problem worse for the framework.

**Comment by micmania1** [comment] 2015-02-27 03:36
Personally, I don't think its a useful addition and breeds inconsistency. If classes are being typed then they should be typed correctly. If they're coming from user input then they should be sanitised and mapped correctly, but I wouldn't consider the framework to be responsible for doing this.

**Comment by dhensby** [comment] 2015-02-28 14:52
@micmania1 unfortunately we deal with a language where class names and function names are not case sensitive and so, IMO, we should treat them in this way when we use string literals and other representations of class/function names

**Comment by micmania1** [comment] 2015-07-20 00:33
I retract my statement :)

**Comment by dhensby** [comment] 2015-07-30 23:14
this was fixed by #3949

**Closed by dhensby** 2015-07-30 23:14 UTC
