### ISSUE TITLE
SS3.5 missing float length params

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#6338] opened 2016-11-26 05:31 UTC
```php
class MapMarker extends DataObject {
    private static $db = [
        'Lat' => 'Float(11,7)',
        'Lng' => 'Float(11,7)',
    ];
}
```
Length won't be set at DB more than that if u will set it manually it will be reset by /dev/build
```
Field MapMarker.Lat: changed to float not null default '0' (from float(11,7) not null default '0.0000000')
Field MapMarker.Lng: changed to float not null default '0' (from float(11,7) not null default '0.0000000')
```

**Comment by tractorcow** [comment] 2016-11-28 04:56
Actually, 3.5 doesn't support setting of precision for float DB values (which is a shame!). The constructor only allows a default value to be set.

```
class Float extends DBField {
	public function __construct($name = null, $defaultVal = 0) {
		$this->defaultVal = is_float($defaultVal) ? $defaultVal : (float) 0;
		parent::__construct($name);
	}
}
```

I think the best we can do is to build in better support for this in 4.0, perhaps.

**Comment by tractorcow** [comment] 2016-11-28 04:58
If I change the `11,7` to `11.7` I see this output.

![image](https://cloud.githubusercontent.com/assets/936064/20656698/39b7f53c-b594-11e6-823f-451b594ce58c.png)

Closing as not a bug, sorry.

**Closed by tractorcow** 2016-11-28 04:58 UTC

**Comment by a2nt** [comment] 2016-11-28 17:50
It shall be length of number, but here's just a default number. And it's impossible to geocode location without numbers this long

**Comment by tractorcow** [comment] 2016-11-28 20:00
Can you use `Double` instead of `Float` in this case?

**Comment by a2nt** [comment] 2016-11-29 16:06
found a solution with DECIMAL(11,7) hopefully floats will be fixed in SS4

**Comment by tractorcow** [comment] 2016-11-29 20:57
Yes you can also use decimal. :) Good job.
