### ISSUE TITLE
Parameters passed to templates are always true, even when they are explicitly false

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-framework#3084] opened 2014-05-01 22:22 UTC
Consider parts of three files:

1. Page.php (Page_Controller)
```php		
public function Truthiness() {
	return true;
}

public function Falsiness() {
	return false;
}
```

2. Layout/Page.ss
```
<% include Truthiness No=$Falsiness, Yes=$Truthiness %>
```
3. Includes/Truthiness.ss
```
<%-- Truthiness.ss --%>
<p>
<% if $No  %>War is Peace, because "$No" is truthy.<% end_if %><br>
<% if $Yes %>Logic still works, because "$Yes" is truthy.<% end_if %>
</p>
```
The output of this is as follows:
```html
<p>
War is Peace, because "" is truthy.<br>
Logic still works, because "1" is truthy.
</p>
```

**Comment by oddnoc** [comment] 2015-06-11 04:55
Is there anything to be done about this?

**Comment by hafriedlander** [comment] 2015-06-11 05:18
This should be fixable. In fact, I'm not sure why it happens just from looking at the code. At https://github.com/silverstripe/silverstripe-framework/blob/3.1/view/SSViewer.php#L519 the boolean cast should make an empty string become false.

**Comment by tractorcow** [comment] 2015-06-11 05:34
Duplicate of https://github.com/silverstripe/silverstripe-framework/pull/4053

**Comment by tractorcow** [comment] 2015-06-11 05:40
Also, not trying to be dismissive... I just want to make sure we collect all of the various symptoms of the same issue in one place. :D I'm open to the idea that this might not be a duplicate, but if you think it is I'll re-open it.

**Comment by tractorcow** [comment] 2015-06-11 06:57
Ok, turns out it was the same problem, but a different part of the code caused it. :)

In any case it's fixed in #4053 . Let's leave this open until the other is merged also.

**Comment by oddnoc** [comment] 2015-06-11 18:33
Sounds great. FWIW, I can confirm the fix on my test case. Thanks!

**Comment by tractorcow** [comment] 2015-07-22 00:14
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4053

**Closed by tractorcow** 2015-07-22 00:14 UTC
Labels: change/patch
