### ISSUE TITLE
SiteTree::batch_permission_check() ending in infinite loop

### ISSUE THREAD

**Issue by oilee80** [silverstripe/silverstripe-framework#5876] opened 2016-08-08 16:10 UTC
If you have different stages that are children of each other (something that Hierarchy::validate() doesn't check for. e.g.

Live:

```
Page 1
  - Page 2
```

Stage:

```
Page 2
  - Page 1
```

Then reload the CMS, specifically the `/admin/pages/treeview` call will fail.

I can see this could be resolved in 2 ways either:
- `Hierarchy::validate()` checks if the Object is versioned
- `SiteTree::batch_permission_check()` doesn't check across the versions?

**Comment by tractorcow** [comment] 2016-08-09 04:45
I wonder if batch_permission_check should only check live stage if the draft version doesn't exist?

E.g. in your above scenario, Page 1 exists in both, so it should use the draft version only. It would ignore the parentID of the live "page 1" since we have a more current draft copy. How does that sound?

**Comment by oilee80** [comment] 2016-08-09 07:27
Hi @tractorcow ,
If I remove "Live" from the staging loop in `SiteTree::batch_permission_check()` then the process works fine. Do we need to check both Live & Stage? Surely we just need to check the current Stage.

**Comment by flamerohr** [comment] 2016-08-09 10:05
@tractorcow that's what we ended up doing with advanced workflow, use Draft as the source of truth until there isn't a Draft then use Live.

**Comment by oilee80** [comment] 2016-08-09 10:16
Ah but if the user is browsing the Live site then it should just be checking the Live stage. e.g. for "Who 
can view this page"

**Comment by dhensby** [comment] 2016-08-09 10:53
When is the CMS ever not in Draft mode?

**Comment by flamerohr** [comment] 2016-08-09 10:59
@oilee80 good point

@dhensby when you use the option "Cancel draft changes" which literally deletes the Draft version

**Comment by dhensby** [comment] 2016-08-09 15:06
@flamerohr, but you'r still in draft reading mode, just the latest draft == latest live

**Comment by oilee80** [comment] 2016-08-10 07:03
@dhensby, but as I said above, when you're viewing the site in "Live" this code is still checked. So just checking the current Stage is what you're wanting?

**Comment by dhensby** [comment] 2016-08-11 13:30
I'm thinking @flamerohr had it right with:

> use Draft as the source of truth until there isn't a Draft then use Live.

**Comment by tractorcow** [comment] 2017-05-04 00:09
@dhensby could we look at fixing this for 3.6?

**Comment by tractorcow** [comment] 2017-05-04 02:02
This is how I'm looking to fix this in 4.x. https://gist.github.com/tractorcow/540a3056cfce5d45f0d5c680372dad0c

**Comment by tractorcow** [comment] 2017-05-04 06:14
I can confirm the above fixes my issue. you'll need a slightly tweaked version for 3.x.

See my unit tests at https://github.com/open-sausages/silverstripe-framework/blob/ca1e6f435ad4ec42df0487265098a3d47c9ccf63/tests/php/Security/InheritedPermissionsTest.php#L233-L267

**Comment by tractorcow** [comment] 2017-05-18 05:03
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/776

**Closed** 2017-05-18 05:03 UTC
Labels: affects/v3, change/patch, type/bug
