### ISSUE TITLE
Following lost password link a second time throws exception

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#7866] opened 2018-02-13 20:15 UTC
## Affected Version

4.x-dev (probably 4.0.x too)

## Description

When I follow the link to reset my password from a "forgot my password" email, reset it, log out and follow the link in my email again I get this exception:

```
[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'forTemplate' does not exist on 'SilverStripe\View\ArrayData'
GET /Security/changepassword?m=2&t=76e780df6db70e2d7f5416e85af0973b7d1256e88ff374afbe8b4853706e04262707451bea157bb92c5f74c8671e5d929f1fb49331ef9b2706246aa24fdca043
```

Full stack trace: https://gist.github.com/robbieaverill/c3ba17e20a445a444d48ec22ef7f9227

## Steps to Reproduce

* Create a user account with your email address
* Log out of the CMS
* Click on "forgot my password"
* Enter your email address and submit
* Follow the "reset your password" link in the email you receive 
* Enter a new password and submit
* Log out
* Follow the "reset your password" link in the email again

**Comment by HARVS1789UK** [comment] 2018-03-07 11:25
@robbieaverill I can confirm that I am also seeing this issue in v 4.1.0-rc2 when following a framework generated password reset e-mail link.

What is more of an issue for me, is that I see this error the **first** time I follow a password reset link which is generated by my codebase!

I generate a password reset link on creation of a new member and e-mail them this link in an 'notification of new account creation' e-mail (so they can set themselves a password for, as they see it, the first time). I get this error when following that link for the first time, meaning users cannot set their own passwords.

Have you found any causes of this yet? I need to find a fix before this project can go live :-(

**Comment by dhensby** [comment] 2018-03-07 11:27
@HARVS1789UK have you done any debugging around this issue?

**Comment by HARVS1789UK** [comment] 2018-03-07 11:51
@dhensby - Yes some, I have taken note of the state of the Member record in the DB in these 3 scenarios.

### Framework Reset - Pre Reset
**TempIDHash**: null
**TempIDExpired**: null
**AutoLoginHash**: $2y$10$ae12a0a21f4ffda80dff2ud1HrolzkPdw.f.ARXLcZx13uO2/utQ6
**AutoLoginExpired**: 2018-03-09 11:38:44
**Note**: HTTP 302 redirect to strip query params

### Framework Reset - Post Reset
**TempIDHash**: 7ecf0cd09b96ee601c0dda361c20a99b2c4b2a5d
**TempIDExpired**: 2018-03-10 11:42:21
**AutoLoginHash**: null
**AutoLoginExpired**: 2018-03-09 11:38:44
**Note**: HTTP 500 - ArrayData forTemplate issue 

### Custom Code Reset - Pre Reset
**TempIDHash**: null
**TempIDExpired**: null
**AutoLoginHash**: null
**AutoLoginExpired**: 2018-03-14 11:45:47 (expected as I set a 7 day validity on my link)
**Note**: HTTP 500 - ArrayData forTemplate issue 

I notice that both instances where this error is thrown, AutoLoginHash is null, so I expect that it one of the root causes of the issue.

I need to work out why my custom code to create and send the reset link is not setting the AutoLoginHash in the database (it's clearly creating it because it is appended to the link in the query params), that will hopefully solve my issue about it happening on first view, but won't solve @robbieaverill 's issue regarding the second load of this page.

**Comment by HARVS1789UK** [comment] 2018-03-07 12:29
I am pretty sure that this is the culprit in both the above scenarios: (from ChangePasswordHandler.php -> changepassword() around line 118)

```php
        // Show a friendly message saying the login token has expired
        if ($token !== null && $member && !$member->validateAutoLoginToken($token)) {
            $message = [
                'Content' => DBField::create_field(
                    'HTMLFragment',
                    _t(
                        'SilverStripe\\Security\\Security.NOTERESETLINKINVALID',
                        '<p>The password reset link is invalid or expired.</p>'
                        . '<p>You can request a new one <a href="{link1}">here</a> or change your password after'
                        . ' you <a href="{link2}">logged in</a>.</p>',
                        [
                            'link1' => $this->link('lostpassword'),
                            'link2' => $this->link('login')
                        ]
                    )
                )
            ];

            return [
                'Content' => $message,
            ];
        }
```

I have never seen DBField objects (or HTMLFragment?) be passed back to the template to be rendered directly before, but it seemingly works in the other scenarios a few lines above, like:

```php
        $session = $this->getRequest()->getSession();
        if ($session->get('AutoLoginHash')) {
            $message = DBField::create_field(
                'HTMLFragment',
                '<p>' . _t(
                    'SilverStripe\\Security\\Security.ENTERNEWPASSWORD',
                    'Please enter a new password.'
                ) . '</p>'
            );

            // Subsequent request after the "first load with hash" (see previous if clause).
            return [
                'Content' => $message,
                'Form'    => $this->changePasswordForm()
            ];
        }
```

However, something about the first snippet seemingly means that ArrayData is returned to the template instead (perhaps the use of the 3rd parameter of the _t() method, to insert values a bit like sprintf() ?).

If I replace it with ```php $message = "I found the culprit!"; ``` it resolves the issue!

Any thoughts @dhensby or @robbieaverill

**Comment by kinglozzer** [comment] 2018-03-07 12:32
@HARVS1789UK I would guess that it should be `$message = DBField::create_field(` rather than `$message = ['Content' => DBField::create_field(`. Looks like we’ve doubled-up on our arrays 😁

**Comment by HARVS1789UK** [comment] 2018-03-07 12:34
@kinglozzer Good spot, I hadn't noticed that part. I am just testing and confirming now.

**Comment by kinglozzer** [comment] 2018-03-07 15:15
Closed in https://github.com/silverstripe/silverstripe-framework/pull/7917

**Closed by kinglozzer** 2018-03-07 15:15 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug
