### ISSUE TITLE
CMS History panel styling regressions

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5355] opened 2016-04-20 03:45 UTC
![image](https://cloud.githubusercontent.com/assets/111025/14662904/d4f99710-070e-11e6-9938-335acd132bfb.png)

/cc @clarkepaul

**Comment by chillu** [comment] 2016-05-08 19:39
See https://github.com/silverstripe/silverstripe-cms/issues/1478

**Comment by clarkepaul** [comment] 2016-05-09 02:39
@chillu can you reopen this issue rather than having it in the CMS repo as the issues are caused by Bootstrap being introduced but not having Bootstrap markup, so these issues will be generic across every checkbox and not just on the history page (eg the page/settings tab as well).

**Comment by tractorcow** [comment] 2016-05-20 02:51
I've re-opened this for now. :D

@clarkepaul can you let me know when this is fixed.

**Comment by clarkepaul** [comment] 2016-05-20 03:22
Should be fixed with https://github.com/silverstripe/silverstripe-framework/pull/5476

**Comment by dhensby** [comment] 2016-05-20 16:36
PR merged

**Closed by dhensby** 2016-05-20 16:36 UTC
Labels: type/frontend
