### ISSUE TITLE
Install process does not check modrewrite

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7561] opened 2017-11-06 21:57 UTC
Using composer to create-project install SS IV when mod rewrite is disabled does not produce an error

**Comment by tractorcow** [comment] 2017-11-08 23:19
The install.php does produce an error if you have mod_rewrite disabled; Can you please confirm you've run this and whether it's produced the error you expected?

It's not possible to run this check at composer time, since the apache environment isn't enabled. We'll need to defer this check until browse time.

With mod_rewrite disabled, what is the current experience you've noticed and what would you expect to happen, when you first attempt to view the website in your browser?

Ideally it would redirect the user to installer.php if it exists.

**Comment by tractorcow** [comment] 2017-11-08 23:20
For reference:

![image](https://user-images.githubusercontent.com/936064/32580046-698aefde-c548-11e7-964d-a4eddc71fb5e.png)

**Comment by worikgh** [comment] 2017-11-09 02:14
Confirmed it.  After the following commands I wrote a .env then when navigating to IV I get a 404.

$ sudo sed -i 's/RewriteEngine/#RewriteEngine/' /etc/apache2/sites-enabled/000-default.conf                              
$ sudo a2dismod rewrite                                                                   
Module rewrite disabled.       
To activate the new configuration, you need to run:            
  systemctl restart apache2    
$ sudo systemctl restart apache2
$ ./composer.phar -q create-project silverstripe/installer IV                             

install.php does not come into it

**Comment by tractorcow** [comment] 2017-11-09 04:52
How about something like this?

```
<IfModule !mod_rewrite.c>
  Error "mod_rewrite is required!"
</IfModule>
```

**Comment by worikgh** [comment] 2017-11-09 05:56
I am not qualified to say.  I do not know how rewrites work on different servers.   I have not learned .htaccess magic

That snippet looks like it is for apache.  How would it work for IIS?

**Comment by tractorcow** [comment] 2017-11-09 07:20
We would need a separate rule for web.config

**Comment by dhensby** [comment] 2017-11-22 12:36
I'm closing this as "not a bug" - as @tractorcow has pointed out, composer is for installing PHP packages/dependencies and cannot make assertions about apache/IIS set-up.

**Closed by dhensby** 2017-11-22 12:36 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug
