### ISSUE TITLE
BUG: DatetimeField Styles in new Filter Panel (3.3)

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#5002] opened 2016-01-29 16:14 UTC
Looks like DatetimeField has some style issues in the Filter panel for 3.3.0 RC1, seems they don't get the same styles as a normal text field do. See attached screenshot.
![ss33-filter-panel-style-bug](https://cloud.githubusercontent.com/assets/1391558/12680739/cba62d2c-c681-11e5-9558-1d97006dccc8.jpg)

**Comment by tractorcow** [comment] 2016-02-03 00:09
This is what I see on the assetadmin area.

![image](https://cloud.githubusercontent.com/assets/936064/12768794/2752e6ee-ca77-11e5-9884-3d940481af41.png)

It looks like the date field inputs are getting their styles from the `.field input.text` selector in _forms.scss. What classes are in the HTML in your search area?

**Comment by tractorcow** [comment] 2016-02-03 00:10
![image](https://cloud.githubusercontent.com/assets/936064/12768829/85f155b4-ca77-11e5-9bcf-92d663fc1c39.png)

**Comment by UndefinedOffset** [comment] 2016-02-03 13:46
@tractorcow looks like those two fields are a grouped DateField, what I'm using is a DatetimeField which looks like the attached in the dom. Which actually also like there's some broken html there, a few unescaped double quotes it looks like on the holder div. But adjusting that doesn't seem to fix the styles.
![datetime-field-html](https://cloud.githubusercontent.com/assets/1391558/12783995/f686b7a0-ca5a-11e5-92fc-c4e8f99a2e0a.jpg)

**Comment by tractorcow** [comment] 2016-02-03 20:47
Oh, those unescaped quotes look dangerous... how likely do you think that's the cause of the issue?

**Comment by UndefinedOffset** [comment] 2016-02-03 20:58
Didn't seem to be related if i doctored the dom to be valid html through dev tools it seemed to still be broken. So it appears to be a separate issue, that also appears to be present in 3.2 with the same site code. I'm poking around to try and find out how or where that particular issue is coming from.

**Comment by UndefinedOffset** [comment] 2016-02-04 13:52
@tractorcow I played around with the styles a bit and managed to come up with a solution that fixes the issue I'm seeing. Seems as though the styles for ``.fieldgroup-field`` are being applied to the input's inside of the datetime field since they have that class. So one solution would be to reset some of those back to what they are on other fields. As for the odd alignment of them removing the float left on the first label in the datetime field cleans that up.

```css
.cms-content-filters .field.datetime > label.left {
    float: none;
}

.cms-content-filters .field input.fieldgroup-field {
    width: 96%;
    padding: 7px;
}
```
![Fixed Styles](https://cloud.githubusercontent.com/assets/1391558/12816814/effbf63c-cb24-11e5-97a5-a7df6b5d1a79.png)

**Comment by tractorcow** [comment] 2016-02-04 21:00
Oh excellent.

Your fix is probably ok. Want to raise a PR?

**Comment by UndefinedOffset** [comment] 2016-02-04 21:17
I assume the compass files must be modified for screen.css? Want me to recompile it as part of the pull or just adjust the compass source as needed?

**Comment by dhensby** [comment] 2016-02-04 21:34
@UndefinedOffset you'll need to edit the scss and recompile then commit all changes

**Comment by UndefinedOffset** [comment] 2016-02-05 14:56
@dhensby @tractorcow pull submitted :)

**Comment by kinglozzer** [comment] 2016-02-05 15:45
Closed via https://github.com/silverstripe/silverstripe-framework/commit/cb39c41872df7c4af4c478bdf649f5045feaa956. Nice work @UndefinedOffset :+1:

**Closed by kinglozzer** 2016-02-05 15:45 UTC
