### ISSUE TITLE
i18nTextCollectorTask ignores template strings that contain a comment.

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-framework#5075] opened 2016-02-22 11:03 UTC
According to the documentation, translations within templates can be annotated with a comment like so:
```
<%t SearchResults.NoResult "There are no results matching your query." is "A message displayed to users when the search produces no results." %>
```
Source: https://docs.silverstripe.org/en/3.3/developer_guides/i18n/

The `i18nTextCollectorTask` silently ignores these translations though (eg. the translation is completely missing from the generated yml file).

This has been observed with `3.3.0-rc3` and `3.2.1`

**Comment by tractorcow** [comment] 2016-02-22 11:26
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/4965

I think it's worse than that... I've noticed textcollector putting the translations in completely incorrect locations (making new modules, in worst case example).

**Closed by tractorcow** 2016-02-22 11:26 UTC
