### ISSUE TITLE
Add environment variables for mysqli connection params

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10787] opened 2023-05-22 00:38 UTC
Follow on from https://github.com/silverstripe/silverstripe-framework/issues/8871 where the [PR](https://github.com/silverstripe/silverstripe-framework/pull/10784) testing instruction required overriding some code to add in params for `$socket` and `$flags` for [mysqli::real_connect()](https://www.php.net/manual/en/mysqli.real-connect.php)

We should allow these two params to be set via environment similar whose names match the existing database connection scheme e.g. `SS_DATABASE_*`

**Comment by wilr** [comment] 2024-09-14 19:17
Closing this as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/9394

**Closed as completed by wilr** 2024-09-14 19:17 UTC
Labels: type/enhancement, impact/low, affects/v4, affects/v5
