### ISSUE TITLE
TextField default value should throw warning when used in getCMSFields()

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-framework#8677] opened 2018-12-17 03:10 UTC
## Affected Version
SS 4.3.0

## Description

When creating a new TextField in the CMS, the third argument seems to be ignored in favour of the database value. I would expect it to display the literal string of text I supplied as the third value. The impact means I can't pre-populate the value of the TextField beforehand. This works on 4.2.1, but does not work on 4.3.0/

## Steps to Reproduce

Add the following to any Page type:
```
    private static $db = [
        'AuthorName' => 'Varchar(80)'
    ];

    public function getCMSFields() {
        $fields = parent::getCMSFields();

        $fields->addFieldsToTab('Root.Main',
            TextField::create('AuthorName', 'Author (Optional)', 'asdfadsfadsf')
        );
        return $fields;
    }
```

Change "asdfadsfadsf" to anything else and publish the page. The published value will be saved to the database, and will be displayed in place of the supplied value.

**Comment by ScopeyNZ** [comment] 2018-12-17 03:38
Hmmn I can reproduce this before a `/dev/build` but after then it just uses the value from the DataObject, including displaying an empty field for `null`.

That seems like the expected functionality to me though?

**Comment by elliot-sawyer** [comment] 2018-12-17 03:46
I'm trying to prepopulate the field with the name of the currently logged in user as a free text field, so the user can change the name if they want ("Jonathan" might be changed to "John" for example). 

Let's say I have a TextField in the CMS, with "Jonathan Smith" pre-filled in as the name. I've hard-coded it here for the sake of argument, but it could be a variable with any pre-determined value:
`TextField::create('AuthorName', 'Author (optional)', 'Jonathan Smith')`

Mr. Smith changes the value of the field to "John Smith" and publishes the page.

Because the third argument of TextField is hardcoded to "Jonathan Smith", I would expect that value to appear in place of the database value "John Smith". If I set the 3rd argument of the TextField to any literal value, the DB value should not be shown.  

I am pre-populating the field to avoid having an empty field, unless the user elects to remove it.

**Comment by ScopeyNZ** [comment] 2018-12-17 03:54
I see. I've not tested it against 4.2.1 but as described seems like a pretty high impact bug. Thanks for the report.

**Comment by kinglozzer** [comment] 2018-12-18 10:07
As far as I’m aware, this is “expected” behaviour in that the form field values aren’t populated until _after_ `getCMSFields()` is run. It might be possible to change that behaviour, but it’d be a breaking change IMO 

>Let's say I have a TextField in the CMS, with "Jonathan Smith" pre-filled in as the name

Isn’t `private static $defaults` (or `public function populateDefaults()` if it needs to be dynamic) intended for this kind of functionality?

**Comment by kinglozzer** [comment] 2018-12-20 09:20
I’ve just tested on `4.2.1` and the value passed to `__construct()` was ignored, same as `4.3.0`.

```php
TextField::create('Foo', 'Foo', 'test')`
```

Was one of the sites using a `DataObject` rather than a `Page`? I wonder if DataObjects may behave differently, as pages are written to the database as soon as you click the add page button.

`populateDefaults()` should still work for that use case, I’ve just tested the following:

```php
public function populateDefaults()
{
    $this-> AuthorName = Security::getCurrentUser()->Name;
    return parent::populateDefaults();
}
```

**Comment by robbieaverill** [comment] 2018-12-30 14:57
Perhaps someone would like to create a unit test proving the bug, so we can show it breaking in the Travis matrix over different core versions?

**Comment by sminnee** [comment] 2019-03-08 06:38
I feel like what @elliot-sawyer is trying to achieve here is better achieved with ORM-level `$defaults`, as @kinglozzer mentioned.

This is a bit confusing, but isn't really a bug. The best fix I could recommend is to throw a warning if FormField default values are set within getCMSFields().

**Comment by robbieaverill** [comment] 2019-03-08 07:36
I agree, the param is for the value of the form field not a default value. Closing since 3x against

**Closed by robbieaverill** 2019-03-08 07:36 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/bug
