### ISSUE TITLE
make cacheTableNames more persistent and simpler

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8695] opened 2019-01-07 10:57 UTC
## Affected Version

SS4+

See: 
https://github.com/silverstripe/silverstripe-framework/blob/74698af402e0d8a4efe90d2db3591fb20b5ecf03/src/ORM/DataObjectSchema.php#L284-L305

## Description

Whenever we do any DB calls, ALL the dataobject tables are put into a cache. This will take a bit of time and seems a bit inefficient (this data stays the same until code is changed).  Could this cache persist between requests or can the option be provided for it to be saved somewhere (e.g. yml file).

*Secondly*

I would change the system so that the database name is always the short class name (e.g. `DataObject` rather than `Silverstripe_ORM_DataObject`) with the ability to set table names to something else ONLY when: 

a. i.e. if there are conflicts - it will revert to fully qualified name https://github.com/silverstripe/silverstripe-framework/blob/74698af402e0d8a4efe90d2db3591fb20b5ecf03/src/ORM/DataObjectSchema.php#L298-L303) will use full name instead of throwing error

b. private static  `table_name` is set.

**Comment by robbieaverill** [comment] 2019-01-07 11:14
WRT the first point, we could probably make it cache the list on flush using a SS cache entry rather than a memory cache

The second point is by design, I think it’d need an RFC if you would like to change it for SilverStripe 5 :-)

**Comment by kinglozzer** [comment] 2019-01-07 11:33
Omitting a `$table_name` setting is deprecated, so it will be required in SS5 - we won’t automatically build table names any more :)

I think there’s a ticket hanging around somewhere about caching everything in DataObjectSchema... I just can’t find it 😝

**Comment by maxime-rainville** [comment] 2019-01-10 23:25
Just profile this bit of the code and the actual time spent on this spent on it is crazy small.

Isn't the manifest kind-of cached any way?

**Comment by maxime-rainville** [comment] 2019-01-11 11:20
Closing as it's already cached by some lower level call.

**Closed by maxime-rainville** 2019-01-11 11:20 UTC
Labels: affects/v4, effort/easy, impact/low, type/enhancement
