### ISSUE TITLE
DBBoolean scaffoldSearchField has no empty option

### ISSUE THREAD

**Issue by TheBnl** [silverstripe/silverstripe-framework#8708] opened 2019-01-09 12:59 UTC
## Affected Version

4.3

## Description

I noticed that the DBBooleans scaffolded search field shows no empty option anymore. It only shows "yes" and "no". This is because the 0 value from the option list acts as an empty value.

![schermafbeelding 2019-01-09 om 13 45 54](https://user-images.githubusercontent.com/1334195/50900281-0018ba00-1415-11e9-80e8-bec7deb91c74.png)
_I extended the search box a bit, thus the different style_

## Steps to Reproduce

Add a boolean as a searchable field
```php
private static $searchable_fields = [
        'MyBooleanValue'
];
```
This is probably because of the option with value `0`. This gets used as the "empty" value instead.

```php
public function scaffoldSearchField($title = null)
{
    $anyText = _t('SilverStripe\\ORM\\FieldType\\DBBoolean.ANY', 'Any');
    $source = array(
        1 => _t('SilverStripe\\ORM\\FieldType\\DBBoolean.YESANSWER', 'Yes'),
        0 => _t('SilverStripe\\ORM\\FieldType\\DBBoolean.NOANSWER', 'No')
    );
      
    $field = new DropdownField($this->name, $title, $source);
    $field->setEmptyString("($anyText)");
    return $field;
}
```
When i add the option manually with a `null` value the empty selection is shown.
```php
public function scaffoldSearchField($title = null)
{
    $anyText = _t('SilverStripe\\ORM\\FieldType\\DBBoolean.ANY', 'Any');
    $source = array(
        null => _t('SilverStripe\\ORM\\FieldType\\DBBoolean.ANY', 'Any'),
        1 => _t('SilverStripe\\ORM\\FieldType\\DBBoolean.YESANSWER', 'Yes'),
        0 => _t('SilverStripe\\ORM\\FieldType\\DBBoolean.NOANSWER', 'No')
    );
      
    $field = new DropdownField($this->name, $title, $source);
    $field->setEmptyString("($anyText)");
    return $field;
}
```
![schermafbeelding 2019-01-09 om 13 57 28](https://user-images.githubusercontent.com/1334195/50900808-8f729d00-1416-11e9-94f5-4c72ed2454f8.png)

But i don't think that is a real fix though.. 😉

**Comment by robbieaverill** [comment] 2019-01-09 13:02
Thanks for reporting this issue! Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8691

**Closed by robbieaverill** 2019-01-09 13:02 UTC

**Comment by TheBnl** [comment] 2019-01-09 13:06
Ah missed that one, thanks for looking into it!

**Comment by sunnysideup** [comment] 2021-03-23 03:44
This is still an issue. Can this be fixed ASAP?
