### ISSUE TITLE
GridFieldConfig_RelationEditor no longer unlinks records, archives object instead

### ISSUE THREAD

**Issue by ChrissiQ** [silverstripe/silverstripe-framework#9023] opened 2019-05-29 01:09 UTC
## Affected Version

4.4.0-rc1

## Description

Using `GridFieldConfig_RelationEditor`, previously an option was available to "unlink" the relation without otherwise altering the related object - certainly not archiving it.

In this version of SilverStripe, when I create a `GridField` with  ` GridFieldConfig_RelationEditor`, records appear with the `...` icon on the right and options available are 'Edit' and 'Archive'.  There is no 'Unlink' option available.

## Sample Code to reproduce

```
use SilverStripe\Forms\GridField\GridField;
use SilverStripe\Forms\GridField\GridFieldAddNewButton;

class ResourcesHolder extends \Page
{
    private static $table_name = 'ResourcesHolderPage';

    private static $has_many = [
        'PopularResources' => ResourcesPage::class,
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->addFieldsToTab('Root.Main', [
            GridField::create(
                'PopularResources',
                'Popular Resources',
                $this->PopularResources(),
                $gridFieldConfig = GridFieldConfig_RelationEditor::create()
            ),
        ]);
        return $fields;
```

## Result (Screenshot)

![Screen Shot 2019-05-28 at 7 02 31 PM](https://user-images.githubusercontent.com/1127719/58522085-09b07d80-817c-11e9-961d-0bb83ab67fa5.png)

**Comment by robbieaverill** [comment] 2019-05-29 01:46
Thanks for raising this issue. Closing as a duplicate of https://github.com/silverstripe/silverstripe-versioned/issues/200.

**Closed by robbieaverill** 2019-05-29 01:46 UTC

**Comment by ChrissiQ** [comment] 2019-05-29 15:57
So it's a problem with `Versioned` for sure, @robbieaverill ?  If I were to create a relation between two non-versioned objects, would the 'unlink' functionality come back?

**Comment by robbieaverill** [comment] 2019-05-29 21:01
It should be fine with unversioned many many or has manys
