### ISSUE TITLE
Remove Link and File Tracking until they make sense to user. 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8497] opened 2018-10-18 07:51 UTC
## Affected Version

Latest stable version of SS

## Description

When I install the latest version of SS I now get some weird stuff about Link and File Tracking. I am sure this is really important but it is completely meaningless to the Content Editor. I have created one site where I have simply hidden the two tabs on the 10 Models or so.  

I would recommend we remove their visibility from the CMS until someone has looked at this from a user's perspective. What do they do, what are they for, why do I need them, etc... etc...

**Comment by robbieaverill** [comment] 2018-10-18 07:54
There's been a lot of work in this area over the last few months. I think it's been disabled for models like members etc, can you please pull in the latest 4.2.x-dev branch and see if that is any better?

**Comment by robbieaverill** [comment] 2018-10-18 07:58
Thanks @ScopeyNZ. Closing as a duplicate of those

**Closed by robbieaverill** 2018-10-18 07:58 UTC

**Comment by sunnysideup** [comment] 2018-10-18 08:04
Thank you for your quick reply. Great to see that it has been fixed. Weird how something as major as that gets released. I mean, so much of the SS work is completely brilliant and all that, but it seems we sometimes forget the end goal: the user experience.

**Comment by robbieaverill** [comment] 2018-10-18 08:13
Thanks @sunnysideup. There's always a lot going on in the core development, and sometimes things slip through unnoticed for some time.

**Comment by sunnysideup** [comment] 2018-10-18 08:20
Totally, I understand that better than anyone else.  I guess what I am advocating is that perhaps more emphasis be placed on the user experience. I, for one, would be super happy to test a new release before it goes live. I am sure others would too.  The cost of such a test would be minimal in comparison to the costs of dealing with it after it has been released (i.e. AFAIK these Tracking Tabs are now on every CWP install).
