### ISSUE TITLE
replaceFile config doesn't seem to work

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#5624] opened 2016-06-01 02:18 UTC
Relates to #5137 (closed) but is still an issue using framework:master (b4c5c71a0b8) and cms:master (9feec1f1d) on PHP 5.6 (Sury) / Ubuntu 14.04. Also observed in a CWP (v1.2) setup, so using framework+cms v3.2.1.

No matter what I do, I cannot set or override `Upload::replaceFile` via YML config.

mysite/_config/config.yml

```yml
Upload:
  replaceFile: true
```
...dev/build flush=all

mysite/code/Page.php

```php
public function init() {
    // Same result using Upload::config()->replaceFile FWIW...
    Debug::dump(Config::inst()->get('Upload', 'replaceFile')); // `false`
    Debug::dump(Config::inst()->get('UploadField', 'overwriteWarning')); // `NULL`
    die;
}
```
Interestingly, I can _also_ hack framework's config.yml, and get the same result:

framework/_config/config.yml

```yml
Upload:
  # Replace an existing file rather than renaming the new one.
  replaceFile: true
```
...dev/build flush=all

```php
public function init() {
    // Same result using Upload::config()->replaceFile FWIW...
    Debug::dump(Config::inst()->get('Upload', 'replaceFile')); // `false`
    Debug::dump(Config::inst()->get('UploadField', 'overwriteWarning')); // `NULL`
    die;
}
```
FWIW I find the `UploadField` constructor logic clumsy:

```php
$this->replaceFile = self::config()->replaceFile;
```
I assume it's for legacy reasons, but why not make `replaceFile` a private (config) static and be done with it?

**Comment by JayDevlin** [comment] 2016-06-01 07:54
I cannot reproduce your problem with a 3.2.1 setup. Both replaceFile and overwriteWarning configs work as intended and are set on ?flush.

mysite/_config/config.yml
```
Upload:
  replaceFile: true
UploadField:
  defaultConfig:
    overwriteWarning: true
```
mysite/code/Page.php
```
var_dump( Config::inst()->get('Upload', 'replaceFile') ); // bool(true)
var_dump( Config::inst()->get('UploadField', 'defaultConfig') ); // array(9) {["overwriteWarning"] => bool(true) ...}
```

**Comment by JayDevlin** [comment] 2016-06-01 08:36
Maybe your ?flush does not work (because of the `arg_separator.output` php config?) or perhaps your `Upload:replaceFile` config gets overwritten by some other config file in your project.

**Comment by dhensby** [comment] 2016-06-01 09:35
Closing as can't replicate - assuming this is some other module or config setting overriding the value

**Closed by dhensby** 2016-06-01 09:35 UTC
