### ISSUE TITLE
$member->logOut() logs out a wrong user

### ISSUE THREAD

**Issue by Taitava** [silverstripe/silverstripe-framework#6308] opened 2016-11-09 23:42 UTC
Hi,

I just noticed that if I call `$member->logOut()`, it logs out the currently logged in member instead of the one that I have in the `$member` variable.

Although you rarely need to log anybody else out than your self, it still can be the case sometimes.

Thanks.

**Comment by dhensby** [comment] 2016-11-10 01:49
So logging a member out is a change of session state, really and not linked to any one member instance. I suppose logout should probably be a static method, rather than on an instantiated object...

**Comment by Taitava** [comment] 2016-11-17 02:55
I agree that logOut() could be made static. It would be clearer.

If anyone still has advices on how to log other members out, please let me know. Thanks! :)

**Comment by tractorcow** [comment] 2016-11-18 02:40
It's not possible without extending Member and quite a bit of extra work I'm afraid.

All of the logic in `Member::currentUserID` is based on the session.

You could create a RequestFilter and have a queue of users to log out on the server. You could then push to this queue, and have all requests validate that the current user isn't in this list, and otherwise log them out. Maybe?

**Comment by tractorcow** [comment] 2016-11-18 02:40
Closing as not a bug (even though we agree the API could be improved).

**Closed by tractorcow** 2016-11-18 02:40 UTC

**Comment by dhensby** [comment] 2016-11-22 17:02
> If anyone still has advices on how to log other members out, please let me know. Thanks! :)

The only way to log a user out would be to invalidate their session and/or destroy their autologin key.
