### ISSUE TITLE
IntlDateFormatter

### ISSUE THREAD

**Issue by bigbang1980** [silverstripe/silverstripe-framework#4794] opened 2015-11-25 17:04 UTC
As you know from php 5.3 and upper,we can use the "IntlDateFormatter" function.
how we can change the whole system calendar by using this following sample code?

$fmt = new IntlDateFormatter("fa_IR@calendar=persian", IntlDateFormatter::FULL,
IntlDateFormatter::FULL, 'Asia/Tehran', IntlDateFormatter::TRADITIONAL);

**Comment by tractorcow** [comment] 2015-11-25 20:40
In SilverStripe, which as far as I know doesn't use `IntlDateFormatter`, the correct way to set the locale is `i18n::set_default_locale`. Users can have their own locale, which will override this when they are logged in. You can use the `SS_DateTime::FormatFromSettings` to get this formatted date.

Does that answer your question?

**Comment by tractorcow** [comment] 2015-11-25 20:41
Since this is a question, not a bug, I'm closing this.

In future please use the [community forum](http://www.silverstripe.org/community/forums/) for these kinds of questions.

**Closed by tractorcow** 2015-11-25 20:41 UTC
