### ISSUE TITLE
DataQuery applyRelation has_one join incorrect foreignKey

### ISSUE THREAD

**Issue by hutlim** [silverstripe/silverstripe-framework#3954] opened 2015-02-28 06:33 UTC
$has_one = array_flip($model->has_one());

I getting incorrect foreignKey while I have multiple has_one with same class.

e.g.

$has_one = array(
    'Owner' => 'Member',
    'Father' => 'Member',
    'Son' => 'Member'
);

It always getting the "Son" as foreignKey.

**Comment by dhensby** [comment] 2015-02-28 12:38
possibly fixed by #3799 ? @kinglozzer ?

**Comment by kinglozzer** [comment] 2015-02-28 12:49
@hutlim have you defined the ´has_many´ side using the dot-notation like the example in the docs? Take a look at the last example under has_many http://doc.silverstripe.org/en/developer_guides/model/relations/

**Comment by hutlim** [comment] 2015-03-02 04:54
Yes. It's fixed on version 3.1.10.
I'm gonna upgrade framework to 3.1.10 version.

Thanks.

**Comment by hutlim** [comment] 2015-03-02 09:18
These error happen again. It's getting the last value as foreignKey.

Here is the example.

class OrderPackage extends DataObject {
    private static $has_one = array(
        'Member' => 'Member',
        'PaidBy' => 'Member',
        'SoldBy' => 'Member'
    );
}

debug::dump(OrderPackage::get()->filter('Member.Username', 'Hut.L')->sql());exit;

Below is the query debug.

SELECT DISTINCT "OrderPackage"."ClassName", "OrderPackage"."Created", "OrderPackage"."LastEdited", "OrderPackage"."MemberID", "OrderPackage"."PaidByID",
"OrderPackage"."SoldByID", "OrderPackage"."ID", CASE WHEN "OrderPackage"."ClassName" IS NOT NULL
THEN "OrderPackage"."ClassName" ELSE 'OrderPackage' END AS "RecordClassName" FROM "OrderPackage"
LEFT JOIN "Member" ON "Member"."ID" = "OrderPackage"."SoldByID" WHERE ("Member"."Username" = 'Hut.L')
ORDER BY "OrderPackage"."Created" DESC

**Comment by hutlim** [comment] 2015-03-02 09:26
I've debug the code from the DataQuery.php

	public function applyRelation($relation) {
		// NO-OP
		if(!$relation) return $this->dataClass;
		
		if(is_string($relation)) $relation = explode(".", $relation);

		$modelClass = $this->dataClass;
		
		foreach($relation as $rel) {
			$model = singleton($modelClass);
			if ($component = $model->has_one($rel)) {
				if(!$this->query->isJoinedTo($component)) {
					$has_one = array_flip($model->has_one());
					debug::dump($has_one);exit;


--------------------------------------------------------------------------------------------------------------

DataQuery.php:612 - DataQuery::applyRelation() - 
Array
(
    [Member] => SoldBy
)

**Comment by kinglozzer** [comment] 2015-03-02 09:26
Hmm, looks like this could be a regression from #3547 (though looking at `DataObject::getReverseAssociation()` which I removed, this bug may have always existed independent of that change)

**Comment by dhensby** [comment] 2015-03-02 09:34
OK, this may be related slightly to #3839 

It seems that the queries aren't very good at dealing with multiple queries on the same table.

**Comment by kinglozzer** [comment] 2015-03-02 09:45
Whoa.. the problem is with `array_flip`! Should have a fix and test for review soon :)

**Comment by kinglozzer** [comment] 2015-03-02 10:01
#3956

**Closed** 2015-03-03 00:13 UTC
