### ISSUE TITLE
NULL password results in server error. 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#10916] opened 2023-08-15 03:40 UTC
## Affected Version

Latest SS4

## Description
When I login as a user with a Password set to NULL and a PasswordEncryption set to NULL then I get a server error. 

What I would expect is a message:
"sorry, that is the wrong password, please use the password reset thingy" - like anyone else who logs in with the wrong password.

**Comment by Firesphere** [comment] 2023-08-15 03:50
But that's by design.

If it would give the response of "unkown user" or "password wrong", it would leak PII.
So, the generic response is correct. It's preventing data leakage.

**Comment by GuySartorelli** [comment] 2023-08-15 03:50
What is the error that is thrown, and where is it thrown from?

**Comment by sunnysideup** [comment] 2023-08-15 04:00
Lets firstly find out if this is supposed to be an error - and why.  I guess as a developer I can create a whole bunch of Members (e.g. through a related system) and not set a password, because I do not know their passwords (obviously). Then, if these members try to login, they create the following error:

![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/969dc4e2-596a-40bd-a36d-6abc9d0c26b9)

**Comment by sunnysideup** [comment] 2023-08-15 04:02
> But that's by design.
> 
> If it would give the response of "unkown user" or "password wrong", it would leak PII. So, the generic response is correct. It's preventing data leakage.

What you are saying is that it is a way to work out if the member exists?

**Comment by GuySartorelli** [comment] 2023-08-15 04:04
In this case I agree that this is by design. Creating a `Member` record programatically with no _password_ is one thing.
Creating them with no `PasswordEncryption` value is quite another. You must set a valid `PasswordEncryption` value on those records.

The system has no way of knowing how to "encrypt" (or "hash" if you prefer) the password in order to compare it with the stored password if `PasswordEncryption` is blank - so it's throwing this exception to tell the developer they've misconfigured something or got some bad code generating these records.

I'm going to close this issue as this is working as expected.

Though I will note that contrary to the information above, this exception is explicitly indicating that a member record with that username/email exists - so it's arguably leaking PII from that perspective.

**Comment by Firesphere** [comment] 2023-08-15 04:04
> What you are saying is that it is a way to work out if the member exists?

Yes

**Closed as not planned by GuySartorelli** 2023-08-15 04:04 UTC

**Comment by sunnysideup** [comment] 2023-08-15 04:12
Why not set the Password Encryption by default (e.g onBeforeWrite) so that someone without "intimate" knowledge of the ORM can simply write:
```php

$member = Member::create();
$member->FirstName = "Foo";
$member->Surname = "Bar";
$member->Email = "foo@bar.com";
$member->write();
```
?

**Comment by GuySartorelli** [comment] 2023-08-15 04:18
Member records which have a password defined _do_ get a `PasswordEncryption` value declared automatically through `onBeforeWrite()` which calls `encryptPassword()` which sets a default `PasswordEncryption` value if one wasn't already set.

It might make sense to set `PasswordEncryption` directly in `onBeforeWrite` if it hasn't been set, but ultimately having records like this in a production site is very much an edge case in the first place. I don't think it's worth dedicating the time to "fix" this. I'd review a PR if you want to raise one, though.

**Comment by sunnysideup** [comment] 2023-08-15 04:36
https://github.com/silverstripe/silverstripe-framework/pull/10917/files
