### ISSUE TITLE
HTMLEditorField in FieldGroup caused obtuse JavaScript error

### ISSUE THREAD

**Issue by SilbinaryWolf** [silverstripe/silverstripe-framework#7210] opened 2017-07-26 05:26 UTC
Doing something like the following in getCMSFields():
```php
$fields->addFieldsToTab("Root.MyTab", array(
    $fg = FieldGroup::create(
        HtmlEditorField::create('MyFieldContent', 'MyField Content')
    )
));
```

Causes the following JavaScript errors in console and HTMLEditorField doesn't appear at all:
```javascript
LeftAndMain.EditForm.js?m=1500872371:222 Uncaught TypeError: Cannot read property 'getInstance' of undefined
    at init.oneditorinit (LeftAndMain.EditForm.js?m=1500872371:222)
    at init.<anonymous> (jquery.entwine-dist.js?m=1500872398:1764)
    at one (jquery.entwine-dist.js?m=1500872398:1011)
    at init.prxy [as from .htmleditor_editorinit] (jquery.entwine-dist.js?m=1500872398:1036)
    at HTMLDocument.<anonymous> (jquery.entwine-dist.js?m=1500872398:1751)
    at HTMLDocument.dispatch (jquery.js?m=1500872400:3332)
    at HTMLDocument.eventHandle (jquery.js?m=1500872400:2941)
    at Object.trigger (jquery.js?m=1500872400:3210)
    at HTMLTextAreaElement.<anonymous> (jquery.js?m=1500872400:3869)
    at Function.each (jquery.js?m=1500872400:660)
```

**Comment by nglasl** [comment] 2017-07-26 05:31
Just chiming in on this one, as it's specific to **SS3.6** (possibly lower versions too) and hasn't been confirmed against **SS4**.

**Comment by adrexia** [comment] 2017-07-26 06:30
One work around right now it to make sure the field has a wrapper with '.field.htmleditor' classes. It looks like the small field holder by default is only including .htmleditor.

**Comment by tractorcow** [comment] 2017-07-27 22:14
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7220

**Comment by flamerohr** [comment] 2017-07-30 21:25
both this and the linked https://github.com/silverstripe/silverstripe-framework/issues/3260 issue describe the `3` branch, but the fix is for `4`

perhaps someone has a moment to backport the fix?

**Comment by tractorcow** [comment] 2017-07-30 22:10
Fixed in 3 branch with https://github.com/silverstripe/silverstripe-framework/pull/7213

**Closed by tractorcow** 2017-07-30 22:10 UTC
Labels: affects/v3, impact/medium, type/bug
