### ISSUE TITLE
Can't add Extension to ViewableData

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#6129] opened 2016-10-01 21:35 UTC
I want to make some methods available to all templates, so tried to add these to ViewableData. It doesn't work though, whether adding through PHP or config layer, the methods cannot be accessed, either directly or in templates. If I add the extension to the Controller class instead that works fine. Controller extends from ViewableData so I can't work out what's going on here.

Works:
`Controller::add_extension('MyExtension');`

Doesn't work:
`ViewableData::add_extension('MyExtension');`

I don't really want to settle for adding this to the Controller class as I want the methods to be available in emails etc. too, and it seems like this _should_ work.

Am I missing something here?

**Comment by tractorcow** [comment] 2016-10-02 20:22
Yes, you can use `TemplateGlobalProvider` to apply global methods for use in templates. Add the interface to any class, and then implement get_template_global_variables() to list the global methods you'd like to add.

**Comment by SpiritLevel** [comment] 2016-10-03 05:31
@jonom @tractorcow...In this oldish post https://www.silverstripe.org/community/forums/general-questions/show/19136 @wilr talks about putting global methods (and I suppose properties too) in `SiteConfig` and using the dot notation to access them in templates. 

I'm not sure if this an "acceptable" way to handle globals. Is implementing the `TemplateGlobalProvider` interface considered "best SS practice"? If so, how does one choose the class for implementing the interface? Perhaps `SiteConfig` is a good choice when there is no obvious class to host the method or property...

**Comment by wilr** [comment] 2016-10-03 08:13
That post likely predates TemplateGlobalProvider so being in existence (ss3) so SiteConfig shouldn't become a grab bag of everything.

**Comment by kinglozzer** [comment] 2016-10-03 08:22
> If so, how does one choose the class for implementing the interface? Perhaps SiteConfig is a good choice when there is no obvious class to host the method or property...

If there’s no logical class to add it to, just create a new one:

```php
class MySuperTemplateHelperClass implements TemplateGlobalProvider
{
    // ...
}
```

**Comment by jonom** [comment] 2016-10-03 15:39
Thanks guys, very helpful. That gives me a different way to solve the problem, but setting aside my original goal shouldn't it be possible to apply an extension to ViewableData? Is there a good reason you can't do it?

For example this doesn't work:

in _config.php
```php
ViewableData::add_extension('MyExtension');
```
Later:
```php
$vD = new ViewableData();
echo $vD->methodFromMyExtension();
```

Result: _[User Error] Uncaught Exception: Object->__call(): the method 'methodfrommyextension' does not exist on 'ViewableData'_

**Comment by jonom** [comment] 2016-10-03 16:41
BTW I opened a PR to add a hint to docs about how to use TemplateGlobalProvider as it only seems to be documented in the API at the moment https://github.com/silverstripe/silverstripe-framework/pull/6132

**Comment by SpiritLevel** [comment] 2016-10-03 19:41
Thanks @wilr @kinglozzer :)

@jonom Can you post your code for `ViewableData::methodFromMyExtension()` to see why it might not be working?

**Comment by jonom** [comment] 2016-10-03 22:51
@SpiritLevel it doesn't particularly matter what's in that method, the problem is that the method isn't accessible. But here is example code that demonstrates the inability for extensions to be added to ViewableData: https://gist.github.com/jonom/e13a3b571244e6e8900b18fb5cba8b96. The same extensions applied to DataObject or Controller works just fine.

@tractorcow I'm reopening this for now because ViewableData should be able to receive extensions like any other Object subclass shouldn't it?

**Comment by SpiritLevel** [comment] 2016-10-03 23:17
@jonom Thanks...just wanted to check access was public...but, then again, it already works with `Controller` (and `DataObject` going by your example).

I did notice that `Controller` and `DataObject` have various extension points defined in them while `ViewableData` doesn't have any. This is the likely cause.

**Comment by SpiritLevel** [comment] 2016-10-04 00:32
Tried to narrow down what is happening in `ViewableData`:

(1) `ViewableData` refuses to have new fields added as well as refusing new methods.

(2) I copied `framework/view/VewiableData.php` to `framework/view/ViewableDataTemp.php` and in it I renamed every occurrence of `ViewableData` to `ViewableDataTemp`. The extension works absolutely fine with `framework/view/ViewableDataTemp.php` allowing new methods and new fields to be added.

I'm using 3.4.

**Comment by jonom** [comment] 2016-10-04 00:38
Thanks for the interest and sleuth work @SpiritLevel!

**Comment by SpiritLevel** [comment] 2016-10-04 00:54
Sloth and sleuth are dangerously similar words :P One more piece of information:

(3) I defined 
```php
ViewableDataSubClass extends ViewableData {}
```

and was able to add new methods and fields to `ViewableDataSubClass` as well. 

After a cursory look over `ViewableData` and yml config files, I couldn't see if anything is getting added at run time to `ViewableData` causing a problem that `ViewableDataTemp` and `ViewableDataSubClass` are both free of.

**Comment by kinglozzer** [comment] 2016-10-04 08:07
Doh, I’ve just spotted why you can’t add extensions to `ViewableData`: it’s [explicitly marked as unextendable](https://github.com/silverstripe/silverstripe-framework/blob/2ab0dcf618590e69beff947ef6ed26dced852359/core/Object.php#L656). I can’t find any info on why that decision was taken, however...

**Comment by dhensby** [comment] 2016-10-04 12:28
That's *very* strange that a parent class is dictating properties of child classes.

BUT it looks like a config options  so can't we override that list if we want?

**Comment by jonom** [comment] 2016-10-04 15:23
@sminnee memory test! Do you remember if there is a good reason ViewableData shouldn't ever be extended? https://github.com/silverstripe/silverstripe-framework/commit/d8113a667e1ec9639c7318bc9755e8fc3eb5b75d#diff-0d087a82b0840f218d5b11d54057998dR510

**Comment by tractorcow** [comment] 2016-10-11 21:16
My guess it was an attempt to avoid anti-patterns that would have negative performance implications. Adding extensions to ViewableData adds extra methods to nearly every object in existence, which has a performance overhead that a templateglobalprovider doesn't.

I'm removing the "bug" flag since it's not a bug, it's an intentional restriction put in place.

**Comment by tractorcow** [comment] 2016-10-11 21:17
> ENHANCEMENT: Object::__construct() performance improved slightly.

Yep. :D

**Comment by jonom** [comment] 2016-10-12 18:47
Thanks @tractorcow I might just make a note about this in docs somewhere in that case then close this

**Comment by dhensby** [comment] 2016-10-13 10:58
I think it's probably better to warn devs not to do it, but let them, than to blacklist it... I don't think a parent class should know about it's inheritance structure in this way.

**Comment by sminnee** [comment] 2016-10-13 13:12
Let's get the docs in and close this issue. It's an incredibly bad idea to add an extension to ViewableData; I don't think docs are sufficient to block it and if you had a codified warning you would still end up with the coupling.

At some stage it would be good to do away with the ViewableData base class altogether and refactor it's functionality to be a part of SSViewer.

**Comment by jonom** [comment] 2016-10-13 16:45
PR: https://github.com/silverstripe/silverstripe-framework/pull/6181

**Comment by dhensby** [comment] 2016-10-16 13:25
docs merged

**Closed by dhensby** 2016-10-16 13:25 UTC
Labels: affects/v3
