### ISSUE TITLE
[CONTROL] [3.2] beforeCallActionHandler is called two times

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#5170] opened 2016-03-12 00:10 UTC
The problem comes from bad fix in de09bffd. The real problem is that default action is implicit and handled differently from other actions. It should be implemented as `Controller::index`

```
public function index(SS_HTTPRequest $request) {
    return $this->getViewer('index')->process($this);
}
```

see http://stackoverflow.com/questions/35865868/silverstripe-publish-page-in-the-future for example of extension

**Comment by tractorcow** [comment] 2016-03-13 19:35
It looks like you're correct... it was merged quite a while back.

https://github.com/silverstripe/silverstripe-framework/pull/3355

We should fix this on master, since removing it could have regression risks.

**Comment by tractorcow** [comment] 2016-03-13 19:37
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5173

**Comment by gregsmirnov** [comment] 2016-03-14 08:57
The #3355 now is open issue again for default action 'index'

**Comment by tractorcow** [comment] 2016-03-17 01:21
@gregsmirnov I've updated https://github.com/silverstripe/silverstripe-framework/pull/5173 so that the issue remains fixed.

**Comment by sminnee** [comment] 2019-05-27 04:41
Looks like this is all closed.

**Closed by sminnee** 2019-05-27 04:41 UTC
Labels: affects/v3, impact/medium, type/bug
