### ISSUE TITLE
main.php syntax error before php version check

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2956] opened 2014-03-15 15:41 UTC
anonymous functions where introduced in php5.3
however there is usage of it in [main.php#L117](https://github.com/silverstripe/silverstripe-framework/blob/050115f43141a850ac9d10f6a23be17695d31a76/main.php#L117),
which will result in an imidiate php syntax error. (`unexpected T_FUNCTION`)

**Comment by kinglozzer** [comment] 2016-03-26 18:57
Closing as it’s extremely unlikely that anyone’s trying to run SilverStripe on PHP 5.2 these days. If anyone really feels strongly about this then I guess we could move the `ErrorControlChain` stuff to a separate file to work around this?

**Closed by kinglozzer** 2016-03-26 18:57 UTC

**Comment by tractorcow** [comment] 2016-03-30 00:13
In the same file

https://github.com/silverstripe/silverstripe-framework/blob/050115f43141a850ac9d10f6a23be17695d31a76/main.php#L17

**Comment by kinglozzer** [comment] 2016-03-30 07:41
@tractorcow I believe the issue is a syntax error, so that’s unfortunately useless unless it’s in a separate file to the closure below :(

**Comment by tractorcow** [comment] 2016-03-31 22:15
Oh, i see. It's a compile time crash which is triggered before the run-time warning.
