### ISSUE TITLE
Review of SiteTree::duplicate

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#5030] opened 2016-02-12 01:06 UTC
There are several issues with current code

- hooks onBeforeDuplicate and onAfterDuplicate are called two times
- SiteTree calls hooks in reverse (hook is called on source, passing clone as argument, when DataObject calls hook on clone, passing the source instance)
- Object::invokeWithExtensions method has only two arguments, so calling it from duplicate() method, the argument $doWrite is lost

instead of SiteTree::duplicate, there should be just one hook method:

```php
public function onBeforeDuplicate(&$source) {
	$this->Sort = 0;
}
```

**Comment by tractorcow** [comment] 2016-02-14 21:39
This issue is a duplicate of https://github.com/silverstripe/silverstripe-cms/issues/1253. Also this is a CMS bug, so it should be on the correct repo. ;D

Thanks for the report anyway!

**Closed by tractorcow** 2016-02-14 21:39 UTC
