### ISSUE TITLE
Remove "application/javascript" fopr W3C validator

### ISSUE THREAD

**Issue by Blueace** [silverstripe/silverstripe-framework#10629] opened 2022-12-23 18:03 UTC
## Affected Version

4.12.0

## Description

W3C says that "The type attribute is unnecessary for JavaScript resources".

So, in order to pass the validation, in "vendor\silverstripe\framework\src\View\Requierements_Backend.php", please delete 

`              'type' => isset($attributes['type']) ? $attributes['type'] : "application/javascript",`

**Comment by christopherdarling** [comment] 2022-12-23 20:33
Dupe of https://github.com/silverstripe/silverstripe-framework/issues/8710 I think

**Closed as completed** 2022-12-24 00:14 UTC
