### ISSUE TITLE
Enum('0,+,++','0') does not list '0' as an option in a DropDownList

### ISSUE THREAD

**Issue by oetiker** [silverstripe/silverstripe-framework#5196] opened 2016-03-17 16:05 UTC
If I use `Enum('0,+,++','0')`, the entry '0' will not get listed in an automatically populated drop-down list. (v3.3.1)

**Comment by gregsmirnov** [comment] 2016-03-17 17:15
Why would you ever want to create such enum? MySQL stores enum values internally as integer keys to reference ENUM members, that should be readable names. On the other hand SS fields usually treat 0, auto-casted '0', empty string '', and `null` as empty/no value.

**Comment by JorisDebonnet** [comment] 2016-03-17 21:27
Doesn't matter why, if you want to create it, it should be possible. In any case, this looks like a duplicate of the issue that was created just 3 minutes before this one: #5195 (which I fixed)

**Comment by oetiker** [comment] 2016-03-18 08:09
It is an existing 2.4 website ... which just happens to have these 3 values in a field ...  actually it has these

`Enum(',0,+,++','')`

causing the dropdown list to start with two empty fields that can not be distinguished since both are just empty..

**Comment by gregsmirnov** [comment] 2016-03-18 11:06
@JorisDebonnet it does matter why. This is incorrect way of using MySQL Enum type, and the OP code should be fixed, not the framework.
@oetiker Yes, we had bad Enum usage cases when we were migrating from SS2.2 and 2.4 as well, and fixed the code.

**Comment by dhensby** [comment] 2016-03-18 11:15
@JorisDebonnet this is not a duplicate error - this is about how enum values are presented in dropdowns. It's more an issue with DropdownField than Enum

@gregsmirnov I agree with you, but also if it's a valid way of creating an enum (even if it's not best practice) then the framework should display it properly too.

This is the challenge of loose typing. @oetiker I think the most sensible thing you can do is extend dropdown field and handle this case in your own project as I don't see an elegant / easy way to fix this without bringing in regressions to other code bases. If you'd like to open a PR with a fix I will, of course, consider it and merge it if we don't see a high risk of regression.

**Comment by JorisDebonnet** [comment] 2016-03-18 15:10
Ah I'm sorry, I jumped to "duplicate!!" too quickly indeed. 

But I don't agree that it is "an incorrect way of using MySQL ENUM type". What's against having the values `'0','1','2','many'` for example? Yes, that 0 value is risky for use in a php application due to its falsy value, but then you just have to develop well. 

Anyway, since I was feeling productive, I fixed this issue as well. PR in a bit.

**Comment by dhensby** [comment] 2016-03-18 16:11
@JorisDebonnet that's just a bad way to use enums.

TBH, enums in general are flawed because if you change the enum set (remove an item) you corrupt your existing data. Enums are just too rigid and should be avoided for some better implementation but thats a side topic...

**Comment by gregsmirnov** [comment] 2016-03-18 17:37
Well... what might go wrong... from the top of my memory.

1. Invalid enum value in SQL query is evaluated as empty string, and oops we have declared empty string value.
2. Numeric values must be passed in SQL query as quoted strings, however with php auto-casting or improper usage, the integer may be passed (it is treated as incorrect value... and see point 1.)
3. SS specific: db schema will be altered every time you make dev/build when enum declared with numeric values. You are welcome to fix this as well.

@dhensby I like Coffeescript because it helps you to avoid silly mistakes, and it is safer to work with frameworks that don't allow (beginners) to make bad decisions.

**Comment by dhensby** [comment] 2016-03-18 18:16
Empty string, I think. 0 should be a legitimate value for a dropdown

**Comment by gregsmirnov** [comment] 2016-03-18 18:47
you are right, empty string is a valid php array key as well. Time to get rest. :)

**Comment by dhensby** [comment] 2016-03-18 19:04
I don't like the array to dropdown representation because you can only use a key once and there are valid usecases for having keys more than once in a select (alias labels, having items at top and in alphabetical order, etc)

**Comment by JorisDebonnet** [comment] 2016-03-18 19:09
I guess the main problem (concerning saving Enums) is we are limited by HTML forms, which can only send strings. In SQL queries, ENUMs can be filtered by both the string-values and the integer-keys, but when we are receiving HTML form data we can not discern between for example '3' (the value 3) and 3 (the third value in the ENUM list). So for the easy forms, we have to make do with the strings :) 

About things that can go wrong, you have a point with the second one, although it is avoidable of course: if people really want numbers as ENUM values, they'll just have to be careful when filtering. 

The other two points aren't really correct though: (1) Sending an invalid enum value into an SQL query will internally save it as the integer 0, while sending an actual empty string will save it as the integer 1 (if it is in fact the first defined value). And (2) using `Enum('0,1,2,3')` in SilverStripe does not cause rebuilding, I just tested it - but I did notice that it _does_ rebuild if you include an empty string (which is a tiny bug). But I guess that doesn't really hurt: MySQL won't lose data or anything.

**Closed** 2016-04-19 05:40 UTC
