### ISSUE TITLE
Form Field validation always fails if value is 0 (zero)

### ISSUE THREAD

**Issue by cmcramer** [silverstripe/silverstripe-framework#3849] opened 2015-02-04 16:37 UTC
In form fields including text, numeric, dropdown which are required, validation always fails if the value is "0" (the digit zero). 

1) A user enters "0" or "0" into a text or numeric field or "0" is chosen from a dropdown field.
2) "0" passes javascript validation, but fails php validation.

I'm running into this issue with the UserForms module, though I believe it originates in silverstripe-framewok. I haven't been able to figure out a work around.

**Comment by kinglozzer** [comment] 2016-03-26 18:38
Just tested on a 3.x site and a `0` passed to a text field marked as required with `RequiredFields` was accepted. `RequiredFields` checks `strlen($value)` so this should be fine, unless perhaps the issue is in the userforms module

**Closed by kinglozzer** 2016-03-26 18:38 UTC
