### ISSUE TITLE
Exception thrown when using Indonesian language in CMS

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#4955] opened 2016-01-20 02:15 UTC
When attempting to use Indonesian language as an interface language in the CMS an exception is thrown. Seems to be `framework/lang/id.yml` file (Possibly also in `framework/lang/id_ID.yml`)  (see below).

```
[User Error] Uncaught InvalidArgumentException: Unable to parse string: Malformed inline YAML string ("\n\tPenggunaan mahir\n\t\n\tKolom yang dibolehkan: %s\n\tPengguna yang sudah terdata dihubungkan dengan nilai Kode uniknya, \n\tdan diperbarui dengan nilai apapun dari berkas yang diimpor.\n\tKelompok dapat dihubungkan dengan kolom Kelompok. Kelompok diidentifikasi dengan properti Kode-nya,\n\tkelompok ganda dapat dipisahkan dengan tanda koma. Kelompok yang sudah terdata tidak terpengaruh.\n\t\n\).
```

**Comment by tractorcow** [comment] 2016-01-21 01:09
@phptek which branches have you tested this on? I can't seem to find this string you're noticing.

**Comment by tractorcow** [comment] 2016-01-21 01:24
I've resynced all translations with transifex... I can't see the string sorry. =/

**Comment by phptek** [comment] 2016-01-26 21:21
..checking

**Comment by sminnee** [comment] 2016-09-21 22:19
Gonna assume that this is a duplicate of #5957.

**Closed by sminnee** 2016-09-21 22:19 UTC
Labels: feedback-required/author
