### ISSUE TITLE
not able to install ss4 alpha2 on mamp

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-framework#6084] opened 2016-09-26 07:39 UTC
trying to install ss4 alpha2 isn't working on mamp because of warning about database credentials (although they are correct). Screenshots attached.
![schermafbeelding 2016-09-26 om 09 35 27](https://cloud.githubusercontent.com/assets/3098809/18826314/196300c2-83cd-11e6-9966-6421b7546ce1.png)
![schermafbeelding 2016-09-26 om 09 38 24](https://cloud.githubusercontent.com/assets/3098809/18826315/19676c34-83cd-11e6-81b4-f477b7a511bd.png)

**Comment by JorisDebonnet** [comment] 2016-09-26 09:04
I get the same issue on completely different setup (nginx with php 5.6). I get the exact same screenshot, and I suspect that strange fifth check to be the real issue. 

Clearly someone broke the installer before releasing alpha2 ;)

**Comment by lerni** [comment] 2016-09-26 11:18
same failure with the 5th check here with MAMP (PHP Version doesn't matter 5.5, 5.6, 7.0)

**Comment by SpiritLevel** [comment] 2016-09-27 00:25
I can confirm same installation problem with DB credentials on Ubuntu 14.04/16.04 and PHP5.6/PHP7.0.

I noticed some other (possibly related) things too, in addition to the 5th check and the mysterious "o" and "u" characters below it:

**(1)** If PDO is recommended for SS then maybe this should be checked by default instead of MySQLi:

![screenshot from 2016-09-27 13 10 02](https://cloud.githubusercontent.com/assets/8912185/18856028/ece8faf0-84b3-11e6-8009-9f620bd15f2f.png)

**(2)** The pink message boxes above are missing some information about modules. Also, the link given to download needed module gives a 404.

**(3)** None of the "Show All Requirements" accordions open when clicked on:

![screenshot from 2016-09-27 13 18 39](https://cloud.githubusercontent.com/assets/8912185/18856152/ef8e2266-84b4-11e6-8ed2-a9b5343ee4d5.png)

**Comment by thezenmonkey** [comment] 2016-09-27 18:49
@SpiritLevel accordians are related to another issue with the page calling a missing jquery [PR:6100](https://github.com/silverstripe/silverstripe-framework/pull/6100)

**Comment by SpiritLevel** [comment] 2016-09-27 19:18
Thanks @thezenmonkey.

**Comment by baukezwaan** [comment] 2016-09-28 09:47
The error is thrown because the getDatabaseConfigurationHelper throws an error:  "Couldn't load database helper code for MySQLPDODatabase" (same goes for MySQLDatabase). The mysterious error 'o' and 'u' are the 2nd and 3rd letter of this error message ;-)

Solution would be to add namespaces when loading the database helper:
[install.php5](https://github.com/silverstripe/silverstripe-framework/blob/master/Dev/Install/install.php5#L1050)
`$class = '\SilverStripe\Dev\Install\\' . str_replace('.php', '', basename($helperPath));`

But I'm not certain this is the way to help find the class in the right namespace. Anyone?

**Comment by baukezwaan** [comment] 2016-09-28 10:03
Next error in line while running the installer is 'I couldn't find a database server on 'localhost': Invalid connection type'. 

This is because in [MySQLDatabaseConfigurationHelper.php](https://github.com/silverstripe/silverstripe-framework/blob/master/Dev/Install/MySQLDatabaseConfigurationHelper.php#L29) the connection-type doesn't match. I believe the namespace notation here is causing the problem...

So I think that should be
`case 'MySQLDatabase':`
instead of 
`case 'SilverStripe\\ORM\\Connect\\MySQLDatabase':`

**Comment by laminbarrow** [comment] 2016-09-30 08:35
I had the same error too. I noticed it was looking for jquery in a location the server can't load if from.

`<script type="application/javascript" src="framework/thirdparty/jquery/jquery.js"></script>`

So in the end, i fixed it by applying the database details and default admin username and password in the _ss_environment.php file and then running dev/build.

Now the issue i have is that i can't load the admin becuase its looking for another file that doesn't exists.
`[Emergency] Uncaught InvalidArgumentException: File \framework/admin/client/dist/js/vendor.js does not exist`

I think running the node/webpack dev tools in the framework folder should fix that like to.
`cd ./framework
npm install
npm build`

**Comment by dhensby** [comment] 2016-09-30 11:36
@laminbarrow the dist file is definitely in the alpha2 release (https://github.com/silverstripe/silverstripe-framework/blob/4.0.0-alpha2/admin/client/dist/js/vendor.js)

Can you make sure you checked out the files correctly? Did you use composer?

**Comment by nblum** [comment] 2016-09-30 13:48
Same here on ubuntu 14.04
Tried installation with composer and archive

[phpinfo.pdf](https://github.com/silverstripe/silverstripe-framework/files/503088/phpinfo.pdf)

**Comment by laminbarrow** [comment] 2016-09-30 17:56
@dhensby I used the composer install command sent along in the alpha2 release notification via the Google Silverstripe developers group.

`composer create-project silverstripe/installer ./ss40 4.0.0-alpha2`

**Comment by tractorcow** [comment] 2016-10-11 00:30
Fix at https://github.com/silverstripe/silverstripe-framework/pull/6167.

These issues will be resolved in silverstripe 4.0.0-alpha3

**Comment by anselmdk** [comment] 2016-10-13 03:44
Yesterday night I installed latest SS4 this way (`composer create-project silverstripe/installer public dev-master`) and couldn't get past the installer. It kept on saying my db credentials weren't good. I ended up just deleting the installer and setting up an `_ss_environment.php` file.

**Comment by tractorcow** [comment] 2016-10-13 04:20
@anselmdk sorry about this... once we get the above fix merged in your installation should work again. :)

**Comment by tractorcow** [comment] 2016-10-26 01:15
This issue has outstanding PRs.

 - [ ] cms https://github.com/silverstripe/silverstripe-cms/pull/1644
 - [ ] postgres https://github.com/silverstripe/silverstripe-postgresql/pull/58
 - [ ] mssql https://github.com/silverstripe/silverstripe-mssql/pull/40
 - [ ] sqlite https://github.com/silverstripe/silverstripe-sqlite3/pull/29

**Comment by tractorcow** [comment] 2016-10-26 01:46
Ok now it's done. :) thanks @sminnee !

**Closed by tractorcow** 2016-10-26 01:46 UTC
Labels: affects/v4, impact/high, type/bug
