### ISSUE TITLE
Inconsistency: Dot notation failing with custom methods in summary_fields

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#7558] opened 2017-11-05 23:38 UTC
```
/**
 * Class Club
 * @package Vulcan\Derp\Models
 *
 * @property string Title
 * @property string Description
 *
 * @property int    ClubOwnerID
 *
 * @method HasManyList Events
 */
class Club extends DataObject
{
    private static $db = [
        'Title'       => 'Varchar(255)',
        'Description' => 'Text'
    ];

    private static $has_one = [
        'ClubOwner' => Member::class
    ];

    private static $has_many = [
        'Events' => Event::class
    ];

    private static $summary_fields = [
        'Title'              => 'Title',
        'ClubOwner.Name'     => 'Club Owner',
        'ActiveEvents.Count' => 'Active Events',
        'ClosedEvents.Count' => 'Closed Events'
    ];

    public function getActiveEvents()
    {
        return $this->Events()->filter([
            'EndDate:GreaterThan' => DBDatetime::now()
        ]);
    }

    public function getClosedEvents()
    {
        return $this->Events()->filter([
            'EndDate:LessThanOrEqual' => DBDatetime::now()
        ]);
    }
}
```

If I have:

```
    private static $summary_fields = [
        'ActiveEvents' => 'Active Events',
        'ClosedEvents' => 'Closed Events'
    ];
```

both methods "getActiveEvents" and "getClosedEvents" are found.

however if I have:

```
    private static $summary_fields = [
        'ActiveEvents.Count' => 'Active Events',
        'ClosedEvents.Count' => 'Closed Events'
    ];
```

I get 

> [Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'ActiveEvents' does not exist on 'Vulcan\Derp\Models\Club'

To resolve this I need to use the entire method name:

```
    private static $summary_fields = [
        'getActiveEvents.Count' => 'Active Events',
        'getClosedEvents.Count' => 'Closed Events'
    ];
```

**Comment by dhensby** [comment] 2017-11-06 11:14
Do you have a full backtrace for 

>[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'ActiveEvents' does not exist on 'Vulcan\Derp\Models\Club'

**Comment by dhensby** [comment] 2017-11-06 11:15
Also, the `get` prefix on models should only be used when creating pseudo properties - does renaming them break the first example:

```php
    private static $summary_fields = [
        'ActiveEvents' => 'Active Events',
        'ClosedEvents' => 'Closed Events'
    ];
```

**Comment by sminnee** [comment] 2019-03-08 04:05
This isn't a bug but it's obviously a bit confusing. It's also discussed in #8837. Recommend we improve the docs.

**Comment by maxime-rainville** [comment] 2019-03-19 04:34
Closing as duplicate of #8837

**Closed by maxime-rainville** 2019-03-19 04:34 UTC
Labels: affects/v3, change/patch, effort/medium, impact/medium, type/docs
