### ISSUE TITLE
NumericField formatting error in certain locales

### ISSUE THREAD

**Issue by forsdahl** [silverstripe/silverstripe-framework#10626] opened 2022-12-21 16:27 UTC
## Affected Version
4.11

## Description
NumericField has a formatting error when using the CMS in at least the Swedish and Finnish locales. If you input a number greater than or equal to 1000, the next time the form is saved the number will be empty, or you will get a validation error. This seems to be caused by some problem with the php NumberFormatter and space as grouping separator. If you disable grouping in `getFormatter`, the problem is resolved:
```
$formatter->setAttribute(NumberFormatter::GROUPING_USED, false);
```

The general solution might be to disable number grouping for all locales that have space as the grouping symbol? Like so:
```
if ($formatter->getSymbol(NumberFormatter::GROUPING_SEPARATOR_SYMBOL) == ' ') {
    $formatter->setAttribute(NumberFormatter::GROUPING_USED, false);
}
```

## Steps to Reproduce
Switch to Swedish locale in the CMS, and try to store a number greater than or equal to 1000 multiple times in any NumericField.

**Comment by GuySartorelli** [comment] 2022-12-21 20:05
This is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6910 - but given this issue has more details, I will close the other one.

**Comment by GuySartorelli** [comment] 2024-03-11 22:40
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/11162 which has an attached PR that got merged.

**Closed as not planned by GuySartorelli** 2024-03-11 22:40 UTC
Labels: impact/medium, complexity/medium, affects/v4, type/bug, affects/v5
