### ISSUE TITLE
Include Template can't read parent's variables

### ISSUE THREAD

**Issue by dylangrech92** [silverstripe/silverstripe-framework#9815] opened 2020-12-31 12:53 UTC
## Description
I have to explicitly pass variables to Include templates when using `renderWith()`.
Is this the correct behaviour?

## Steps to Reproduce
```
return $this->renderWith('MyTemplate', [
    'MyVar' => new MyClass()
]);
```

### This works
MyTemplate.ss
```
<p>$MyVar.SomeMethod</p>
```

### This doesn't work
```
MyTemplate.ss 
<% include MyInclude %>

MyInclude.ss
<p>$MyVar.SomeMethod</p>
```

### This works
```
MyTemplate.ss 
<% include MyInclude MyVar=$MyVar %>

MyInclude.ss
<p>$MyVar.SomeMethod</p>
```

**Comment by kinglozzer** [comment] 2021-01-04 09:41
Just out of curiosity - does this behave differently if you use:

```php
return $this->customise([
    'MyVar' => new MyClass()
])->renderWith('MyTemplate');
```

**Comment by dhensby** [comment] 2021-01-04 10:30
I believe this is by design

**Comment by lerni** [comment] 2021-01-04 10:51
related? to https://github.com/silverstripe/silverstripe-framework/issues/8580#issuecomment-436578137 and also links to "by design".

**Comment by dhensby** [comment] 2021-01-04 10:59
I'm not sure those two are related, but `includes` are not meant to inherit scope; their context needs to be passed in as show in the "this works" section.

I even had this "problem" way back in ss3, I think. It's not necessarily intuitive (as in PHP an "include" will inherit the variables declared in scope), but the templates aren't PHP and I don't think there's any desire from maintainers to change this behaviour especially when a thought out and reasonable decision was made at the time to explicitly exclude the external scope.

As such, I'm going to close this issue

**Closed by dhensby** 2021-01-04 10:59 UTC

**Comment by dylangrech92** [comment] 2021-01-04 11:06
Thanks for the clarifications guys, it's ok that it's by design just something to keep in mind moving forward :)

Thanks again.
