### ISSUE TITLE
table for filtered ID changed back to main table

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#5029] opened 2016-02-11 23:12 UTC
We are running 3.1 and found the following  issue:
```php
				$this->allProducts = $this->allProducts->filterAny(
					array(
						"DPP" => 1,
						"CAB:GreaterThan" => 1,
						"TIV:GreaterThan" => 1,
						"TestProduct_BonusProducts.ID" => array(null, '')
					)
				)
				->LeftJoin("TestProduct_BonusProducts", "TestProduct_BonusProducts.TestProductID = TestProduct.ID");
```

creates the following SQL

```sql
SELECT bla bla
FROM `SiteTree`
LEFT JOIN `Product` 
  ON `Product`.`ID` = `SiteTree`.`ID`
LEFT JOIN `TestProduct` 
  ON `TestProduct`.`ID` = `SiteTree`.`ID`
LEFT JOIN `TestProduct_BonusProducts` 
  ON TestProduct_BonusProducts.TestProductID = TestProduct.ID
WHERE ((`TestProduct`.`DPP` = '1')
  OR (`TestProduct`.`CAB` > 1)
  OR (`TestProduct`.`TIV` > 1)
  OR (`TestProduct`.`ID` IN ('', '')))
  AND (`SiteTree`.`ClassName` IN ('TestProduct'))
ORDER BY `SiteTree`.`Sort` ASC
```

This SQL is wrong:

```sql
  OR (`TestProduct`.`ID` IN ('', '')))
```

NULL value does not work - I think this is fixed here: https://github.com/silverstripe/silverstripe-framework/commit/392536cb1738f811b9716428638fb7cb518bf7a5

This could be labelled as an enhancement introduced in later versions, BUT also, the table is being changed.  That is a bug from what I can tell.

If we change the PHP to this:

```php
				$this->allProducts = $this->allProducts->filterAny(
					array(
						"DPP" => 1,
						"CAB:GreaterThan" => 1,
						"TIV:GreaterThan" => 1,
						"TestProduct_BonusProducts.ChildID" => array(null, '')
					)
				)
				->LeftJoin("TestProduct_BonusProducts", "TestProduct_BonusProducts.TestProductID = TestProduct.ID");
```

Then the SQL changes to: 

```sql
SELECT bla bla
FROM `SiteTree`
LEFT JOIN `Product` 
  ON `Product`.`ID` = `SiteTree`.`ID`
LEFT JOIN `TestProduct` 
  ON `TestProduct`.`ID` = `SiteTree`.`ID`
LEFT JOIN `TestProduct_BonusProducts` 
  ON TestProduct_BonusProducts.TestProductID = TestProduct.ID
WHERE ((`TestProduct`.`DPP` = '1')
  OR (`TestProduct`.`CAB` > 1)
  OR (`TestProduct`.`TIV` > 1)
  OR (`TestProduct_BonusProducts`.`ChildID` IN ('', '')))
  AND (`SiteTree`.`ClassName` IN ('TestProduct'))
ORDER BY `SiteTree`.`Sort` ASC
```

You can see that now the SQL is:

```sql
OR (`TestProduct_BonusProducts`.`ChildID` IN ('', '')))
```

Note the table change. 

This is a very dangerous bug as you can have all sorts of unexpected results from your ORM selection as far as I can tell (not so much perhaps in the NULL variation, but definitely if NULL was replaced with an array of ID numbers, as you will end up with a working system that provides a bogus result that may seem correct in some cases).

**Comment by tractorcow** [comment] 2016-02-14 21:18
Unfortunately there is no null filtering in 3.1; You need to use a literal addWhere for `WHERE "MyField" IS NULL OR "MyField" = ''`.

This feature is implemented in 4.0 https://github.com/silverstripe/silverstripe-framework/pull/4196

Sorry to be a pain, but I'm going to have to close this, since we have no way to back-port this to 3.1 without breaking semver.

**Comment by tractorcow** [comment] 2016-02-14 21:23
The feature in 4.0 also does things like convert `->exclude('Field', 'value')` into `"Field" != 'value' or "Field" IS NULL`, so there is that to take into consideration.

**Comment by sunnysideup** [comment] 2016-02-14 22:40
Hi @tractorcow, sorry but you have not addresses, AFAIK, the actual point of this Ticket.

The NULL thing in this ticket is a sideshow, This is about the final point above: 

![image](https://cloud.githubusercontent.com/assets/167154/13036718/f85ed21a-d3d3-11e5-9a62-a1a71c91831f.png)


As I said, I understand the null stuff is broken and will be fixed - you also acknowledge that.  That is great. 

However, what I see happening in my SQL is that if I put 
```php
"JoinTable.ID" => array(1,2,3)
```
The ORM changes this to 
```php
"OriginatingTable.ID" => array(1,2,3)
```

I have tried to set up a test case to replicate this systematically, but I have not been able to do so.  If I can find out exactly what happened then I will let you know and start a new ticket and/or ask this one to be reopened.

**Comment by tractorcow** [comment] 2016-02-14 22:55
Ok, so the bug is, when doing a composite filter on a joined table (`Joined.ID` in a filter) then it should NOT adjust the query to the base table, but should instead use the exact table specified in the filter.

Will need to think a bit about this issue; I understand that whenever we do a filter on ID, we typically prefer to filter on the base table (to support missing tables for dataobjects which actually exist in the base table). However, I can see the need to support this in a left join explicitly. I wonder if we can code in an exemption to the ClassInfo::table_for_object_field just for joins in search filters.

**Comment by tractorcow** [comment] 2016-02-14 22:57
SearchFilter::getDbName() is the bit we want to look at.... maybe if $this->name is `ID` we should always set $candidateClass to $this->model rather than invoking table_for_object_field at all. What do you think @sunnysideup ?

**Comment by sunnysideup** [comment] 2016-02-14 23:02
Hi @tractorcow ,

I have just confirmed the bug and it appears it is still there in 3.3.0.

Here is how to test it in 3.1.16 - add the following code to your page controller class: 

```php
	private static $allowed_actions = array (
		"test"
	);

	function test(){
		$objects = Page::get()
			->filterAny(array("Created:GreaterThan" => 1,"ErrorTable.ID" => 12))
			->leftJoin("ErrorPage", "ErrorPage.ID = ParentID", "ErrorTable");
		print_r($objects->dataQuery()->query()->getWhere()[0]->__toString());

		echo "<hr />";
		$objects = Page::get()
			->filterAny(array("Created:GreaterThan" => 1,"ErrorPage.ID" => 12))
			->leftJoin("ErrorPage", "ErrorPage.ID = ParentID", "ErrorTable");
		print_r($objects->dataQuery()->query()->getWhere()[0]->__toString());

		echo "<hr />";
		$objects = Page::get()
			->filterAny(array("Created:GreaterThan" => 1,"\"ErrorPage\".\"ID\"" => 12))
			->leftJoin("ErrorPage", "ErrorPage.ID = ParentID", "ErrorTable");
		print_r($objects->dataQuery()->query()->getWhere()[0]->__toString());

		echo "<hr />";
		$objects = Page::get()
			->filterAny(array("Created:GreaterThan" => 1,"\"ErrorTable\".\"ID\"" => 12))
			->leftJoin("ErrorPage", "ErrorPage.ID = ParentID", "ErrorTable");
		print_r($objects->dataQuery()->query()->getWhere()[0]->__toString());
	}

AND in 3.3.0-rc2 you can add:

```php
	private static $allowed_actions = array (
		"test"
	);


	function test(){
		$objects = Page::get()
			->filterAny(array("Created:GreaterThan" => 1,"ErrorTable.ID" => 12))
			->leftJoin("ErrorPage", "ErrorPage.ID = ParentID", "ErrorTable");
		print_r($objects->sql());
		echo "<hr />";
		$objects = Page::get()
			->filterAny(array("Created:GreaterThan" => 1,"ErrorPage.ID" => 12))
			->leftJoin("ErrorPage", "ErrorPage.ID = ParentID", "ErrorTable");
		print_r($objects->sql());
		echo "<hr />";
		$objects = Page::get()
			->filterAny(array("Created:GreaterThan" => 1,"\"ErrorPage\".\"ID\"" => 12))
			->leftJoin("ErrorPage", "ErrorPage.ID = ParentID", "ErrorTable");
		print_r($objects->sql());
		echo "<hr />";
		$objects = Page::get()
			->filterAny(array("Created:GreaterThan" => 1,"\"ErrorTable\".\"ID\"" => 12))
			->leftJoin("ErrorPage", "ErrorPage.ID = ParentID", "ErrorTable");
		print_r($objects->sql());
	}

```

As you can see, there is something broken at the core of the ORM.  I do not have the time to fix it so from here I will have to leave it anyone else who has more time and more brains than me ;-)

**Comment by tractorcow** [comment] 2016-02-14 23:47
I think the fix I suggested will probably resolve the issue, but of course it'll have to wait til I get the time to look at it. ;P I think this specific issue only affects search filters.

**Comment by sunnysideup** [comment] 2016-02-14 23:53
Thank you @tractorcow.

**Comment by dhensby** [comment] 2016-03-20 23:02
Duplicate of https://github.com/silverstripe/silverstripe-framework/pull/3839 ?

**Comment by tractorcow** [comment] 2016-03-21 04:14
Maybe...

@sunnysideup I wonder if you could please share your datamodel has_ones and has_many between the SiteTree and product classes. I think that would help me better understand the specifics.

**Comment by dhensby** [comment] 2016-03-25 23:29
OK - this is not a bug. I happened to experience the same thing.

When using the `filter` you don't use table names, you use the relationship names. You're directly targeting a table name `TestProduct_BonusProducts` which needs to actually be the `many_many` relationship name.

I experienced this "bug" recently when I missed an "s" of the end of a relation ship name:

```php
Order::get()->filter(array(
    'Booking.ID' => $this->CompleteBookings()->getIDList(),
));
```

And this ended up constructing SQL of `"Order"."ID" IN (...)` instead of `"Booking"."ID" IN (...)`

I was missing the "s" off of `Bookings` and so it couldn't resolve a relation and, thus, falls back to the base table.

I think this behaviour is a bit strange, but it's not the bug you describe, you're using the filtering incorrectly.

**Comment by tractorcow** [comment] 2016-03-28 21:37
> OK - this is not a bug. I happened to experience the same thing.

I think you may be right, @dhensby. That's why I've requested the code for the model so I can make a call.

> @sunnysideup I wonder if you could please share your datamodel has_ones and has_many between the SiteTree and product classes. I think that would help me better understand the specifics of how that exact SQL is being generated.

+1 to that, if you can, @sunnysideup :D

**Comment by sunnysideup** [comment] 2016-03-29 00:39
will do, but too busy right now... give me a few days.

**Comment by tractorcow** [comment] 2016-03-30 01:26
Ta. :D

**Comment by dhensby** [comment] 2016-04-08 17:10
few days past

**Closed by dhensby** 2016-04-08 17:10 UTC

**Comment by sunnysideup** [comment] 2016-04-08 19:25
sorry, totally slammed here with some big projects.  As soon as I have  breather I will go through all my SS Framework issues.

**Comment by dhensby** [comment] 2016-04-12 14:00
@sunnysideup no problem - we know exactly what it's like :)
