### ISSUE TITLE
Image gets rotated on upload

### ISSUE THREAD

**Issue by mylesthedev** [silverstripe/silverstripe-framework#3061] opened 2014-04-23 01:09 UTC
When adding an image via either the files tab or via the html editor certain images seem to get rotated either by 90 degrees or a complete 180.

I'm guessing this has something to do with the image it's self as it doesn't happen to all of them.

The original upload is fine it's just the re sample version that gets rotated.

**Comment by mediabeastnz** [comment] 2015-08-05 21:50
This still seems to happen on 3.1.13

**Comment by micschk** [comment] 2016-02-15 15:00
This module provides a quick fix for now (and a partial solution to be implemented in core): https://github.com/thisisbd/silverstripe-fixjpeg-orientation/blob/master/code/ImageExtension.php

**Comment by tractorcow** [comment] 2016-02-15 22:20
This sounds like a fun bug to fix on a day someone gets the time.

In 4.x assets has changed quite a great deal; It's probably a good idea to address this there. Maybe fix it in UploadField even before being assigned to an image?

**Comment by dhensby** [comment] 2016-03-20 22:54
This is most likely from images that have rotation meta data because they were taken on a phone

**Comment by digitall-it** [comment] 2016-11-11 15:37
If you try to load the images in Github, they appear rotated too. So it is a problem with GD or ImageMagick. Meanwhile, if you are on Windows, use [this program](http://savolai.net/software/JPEG-EXIF_autorotate) to correct whole folders at once.

**Comment by digitall-it** [comment] 2016-11-11 15:45
This function could do the trick with plain GD and also checks for support.

```
function correctImageOrientation($filename) {
  if (function_exists('exif_read_data')) {
    $exif = exif_read_data($filename);
    if($exif && isset($exif['Orientation'])) {
      $orientation = $exif['Orientation'];
      if($orientation != 1){
        $img = imagecreatefromjpeg($filename);
        $deg = 0;
        switch ($orientation) {
          case 3:
            $deg = 180;
            break;
          case 6:
            $deg = 270;
            break;
          case 8:
            $deg = 90;
            break;
        }
        if ($deg) {
          $img = imagerotate($img, $deg, 0);        
        }
        // then rewrite the rotated image back to the disk as $filename 
        imagejpeg($img, $filename, 95);
      } // if there is some rotation necessary
    } // if have the exif orientation info
  } // if function exists      
}
```

**Comment by digitall-it** [comment] 2016-11-11 15:52
Solution proposed by @micschk seems almost the same and already integrated, we should follow that instead.

**Comment by dhensby** [comment] 2016-11-11 15:54
looks good, let's PR!

**Comment by digitall-it** [comment] 2016-11-11 16:02
Tried thisisbd/silverstripe-fixjpeg-orientation on a fresh installation of v3.4.1 and it works fine.

**Comment by sb-relaxt-at** [comment] 2016-11-11 16:08
Based on the comment in this fix, I assume that all exif data is being removed when rotating the image. While removing the Orientation field is required, it might be not desired for other fields, as there might be information concerning the location, the artist, camera in use and so on.

**Comment by digitall-it** [comment] 2016-11-11 16:12
@sb-relaxt-at Yes, also there should be checked if rotation is actually lossless. We could use jhead but is a command line tool.

**Comment by SpiritLevel** [comment] 2016-11-11 21:43
Just wondering if [this animated image issue](https://github.com/silverstripe/silverstripe-cms/issues/1681) should be considered at the same time as the rotation one above, and, as @tractorcow suggests, for SS4 as well ?

More generally, it seems that there is a need for a SS-specific collection of helper functions to deal with things GD and Imagick don't handle quite the way we'd like. Despite what @dhensby says in  [the animated image issue](https://github.com/silverstripe/silverstripe-cms/issues/1681), I think supporting half a dozen helper functions might be a good idea and not to onerous; there are lots of code snippets already out there to borrow from, requiring only minor tweaking to fit into SS, and good image handling would make SS stand out. Just thinking out loud...

**Comment by dhensby** [comment] 2016-11-11 21:55
I'm 100% behind adding features to the image class offered by SS.

Regarding the issue with resizing animated gifs, I was only saying it's not a bug because SS *currently* makes no promise to support resizing of gifs.

FWIW for 4.0 I'd much rather we scrap our image manipulation backends for something like https://github.com/Intervention/image than waste time adding features to ours that are already built somewhere else.

**Comment by SpiritLevel** [comment] 2016-11-12 01:48
Thanks @dhensby 

Sorry to misinterpret/misrepresent your prior comment :) 

Yes, Intervention looks good. But isn't replacing the image manipulation backend a big job ? And, if this was opted for, would we not still need a few helper functions to deal with the immediate needs in 3.x ? Or, can Intervention go into 3.x "easily" ?

**Comment by digitall-it** [comment] 2016-11-13 03:34
I opened an issue on the libgd library regarding this.

Another approach can be a little more drastical: change the resizing functions so that the rotation happens there, and not on image upload. As during resizing and resampling EXIF data is lost anyway, and for any other reference the original file is still present, this would do the trick.

We should create a function that acts as a wrapper around imagecreatefromjpeg and replace it in resize functions (didn't check the sources, but I suppose that how's SS resizes images).

**Comment by dhensby** [comment] 2016-11-13 22:28
I like the idea of rotate when re-sampling BUT how does that affect the original image when it's displayed without being resampled?

**Comment by digitall-it** [comment] 2016-11-14 03:27
The original image, when not resampled, should be treated by the OS and the browser, as they are orientation aware. I.e. when you load an image with orientation in Github, it appears incorrectly rotated if seen in the context of the chrome of the site, because it gets resampled by a non exif aware library. When indeed you open the original file either in-browser as a direct connected link or as a forced download, it gets to be shown correctly, as the major browsers and file browsers (Finder, Explorer and so on) know how to display them.

**Comment by sb-relaxt-at** [comment] 2016-11-14 08:53
Unfortunately most browsers are not orientation aware when referring an image in an img tag. For example have a look at the following [test image](https://github.com/recurser/exif-orientation-examples/blob/master/Portrait_3.jpg) which is not rendered correctly (in Chrome). It is indeed rendered correctly when [opened directly](https://github.com/recurser/exif-orientation-examples/blob/master/Portrait_3.jpg?raw=true). There is no non-orientation aware library involved.

This seems to be the major reason against rotation-on-resampling. We are currently using a custom module for SilverStripe that rotates uploaded images immediately after upload. This seems to be the best way in order to allow using the "original" image as well. 

P.S.: These are really useful test images: [recurser/exif-orientation-examples](https://github.com/recurser/exif-orientation-examples)

**Comment by digitall-it** [comment] 2016-11-14 14:10
The rendering of images when transmitted in bit-per-bit fidelity is not the CMS concern. Thus, this type of workflow should be reserved for downloads, as we do not know if the image can contain custom metadata. Indeed, if this is the concern, we can add a function that returns the image autorotated at original size (will require resampling; will strip EXIF data; will not change original file, that is still available to read metadata). 

I'm against the autorotation on upload, I'm in favour of autorotation on resize/crop/resample.

**Comment by digitall-it** [comment] 2016-11-14 14:13
Please note that the issue opened on the GD library is going on; GD will apply autorotation on resampling itself in the near future. This could require no action by the Silverstripe CMS itself, OR it could check for functionality and autorotate on resize/crop/resample.

**Comment by digitall-it** [comment] 2016-11-14 14:22
@sb-relaxt-at you do not see the image correctly rendered just because it is resampled by GitHub in its own site chrome (GitHub is using a not EXIF aware library, probabily GD or ImageMagick theirselves) , but if you open it directly, Chrome will render it correctly, thus reinforcing the argument in favour of autorotation on resample, not against it.

**Comment by sb-relaxt-at** [comment] 2016-11-14 14:39
@digitall-it well I do agree that automatic rotation on upload is something that needs to be evaluated carefully, as it might not be the best default behaviour for all sites. A getter returning the rotated image in full resolution might be fine as well.

I just wanted to point out, that browsers do not respect exif orientation information when embedding an image via an img tag. The example presented does not use any resampling, it is just the raw image. But in order to show this more clearly, compare:  [in img tag](http://codepen.io/anon/pen/oYLjyG) versus [raw image](https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_3.jpg)

P.S.: I just learned, that there might be a [CSS property](https://developer.mozilla.org/de/docs/Web/CSS/image-orientation) going to solve this.

**Comment by digitall-it** [comment] 2016-11-14 14:46
Very clever, the CSS property is not very well supported [yet](http://caniuse.com/#feat=css-image-orientation), but interesting. Didn't bother to check out, you are right, the problem is in the img tag.

So, what are the use case against moving the autorotation to the resampling phase instead of the uploading one? We could still have an autoRotate() function to be called if we need to display the image without resizing or cropping and leverage SS built-in caching functionality. I would rather prefer to having to apply it on my sites instead of having my EXIF data magically stripped off on all the images on upload without knowing why.

**Comment by dhensby** [comment] 2016-11-14 16:20
Keeping a copy of the original image makes sense, rotating on manipulation also makes sense, though this still doesn't solve the problem where we want to load the original image on site but oriented correctly.

If GD is going to fix this problem upstream, how will that affect our patch/poly-fill?

**Comment by digitall-it** [comment] 2016-11-14 16:48
@dhensby an appropriated chain function can be called to prepare image for display if no resizing is required. This function will strip EXIF metadata and will be applied automatically if using using the framework image tag generation code.

For backward compatibility, I proposed in the GD issue that to avoid overcompensation the library should enable to turn off the feature, and/or to test for feature presence (`if GD && !GD->exifAware()`) , as indeed the GD library is working to provide a better native implementation that an upper polyfill (I proposed lossless transformation and EXIF data retention).

**Comment by dhensby** [comment] 2016-11-14 17:31
Can you provide a link to the issue with GD? Is Imagick working on it too?

**Comment by digitall-it** [comment] 2016-11-14 17:40
Already [did link to that issue](https://github.com/libgd/libgd/issues/341).

 ImageMagick does that by passing an operator called `-auto-orient` as per their [docs](http://imagemagick.org/Usage/photos/#orient), but their whole paragraph "JPEG Format is Lossy" is outdated, as there are new techniques to rotate images without reducing their quality and could be nice opening an issue regarding that. Did not conduct any test to see if EXIF data is retained on transformations.

A fix in the backends to be issued on image manipulation could implement both solutions.

**Comment by tractorcow** [comment] 2017-05-18 21:49
I suggest that we only re-rotate images on resampling, but don't touch original images.

**Closed as completed** 2017-07-27 16:30 UTC
Labels: type/enhancement, impact/low, complexity/medium, affects/v4
