### ISSUE TITLE
4.0.0-alpha5

### ISSUE THREAD

**Issue by sachithra-gayan** [silverstripe/silverstripe-framework#6784] opened 2017-04-06 07:30 UTC
hi
i got an error when dev/build run
```PHP Fatal error:  Uncaught exception 'MJS\TopSort\CircularDependencyException' with message 'Circular dependency found: modelascontrollerroutes->**-extensions->modelascontrollerroutes' in /var/www/html/**/vendor/marcj/topsort/src/CircularDependencyException.php:34
Stack trace:
#0 /var/www/html/**/vendor/marcj/topsort/src/Implementations/BaseImplementation.php(57): MJS\TopSort\CircularDependencyException::create(Array)
#1 /var/www/html/**/vendor/marcj/topsort/src/Implementations/ArraySort.php(63): MJS\TopSort\Implementations\BaseImplementation->throwCircularExceptionIfNeeded(Object(stdClass), Array)
#2 /var/www/html/**/vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array)
#3 /var/www/html/**/vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array)
#4 /var/www/html/**/vendor/marcj/topsort/src/Implementations/ArraySort.php(115): MJS\TopSort\Imple in /var/www/html/**/vendor/marcj/topsort/src/CircularDependencyException.php on line 34
```
with 
"silverstripe/cms": "4.0.0-alpha5",
 "silverstripe/framework": "4.0.0-alpha5",

**Comment by kinglozzer** [comment] 2017-04-06 08:26
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6700. Please remove the before/after block in `mysite/_config.yml`, or try installing 4.0.0-alpha6 instead, thanks!

**Closed by kinglozzer** 2017-04-06 08:26 UTC
