### ISSUE TITLE
Unable to unset a session variable

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#6052] opened 2016-09-21 12:20 UTC
As per title using version 3.4.1

**Page 1**

``` php
$session = Session::get('MySessionVar');
/*
array(
    "Foo" => "Bar",
    "Key" => "Value"
)
*/

unset($session['Foo']);
Session::set('MySessionVar', $session);
```

**Page 2**

``` php
$session = Session::get('MySessionVar');
/*
Still returns the array with "Foo":
array(
    "Foo" => "Bar",
    "Key" => "Value"
)
*/
```

The only way I can get around this is by setting `Foo` to `FALSE`

Having also tried:

``` php
$session = Session::get('MySessionVar');
Session::clear('MySessionVar');
Session::set('MySessionVar', $session);
```

... the result remains the same
# HOWEVER

If I were to `set` and `get` in the same page, the result is as you would expect

``` php
$session = Session::get('MySessionVar');
/*
array(
    "Foo" => "Bar",
    "Key" => "Value"
)
*/

unset($session['Foo']);
Session::set('MySessionVar', $session);
$session = Session::get('MySessionVar');
/*
array(
    "Key" => "Value"
)
*/
```

So it appears the problem may be within the way `Session()->changedData` is dealt with

The scenario here (for your understanding) is traversing back through pages of a 5 step process where if you traverse back to step 4, you want to destroy any variables that were set in step 5 and likewise if you were to traverse back to step 3 then destroy any variables set in step 4 etc etc.

I did notice the PHPDoc note on `inst_save()`: 

> Only save the changes, so that anyone manipulating $_SESSION directly doesn't get burned."

.. so this may very well be intended behavior depending on how semantic your developer gets in his descriptions

Cheers :)

**Comment by robbieaverill** [comment] 2016-09-22 02:49
If you call `Session::save()` after `::set(...` does it behave correctly?

**Comment by ReeceA** [comment] 2016-09-22 04:24
Will test shortly @robbieaverill and update this comment

**Comment by ReeceA** [comment] 2016-09-22 05:17
@robbieaverill Same result, the unset variables remain on the next page load

**Comment by ErangaLakmal** [comment] 2018-04-01 17:38
Is this bug still remains. I have faced to the same problem in the latest SS framework. Any positive answer is realy appreciate,

**Comment by ErangaLakmal** [comment] 2018-04-01 17:52
I found a workaround here. https://github.com/silverstripe/silverstripe-framework/issues/1537

**Comment by tractorcow** [comment] 2018-04-02 21:30
This bug was fixed in 4.x, but it was done in a slightly non-semver way making it hard to port back.

See https://github.com/silverstripe/silverstripe-framework/pull/7825

**Comment by tractorcow** [comment] 2018-04-02 21:31
As expected, yes the issue is with savedData not storing deletions properly.

**Comment by dhensby** [comment] 2018-04-04 13:58
Although this clearly seems to be a bug, does `Session:clear('MySessionVar.Foo')` work?

**Comment by tractorcow** [comment] 2018-04-04 20:01
I would guess it doesn't from my experience.

**Comment by sminnee** [comment] 2018-10-04 02:02
I believe that this is a duplicate of #1537, which I tested in 4.3.x-dev and found has been resolved.

**Closed by sminnee** 2018-10-04 02:02 UTC
Labels: affects/v3, type/bug
