### ISSUE TITLE
[4.0 alpha 2] Requirements Failure in Install

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-framework#6101] opened 2016-09-27 14:22 UTC
I intially posted this to silverstripe/silverstripe-installer, howeer the error actually happens in framework code. When installing on MAMP 4.0 with php 5.5.28 I get the following Requirements failure.

![silverstripe_cms___framework_installation](https://cloud.githubusercontent.com/assets/1685217/18877733/1dc36b5a-849c-11e6-8c77-116f3699682e.png)

Not actually sure what the problem is.

**Comment by lerni** [comment] 2016-09-27 14:59
duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6084

**Closed** 2016-09-27 15:12 UTC
