### ISSUE TITLE
Trailing slash also added to external redirects

### ISSUE THREAD

**Issue by brasileric** [silverstripe/silverstripe-framework#11151] opened 2024-02-17 21:21 UTC
### Module version(s) affected

5.1.0

### Description

If add_trailing_slash is set true:

```
SilverStripe\Control\Controller:
  add_trailing_slash: true
```
a trailing slash is also added to external redirects like:

`$this->redirect('https//www.example.com/about-us');`

is redirected to **https//www.example.com/about-us/** and:

`$this->redirect('https//www.example.com/about-us?rank=1');`

is redirected to **https//www.example.com/about-us/?rank=1** (so with a slash after about-us)

In my opinion a trailing slash must be added to internal redirects only.

### How to reproduce

`$this->redirect('https//www.example.com/about-us');`

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11321

**Comment by maxime-rainville** [comment] 2024-02-19 20:55
I agree that [`Controller::redirect()`](https://github.com/silverstripe/silverstripe-framework/blob/bcbbfddd1ad6f70a2fd954b4bf71a236fd754527/src/Control/RequestHandler.php#L599) should probably respect whatever choice the developer hard coding the link made.

But I'm not sure this would have any practical impact, so I'm disinclined to prioritise this issue. Is there a scenario where this could lead to a problem for the end user?

**Comment by brasileric** [comment] 2024-02-20 11:04
> I agree that [`Controller::redirect()`](https://github.com/silverstripe/silverstripe-framework/blob/bcbbfddd1ad6f70a2fd954b4bf71a236fd754527/src/Control/RequestHandler.php#L599) should probably respect whatever choice the developer hard coding the link made.
> 
> But I'm not sure this would have any practical impact, so I'm disinclined to prioritise this issue. Is there a scenario where this could lead to a problem for the end user?

Hi Maxime. Thanks for your response. In most cases this will not be a problem I agree. But I have a redirect that goes to an affiliate link which is not working when added a trailing slash. I realize this is an issue on the side of the affiliate platform as well.

I agree with the low priority.

**Comment by brasileric** [comment] 2024-02-21 10:17
I'm experiencing a problem with some api authentication as well. Like:

`https://login.daisycon.com/oauth/authorize?response_type=code&client_id=`

Is changing to:

`https://login.daisycon.com/oauth/authorize/?response_type=code&client_id=`

And refused by the api.

**Comment by lekoala** [comment] 2024-02-28 16:54
just realised the same, spent 30 minutes troubleshooting why my openid provider wasn't working as expected because silverstripe decided to add a slash at the end of the redirect url...

**Comment by lekoala** [comment] 2024-02-28 17:03
@maxime-rainville i don't agree it's low priority, this can break things in unexpected ways!

i think the issue is due to Director::absoluteUrl() usage instead of what was in place before

https://github.com/lekoala/silverstripe-framework/commit/21c9c1310dc47b69a2a42568de46ed19dbd1c0df

this fixes the issue but maybe it should be considered that Director::absoluteUrl shouldn't try to rewrite an url that is working fine

in the meantime, i'm having a static utility doing this

```php
    public static function redirect(string $url, int $code = 302): HTTPResponse
    {
        $response = new HTTPResponse();
        return $response->redirect($url, $code);
    }
```

it's really odd to have to do that :-)

**Comment by johannesx75** [comment] 2024-03-11 10:48
@maxime-rainville please reconsider the low impact rating.

This breaks things with external services that are hard to trace and debug. For us it was "Sign in with Apple".

**Comment by lekoala** [comment] 2024-04-05 15:37
So actually, this is really annoying . It hit me again : i have a whitelisted url without a trailing slash in a third party service, and obviously, it doesn't work with the trailing slash... so... using absoluteURL has again broken my website :(

I've improved my snippet a bit to generate absolute urls it looks like this now

```php
    /**
     * A simpler approach to absolute urls
     * Does not mutate the url (ie trailing slashes) unless specified
     * @param string|null $url
     * @param ?bool $trailing With (true) or without (false) trailing slash. Leave null for no changes
     * @return string
     */
    public static function absURL(?string $url, ?bool $trailing = null): string
    {
        $url = $url ?? '';
        $url = ltrim($url, '/');
        $base = rtrim(Director::absoluteBaseURL(), '/');
        // Append base url if needed
        if (!str_contains($url, $base)) {
            // Add base if it's not an external redirect
            if (!preg_match('/^http(s)?:/', $url)) {
                $url = $base . '/' . $url;
            }
        }
        // Add or remove trailing slash
        if ($trailing !== null) {
            $split = explode('?', $url);
            $url = rtrim($split[0], '/');
            if ($trailing) {
                $url .= '/';
            }
            if (!empty($split[1])) {
                $url .= '?' . $split[1];
            }
        }
        return $url;
    }
```

**Comment by chtombleson** [comment] 2024-07-30 02:36
This is causing an issue with Windcave/Omnipay module. I have had to implement a workaround until this is fixed.

**Comment by lozcalver** [comment] 2024-07-30 08:11
IMO the best fix here would be to add something like this to the start of `Controller::normaliseTrailingSlash()`:

```php
if (!Director::is_site_url($url)) {
    return $url;
}
```

I can’t see any reason why this behaviour ever _should_ apply to external URLs. Anyone disagree?

**Comment by lekoala** [comment] 2024-07-30 09:04
@kinglozzer  fully agree with you, adding trailing / to external url's don't make any sense

**Comment by draghu9** [comment] 2024-08-05 02:57
> This is causing an issue with Windcave/Omnipay module. I have had to implement a workaround until this is fixed.

What is the workaround you applied @chtombleson. I have added a redirect function within my controller class to remove the trailing slash. Unfortunately, that did not work for me.

**Comment by GuySartorelli** [comment] 2024-08-06 03:24
@emteknetnz Please link all relevant PRs in the issue description

**Comment by emteknetnz** [comment] 2024-08-06 03:25
Done

**Comment by GuySartorelli** [comment] 2024-08-07 00:51
PR merged. This will be automatically tagged by GitHub actions

**Closed as completed by GuySartorelli** 2024-08-07 00:51 UTC
Labels: complexity/low, impact/low, type/bug, affects/v5
