### ISSUE TITLE
CMS 5 beta regression: setter method not called when saving field through edit form

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-framework#10707] opened 2023-02-27 00:55 UTC
## Affected Version

`5.0.0-beta3`

## Description

* I have set up my `Page` with a basic text field
* I then create a `setter` method for that field
* Saving a value for this field through a CMS edit form should trigger the `setter` method(?)

Is Silverstripe 4 it does, but in Silverstripe 5 it does not.

## Set up

`Page.php`:
```php
class Page extends SiteTree
{
    private static array $db = [
        'MyTestField' => 'Varchar',
    ];

    public function setMyTestField($val)
    {
        $this->setField('MyTestField', strtolower($val));
    }

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->insertAfter('Title', TextField::create('MyTestField'));

        return $fields;
    }
}
```

### Silverstripe 4

Input value into field:
![Screen Shot 2023-02-27 at 1 44 54 PM](https://user-images.githubusercontent.com/505788/221448266-00b64711-3fda-409f-ba08-98cb89d53009.png)

Value after page is saved:
![Screen Shot 2023-02-27 at 1 45 42 PM](https://user-images.githubusercontent.com/505788/221448287-bf8b50d9-b9da-4b60-8321-e7a42fb8ea83.png)

### Silverstripe 5

Input value into field:
![Screen Shot 2023-02-27 at 1 47 22 PM](https://user-images.githubusercontent.com/505788/221448331-e520c23d-81fa-4598-8449-0fe5343b6541.png)

Value after page is saved:
**[no change to field value]**

### Working in both Silverstripe 4 and 5

Interestingly, if I create a test that explicitly sets a value to my field, then this correctly call my `setter` in both Silverstripe 4 and 5.

```php
class PageTest extends SapphireTest
{
    public function testSetMyTestField(): void
    {
        $page = Page::create();
        $page->MyTestField = 'Uppercase Words Here';

        Debug::dump($page->MyTestField);
    }
}
```

Output in both major versions:
```
====================================================
PageTest.php:16 - App\Tests\PageTest::testSetMyTestField()

uppercase words here
====================================================
```

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10708

**Comment by GuySartorelli** [comment] 2023-02-27 01:15
This is a direct result of https://github.com/silverstripe/silverstripe-framework/pull/10614

Where saving values from formfields used to go through the full `__set()` pipeline, it's now only going through `setField()` which has caused this regression, since it's no longer checking for and subsequently calling the setter methods.

**Comment by emteknetnz** [comment] 2023-03-01 02:19
Linked PR has been merged

**Closed as completed by emteknetnz** 2023-03-01 02:19 UTC
