### ISSUE TITLE
Unable to scroll edit page in Firefox

### ISSUE THREAD

**Issue by ewweaver** [silverstripe/silverstripe-framework#6170] opened 2016-10-11 22:36 UTC
When editing a page in firefox, you are unable to scroll down the page. You can tab down the form to edit the fields.

The toolbar with the publish / save buttons will not appear higher than the end of either the edit page form or the bottom of the site tree. This means that either is taller than you screen, you are unable to access the toolbar without tabbing all the way down the page to it.

FF 49.0.1

Works fine in Chrome.

**Comment by kinglozzer** [comment] 2016-10-12 08:30
Which version of SilverStripe are you using? I’m unable to recreate this in 3.4 / Firefox 49.0.1

**Comment by ewweaver** [comment] 2016-10-12 21:05
This is in master

**Comment by kinglozzer** [comment] 2016-10-13 08:46
Looks like a regression from the work to replace JLayout with Flexbox, two-part fix at:

- https://github.com/silverstripe/silverstripe-framework/pull/6180
- https://github.com/silverstripe/silverstripe-cms/pull/1647

**Comment by tractorcow** [comment] 2016-10-28 00:45
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1669

**Closed by tractorcow** 2016-10-28 00:45 UTC
