### ISSUE TITLE
Fatal Error on Install of Fresh SS4alpha5

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-framework#6717] opened 2017-03-16 19:37 UTC
I'm getting the the folloeing error in alpha 5 (both on upgraded aplha4 and fresh install)

```
Fatal error: Uncaught exception 'MJS\TopSort\CircularDependencyException' with message 'Circular dependency found: modelascontrollerroutes->mysite->modelascontrollerroutes' in /Applications/MAMP/htdocs/ss4test/vendor/marcj/topsort/src/CircularDependencyException.php on line 34
```

Installing on MAMP4 php 5.6.28 and php 7.0.13

**Comment by filisko** [comment] 2017-03-16 21:01
Do this:
https://github.com/silverstripe/silverstripe-framework/pull/6684/files

**Comment by kinglozzer** [comment] 2017-03-17 09:07
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6700, thanks for reporting

**Closed by kinglozzer** 2017-03-17 09:07 UTC
