### ISSUE TITLE
Conflict with nginx as a proxy introduced affecting 3.7 and not 3.6.6

### ISSUE THREAD

**Issue by digitall-it** [silverstripe/silverstripe-framework#8185] opened 2018-06-16 11:23 UTC
## Working Version
```
bugsnag/bugsnag                                   v3.13.0            Official Bugsnag notifier for PHP applications.
bummzack/silverstripe-omnipay-ui                  0.1.2              SilverStripe Omnipay UI Module
bummzack/sortablefile                             1.2.3              An extension for SilverStripe 3.1 that allows sorting of multiple attached images (extends UploadField).
eo/passbook                                       v2.1.1             iOS Passbook for PHP
hashids/hashids                                   2.0.4              Generate short, unique, non-sequential ids (like YouTube and Bitly) from numbers
heyday/silverstripe-menumanager                   2.2.2              Allows complex menu management to be handled through the CMS when a simple tree structure is not enough.
jdorn/sql-formatter                               v1.2.17            a PHP SQL highlighting library
jonom/focuspoint                                  2.5.0              Smarter automatic image cropping for SilverStripe
jonom/silverstripe-betternavigator                3.0.2              Front-end utility menu for SilverStripe websites featuring administration and development tools
jonom/silverstripe-share-care                     dev-master 3aa6611 Social media sharing previews and customisation for SilverStripe
lekoala/silverstripe-debugbar                     1.1.0              DebugBar for SilverStripe CMS
maximebf/debugbar                                 v1.15.0            Debug bar in the browser for php application
oddnoc/silverstripe-artefactcleaner               3.0.0              Find and optionally delete disused tables and fields in a SilverStripe database
omnipay/manual                                    v2.2.1             Manual driver for the Omnipay payment processing library
omnipay/paypal                                    v2.6.4             PayPal gateway for Omnipay payment processing library
omnipay/stripe                                    V2.4.7             Stripe driver for the Omnipay payment processing library
phpunit/phpunit                                   3.7.38             The PHP Unit Testing framework.
psr/log                                           1.0.2              Common interface for logging libraries
silverstripe-themes/simple                        3.1.1              The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/cms                                  3.6.6              The SilverStripe Content Management System
silverstripe/framework                            3.6.6              The SilverStripe framework
silverstripe/googlesitemaps                       1.x-dev 776e6bd    SilverStripe support for the Google Sitemaps XML, enabling Google and other search engines to see all urls on your site. This helps your SilverStripe website rank well in search engines...
silverstripe/lumberjack                           1.3.3              A module to make managing pages in a GridField easy without losing any of the functionality that you're used to in the CMS.
silverstripe/reports                              3.6.6              Reports module for SilverStripe CMS
silverstripe/silverstripe-omnipay                 2.5.0              SilverStripe Omnipay Payment Module
silverstripe/siteconfig                           3.6.6              Site wide settings administration.
silverstripe/widgets                              1.3.1              Widgets are small pieces of functionality such as showing the latest Comments or Flickr Photos. They normally display on the sidebar of your website.
symbiote/silverstripe-addressable                 2.0.2              SilverStripe addressable and geocoding module
symfony/process                                   v3.4.11            Symfony Process Component
tecnickcom/tcpdf                                  6.2.17             TCPDF is a PHP class for generating PDF documents and barcodes.
thisisbd/silverstripe-fontawesome-iconpickerfield v0.4               Font Awesome Icon Picker for SilverStripe 3.1.x based on http://mjolnic.com/fontawesome-iconpicker
tractorcow/silverstripe-fluent                    3.8.1              Simple localisation for Silverstripe
tractorcow/silverstripe-opengraph                 3.1.0              Implementation of the Facebook Opengraph protocol for Silverstripe
unclecheese/betterbuttons                         1.3.14             Adds new form actions and buttons to GridField detail form for usability enhancements.
wilr/silverstripe-googlesitemaps                  1.6.0              SilverStripe support for the Google Sitemaps XML, enabling Google and other search engines to see all urls on your site. This helps your SilverStripe website rank well in search engines...
```

## Description

Silverstripe 3.7 under Plesk Onyx 17.8.11#10 with PHP 7.0.30 as FPM served by Apache can't show large subtrees.  A message in the top right shows "parserror". Logs do not show anything normal.

This has to do with the tree XHR transfers and interaction between ngix as a proxy between Apache. Up to version 3.6.6 (the one that is listed above) the problem can be mitigated by enlarging the proxy buffers by adding those additional nginx directives

```nginx
proxy_buffers 32 128k;
proxy_buffer_size 128k;
```

and by upping the numbers as needed. In v3.7 seems like it doesn't work anymore, maybe because the XHR subtree structure is different and/or larger.

Changing browser between Safari and Chrome didn't change the situation, and accessing the site without SSL didn't either.

## Steps to Reproduce

On this particular configuration (that is very very common amongst Plesk users) on 3.7 large subtrees cannot be opened in the tree in the CMS, whilst on 3.6.6 they can.

## Proposed course of action

Find out a working configuration for nginx, or patching the sourcetree XHR routines to work better with nginx as a proxy.

**Comment by dhensby** [comment] 2018-06-16 16:27
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/2183

**Closed by dhensby** 2018-06-16 16:27 UTC
