### ISSUE TITLE
[VERSIONED] Versioned::writeWithoutVersion() does create a new version if called into onAfterPublish()

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#3557] opened 2014-10-15 10:32 UTC
Like in subject, there is a strange behaviour of Versioned::writeWithoutVersion() when used inside onAfterPublish(). It creates a new record into SiteTree_versions _after_ the published record. If the function is called inside onBeforePublish() everything works well.

Here you are the result of the following query: select \* from SiteTree_versions where RecordID=12 order by Version desc

![bug_write_without_version](https://cloud.githubusercontent.com/assets/2427390/4644037/05072ce6-5456-11e4-8dc0-ad7fb0dc6ff6.png)

As you can see version 5 is the same of version 4, but it's not published. Both version are created during a single publish process.

My code is the following (the first line is commented since it triggers an error, so also documentation should be updated):

``` php
public function onafterpublish(&$original) {
    //parent::onAfterPublish();
    Debug::log('OnAfterPublish');
    $this->Number = 3;
    $this->writeWithoutVersion();
}
```

**Comment by sminnee** [comment] 2019-04-08 05:46
I can't replicated this issue in 4.x-dev (due to be 4.4) but I do note that when you publish, it's certain an extra version record that may be unnecessaryw.

**Comment by sminnee** [comment] 2019-04-08 05:51
From the looks of things this is intended behaviour. So I'm closing the original issue as fixed, and the subsequent one as not needing a changes.

**Closed by sminnee** 2019-04-08 05:51 UTC
Labels: affects/v3, change/patch, effort/hard, impact/medium, type/bug

**Comment by sminnee** [comment] 2019-04-08 05:55
Added a test related to this in https://github.com/silverstripe/silverstripe-versioned/pull/227
