### ISSUE TITLE
Sorting changes scope layering

### ISSUE THREAD

**Issue by nickspiel** [silverstripe/silverstripe-framework#4817] opened 2015-12-01 22:04 UTC
In the following examples `TeamMember` (DataObject) is a `has_many` on `TeamGrid` (DataObject).

The `Up` method is working fine in this instance: 

```php
<% loop $TeamMembers %>
<p class="name">{$Name}</p>
<p class="parent-property">{$Up.Property}</p>
<% end_loop %>
```

But as soon as I add a `Sort` function to the $TeamMembers collection the `Up` method no longer works:

```php
<% loop $TeamMembers.Sort('SortOrder') %>
<p class="name">{$Name}</p>
<p class="parent-property">{$Up.Property}</p>
<% end_loop %>
``` 

If I add a second `Up` it then works.

```php
<% loop $TeamMembers.Sort('SortOrder') %>
<p class="name">{$Name}</p>
<p class="parent-property">{$Up.Up.Property}</p>
<% end_loop %>
``` 

Let me know what other info you need.

**Comment by kinglozzer** [comment] 2015-12-01 23:10
Duplicate of #4015. It’s a tricky one because the current behaviour enables examples like this:

```php
<% with $HomePage.FeaturedProduct.Category %>
{$Title} // Category title
{$Up.Title} // "Featured product" title
{$Up.Up.Title} // Home page title
<% end_with %>
```

I suppose that “non-object” lookups like `.Filter()` and `.Sort()` shouldn’t be treated as a new scope, but I don’t know if it’s possible to detect that. Even if it is, this would be a breaking change and pretty difficult to communicate in documentation (though arguably not more difficult than the current behaviour!)

**Closed by kinglozzer** 2015-12-01 23:10 UTC
