### ISSUE TITLE
SiteTree.Version field don't update as expected.

### ISSUE THREAD

**Issue by stojg** [silverstripe/silverstripe-framework#2422] opened 2013-09-16 03:52 UTC
I found a somewhat annoying issue with the Version attribute doesn't update in certain circumstances.

The initial issue was discovered by changing a Page.Content field with data from another DataObject during a onBeforeWrite(). This saves fine when pressing the "save draft", but the version number of that Page doesnt update properly. This in it turns causes the version history view to be somewhat borked with the current version being below the latest version.

I've done a test case that I think should pass, but doesnt. It would be interesting to hear anyone else ideas around this.

``` php
<?php
class SiteTreeVersionBugTest extends SapphireTest {
    /**
     * Mimic the logic from CMSMain::save() with writeWithoutVersion() and later write()
     */
    public function testVersionShouldUpdate() {
        // Setup
        $page = new SiteTree();
        $page->Title = 'Initial Title';
        $page->writeWithoutVersion();
        $page->write();
        // assert passes
        $this->assertEquals(2, $page->Version, 'Version should be to 2');

        // Setup
        DataObject::flush_and_destroy_cache();
        $pageFromDB = SiteTree::get()->byId($page->ID);
        // assert fails
        $pageFromDB->Title = 'This is a new Title';
        $pageFromDB->writeWithoutVersion();
        $pageFromDB->write();
        $this->assertEquals(3, $pageFromDB->Version, 'Version should be 3');
    }
}
```

**Comment by tractorcow** [comment] 2017-05-18 21:24
Needs re-confirming and testing.

**Comment by sminnee** [comment] 2018-10-01 20:22
The issue here is that two things are occurring:

```
$pageFromDB->writeWithoutVersion();
```

Writes the changes, doesn't increment the version number as designed

```
$pageFromDB->write();
```

No changes to write, doesn't increment the version number as designed.

So I don't think this is a bug. It's possible that there's a bug in the upstream code (e.g. the CMSMain code that calls these methods), but since it was raised before a major rewrite of versioning 5 years ago, I'm closing.

**Closed by sminnee** 2018-10-01 20:22 UTC
Labels: affects/v3, affects/v4, change/patch, impact/low, type/bug
