### ISSUE TITLE
Injector instantiating wrong class

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#5286] opened 2016-04-09 01:29 UTC
After upgrading from `3.1` to `3.3`, one of my failed unit tests revealed that my custom database class was no longer being returned when using `DB::get_conn()`. Originally I used to define my custom class via the currently recommended method of `SS_DATABASE_CLASS` which results in the following equivalent call:

```php
// Defining custom database class.
define('SS_DATABASE_CLASS', 'CustomMySQLDatabase');

// ... somewhere in DB::connect()...
// This returns 'CustomMySQLDatabase' as expected.
$dbClass = $databaseConfig['type']; 

// This however returns an instance of 'MySQLDatabase' and *NOT* 'CustomMySQLDatabase' as 
// it used to in SilverStripe Framework 3.1
$conn = Injector::inst()->create($dbClass);
```

Here's my custom class, in case that has something to do with it (shouldn't):

```php
<?php

class CustomMySQLDatabase extends MySQLDatabase {

	public function text($values) {
		$charset = "utf8_general_ci";
		if (isset($values["character set"])) $charset = $values["character set"];

		$collate = "utf8_general_ci";
		if (isset($values["collate"])) $collate = $values["collate"];

		return "mediumtext character set $charset collate $collate";
	}

}
```

Am I doing something wrong or is this a bug in `Injector`?

**Comment by kinglozzer** [comment] 2016-04-11 08:19
Pretty sure this is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/4774. `Injector` is looking for configuration for `CustomMySQLDatabase` and is unable to find any, so it looks at the parent class and finds:

```yml
Injector:
  MySQLDatabase:
    class: 'MySQLDatabase'
```

That’s why it returns a `MySQLDatabase` instance. You should be able to work around it by adding this to your config:

```yml
Injector:
  CustomMySQLDatabase:
    class: 'CustomMySQLDatabase'
```

Not a regression from `Injector`: afaik this behaviour was present in 3.1, but the above config for `MySQLDatabase` wasn’t added until 3.2, hence why this has occurred now.

Re-open if I’m off the mark :)

**Closed by kinglozzer** 2016-04-11 08:19 UTC
