### ISSUE TITLE
Versioned Assets not publishing with unversioned dataobjects

### ISSUE THREAD

**Issue by ColmMcBarron** [silverstripe/silverstripe-framework#6949] opened 2017-05-22 11:52 UTC
When using File/Image assets in a has_one with different types of content (pages and dataobjects) there is a scenario where the images don't show up. The root cause seems to be Versioning/publishing.

If you have a has_one relationship on a page to an image, the image is versioned along with the page which makes sense.

If you then apply a has_one image to a data object (which isn't versioned), the image remains as draft and you have to manually go in and publish it in the assets/files section.

I also considered adding versioning to the data object, but that doesn't seem to have a publish option.

Temporary fix has been to have an onAfterWrite hook to publish the image in the data object.

**Comment by tractorcow** [comment] 2017-05-23 01:04
I wonder if we should split out ownership into something that isn't strictly versioned objects only; Then we could enforce auto-publishing in the way you describe. Then we could treat saving of un-versioned objects the same way as publishing of versioned objects.

I suggest to break out ownership into it's own extension, but have the silverstripe/versioned module add this directly to DataObject base class (meaning all objects automatically get ownership support).

```
class NonVersionedObject extends DataObject {
	private static $has_one = [
		'Banner' => Image::class,
	];
	// On save, Banner is published
	private static $owns = [
		'Banner'
	];
}

class VersionedObject extends DataObject {
	private static $extensions = [
		Versioned::class,
	];
	private static $has_one = [
		'Banner' => Image::class,
	];
	// banner is published only when this object is published
	private static $owns = [
		'Banner'
	];
}
```

@sminnee how does this thinking sound to you?

**Comment by sminnee** [comment] 2017-05-23 01:25
So... unversioned intermediary objects have `$owns` meta-data so that publishes can be triggered through them to the files?

Yes I think that would probably make things less confusing for SS3 developers.

However, my recommendation to a developer in that situation would be to put `Versioned` on the intermediary object as well. SS4 is much more designed for a "version all the things" approach...

**Comment by tractorcow** [comment] 2017-05-23 01:29
@ColmMcBarron while we sort this out, you have two temporary work arounds:
 - as you suggested, using an onAfterWrite hook
 - version your object and add "owns".
 
Please let me know how you feel about the other suggestion :)

**Comment by ColmMcBarron** [comment] 2017-05-23 08:37
@tractorcow going to stick with the onAfterWriteHook as I don't need versioning on these dataobjects right now.

Suggestion looks good!

**Comment by dhensby** [comment] 2017-06-27 15:08
@tractorcow are there plans to address this for the beta? @sminnee and you have a consensus on how to approach this and I think it does make sense that we can use unversioned objects with versioned objects

**Comment by tractorcow** [comment] 2017-06-27 22:26
It's not going to be addressed for beta1. Splitting ownership into a non-versioned module probably won't be until 4.1, since we are locking the api for 4.0 beta.

**Comment by axllent** [comment] 2017-06-27 22:55
@tractorcow Does that mean the suggested method of dealing with unpublished assets (for example) "belonging to" (eg via a `$has_one`, `$many_many` etc) is to "manually" publish them using an onAfterWrite hook?

I realise the vagueness of my question, and that it can depend on many things, however in (let's say) case where a unversioned DataObject has a `$has_one=['Image' => Image::class];`. The dataobject is saved, but the `$this->Image()` currently remains unpublished - Should the DataObject then get a onAfterWrite() which publishes the Image on save: `if ($this->Image()->exists() && !$this->Image()->isPublished()) { $this->Image()->doPublish(); }`).

I'm just looking for pointers as to the best practice moving forward, and once that's hopefully not going to backfire down the track.

**Comment by tractorcow** [comment] 2017-06-27 23:05
Yes for now, sorry =( I think what you've done is perfect as a suggested work-around. The issue is deciding and implementing a standard core solution.

**Comment by axllent** [comment] 2017-06-27 23:24
Thank you - at least I know I'm not just setting myself up for a catastrophe (we'll assume & hope at this stage) ;-)

Hopefully this gets addressed/decided upon sooner rather than later (ie: one of the betas) as it is such a core component in the framework and trivial to pretty much every project - at least in terms clear clarification of how a developer is expected to deal with associated versioned dataobjects.

**Comment by chillu** [comment] 2017-11-14 20:11
Closing as duplicate of https://github.com/silverstripe/silverstripe-framework/issues/7359

**Closed by chillu** 2017-11-14 20:11 UTC
Labels: affects/v4, change/minor, effort/hard, impact/high, type/enhancement
