### ISSUE TITLE
Increase Contrast in Backend

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-framework#6541] opened 2017-01-19 14:30 UTC
While the new lighter design is asthetically pleasing, some sections fail basic contrast checks for accessbility. Most notibly teh CMS Content Header (north) and the toolbar icons. Here is the contrast checker for reference
![banners_and_alerts_and_wcag_contrast_checker_by_acart_communications_inc_](https://cloud.githubusercontent.com/assets/1685217/22110490/e37f3f54-de29-11e6-8df9-c73a4d684ae4.png)

http://contrastchecker.com/?swatch_session=0046J4xAxnRt

**Comment by chillu** [comment] 2017-05-24 10:13
@clarkepaul

**Comment by clarkepaul** [comment] 2017-05-25 04:47
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6408 I don't think this issue has any additional detail so closing but if you feel there is something missing @thezenmonkey  feel free to add to the older issue.

**Closed by clarkepaul** 2017-05-25 04:47 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/enhancement, type/UX
