### ISSUE TITLE
Update lesson series for SS4

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5759] opened 2016-06-30 23:08 UTC
Mentioned by Ingo in #5734.

SilverStripe 4 will have many changes, including namespaces, and the lesson series will be out of date.

**Comment by chillu** [comment] 2017-10-11 20:20
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/7353

**Closed by chillu** 2017-10-11 20:20 UTC
Labels: affects/v4, type/docs
