### ISSUE TITLE
RFC: Rename all classes with underscores to be PSR-2 compliant

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#8636] opened 2018-11-26 11:47 UTC
## Affected Version

SilverStripe 5.x

## Description

Many classes in SilverStripe (by convention) have underscores in their names, e.g. `ViewableData_Customised`.

This is a kind of pseudo-namespace, and one which we don't need since we've introduced proper namespaces.

In order to achieve full PSR-2 compliance (#7991) we'll need to remove the underscores.

Suggested approach (example:

```diff
- SilverStripe\View\ViewableData_Customised
+ SilverStripe\View\ViewableData\Customised

- SilverStripe\View\ViewableData_Debugger
+ SilverStripe\View\ViewableData\Debugger
```

## Related issues

- [PSR-2 compliance](https://github.com/silverstripe/silverstripe-framework/issues/7991)
- [Removing _Disabled and _Readonly classes](https://github.com/silverstripe/silverstripe-framework/issues/8002)

**Comment by robbieaverill** [comment] 2018-11-26 21:04
Easy - moving to accepted with four votes in favour (myself @dhensby @kinglozzer and @ScopeyNZ)

**Comment by sminnee** [comment] 2018-12-07 00:02
I like the idea of removing underscores but I think that replacing `_` with `\` creates unnecessary namespace fragmentation.

So I would say that a default rule should probably be to replace `_` with `""`.

**Comment by robbieaverill** [comment] 2018-12-07 11:13
Ok, I think that we'd get into an area of personal preference for whomever picks this up so perhaps we can address the cases as they come up in peer review?

**Comment by GuySartorelli** [comment] 2023-09-08 01:29
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/7991

**Closed by GuySartorelli** 2023-09-08 01:29 UTC
Labels: type/enhancement, complexity/low, type/api-break, impact/medium, rfc/accepted, affects/v5
