### ISSUE TITLE
composer install leaves assets directory g-w

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7560] opened 2017-11-06 21:12 UTC
I am getting inconsistent results.  Some times it is writable and others not

Reproduce for a project named FOO

./composer.phar create-project silverstripe/installer ./FOO 4.0.0-rc3
$ ls -ld FOO/assets
drwxr-xr-x 2 worik worik 4096 Nov  3 17:01 FOO/assets

**Comment by chillu** [comment] 2017-11-12 19:31
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/7580

**Closed by chillu** 2017-11-12 19:31 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug
