### ISSUE TITLE
[2013-02-13] ManyManyList->removeAll() not working with JOINs

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1681] opened 2013-04-03 20:28 UTC
created by: @chillu (ischommer)
created at: 2013-02-13
original ticket: http://open.silverstripe.org/ticket/8258

---

ManyManyList causes a single DELETE query, as opposed to DataList which does one DELETE query per item. This means the single DELETE query needs to replicate all selection criteria if ot was "converted" from a SELECT query before. 

Emulating joins in deletes is possible, but its going to be gricky to satisfy all potential query permutations. My recommendation is to change to single-row DELETE queries which work on the results from executing the SELECT queries.

For context, this problem was discovered with "Group" queries breaking on usage of both subsites and advancedworkflow

**Comment by tractorcow** [comment] 2015-06-16 02:08
If this exists in 3.1 it needs to be fixed there also.

**Comment by dhensby** [comment] 2016-08-12 19:36
I don't get it, how's the problem replicated and how does it manifest itself?

**Comment by tractorcow** [comment] 2016-08-23 05:59
It sounds like the problem is limited to Member_Groupset. maybe just limit the suggested fix to that? (copy DataList::removeAll() to Member_Groupset).

**Comment by kinglozzer** [comment] 2016-08-23 08:33
Related to https://github.com/silverstripe/silverstripe-framework/issues/3948?

**Comment by tractorcow** [comment] 2016-11-16 02:52
ok, I'm closing this in favour of https://github.com/silverstripe/silverstripe-framework/issues/3948 which more precisely targets the issue (even though it's newer).

**Closed by tractorcow** 2016-11-16 02:52 UTC
Labels: change/major
